### ISSUE TITLE
Add support for DuckDuckGo POST Requests in omnibox and via right-click menu

### ISSUE THREAD

**Issue by hook321** [ungoogled-software/ungoogled-chromium#105]

**Comment by Eloston** [comment]
I don't know about this feature. What is the advantage of using POST requests over GET reequests?

**Comment by hook54321a** [comment]
Makes it more difficult for network managers to see what you are searching, if it is implemented it should be able to be turned on and off.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
