### ISSUE TITLE
Remove Sync (ie: "Not Signed In", "Turn on sync...", "Sync and Google services", etc) UI 

### ISSUE THREAD

**Issue by prurigro** [ungoogled-software/ungoogled-chromium#1130]
**Is your feature request related to a problem? Please describe.**

This isn't really a problem so much as that the UI is showing options for and suggesting the use of sync functionality which has been disabled.

**Describe the solution you'd like**

The package would feel much more complete if the account dropdown didn't have a broken sync icon, the message `Not signed in` and a big `Turn on sync` bubble. The `Sync and Google Services` menu and other settings that require being signed into a google account in the settings are much less in your face but is also a bit redundant.

**Describe alternatives you've considered**

I'm not sure if there's really an alternative way to remove something, but the dialogs in the account dropdown are definitely the most jarring.

**Additional context**

![redundant-sync-dropdown](https://user-images.githubusercontent.com/1149238/90060466-c3790880-dcb2-11ea-916d-7b9bfa1964bc.png)

![redundant-sync-setup](https://user-images.githubusercontent.com/1149238/90060469-c5db6280-dcb2-11ea-81c6-068c8debb872.png)

**Comment by wchen342** [comment]
Should this be merged with #224, #369, #999 to be one meta issue?

**Comment by Eloston** [comment]
Good idea, I'll add a meta issue to track these kinds of problems.

**Comment by LoganDark** [comment]
Looks like "Not signed in" is present again on Ungoogled Chromium 129

![image](https://github.com/user-attachments/assets/44913db3-3d63-4d8f-b61f-84ed6324e5b7)

could this issue be reopened?
