### ISSUE TITLE
Use the system color picker

### ISSUE THREAD

**Issue by haykam821** [ungoogled-software/ungoogled-chromium#1544]
## Is your feature request related to a problem? Please describe.

Right now, the color picker used for color inputs is a custom implementation unique to Chromium. In my opinion, this falls under the following category in [the README](
https://github.com/Eloston/ungoogled-chromium/blob/bd0ffd19bfb047ec5302415849593c54171fdbc7/README.md#L34):

> In addition, Google designed Chromium to be easy and intuitive for users, which means they compromise on transparency and control of internal operations.

The Chromium color picker lacks several key features, such as the multitude of color picker plugins available on macOS.

## Describe the solution you'd like

The system color picker should be opened instead.

## Additional context

The color picker used in the developer tools has more advanced options than the default color picker, so it can stay.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
