### ISSUE TITLE
Add "Auto Dark Mode for Web Contents Flag" to hamburger menu

### ISSUE THREAD

**Issue by antgustech** [ungoogled-software/ungoogled-chromium#1851]
**Describe the solution you'd like**
On Bromite on Android, the developer have added an option to enable or disable the Auto dark mode from the menu on each site.  Its dark by default but if there are issues with the page you can quickly disable it. I would like to have this feature in  ungoogled-chromium as well.

**Comment by DigitalNXZ** [comment]
absolutely want this! especially soundcloud and some sites with svgs I use are broken when using the force dark-mode
also sometimes, I wanna switch fast to see how sites are looking on both themes

**Comment by calhix** [comment]
Hello, I just wanted to show support for this issue. Having it work exactly as in Bromite (which doesn't require a restart) would be simply amazing.

**Comment by hamad12a** [comment]
The dark mode is too dark, how to customize it?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
