### ISSUE TITLE
Add a flag to remove "Share this page" button in Omnibox

### ISSUE THREAD

**Issue by arbitrary-dev** [ungoogled-software/ungoogled-chromium#1853]
![image](https://user-images.githubusercontent.com/6984946/156922500-08a5faa5-c225-4bd7-bacf-878bf0e6ee6b.png)

**Comment by metafates** [comment]
Yes, this is annoying

**Comment by Ph0rk0z** [comment]
This used to be a flag. chrome://flags/#sharing-hub-desktop-omnibox and a few more, basically anything with sharing hub in it.

Now its a policy: https://chromeenterprise.google/policies/#DesktopSharingHubEnabled

It started as a menu with copy link and save page, now it's got facebook and other social media crap in there.

Only other way is to remove whatever commit deprecated the flag.
