### ISSUE TITLE
Add a flag to remove "Install app" button in Omnibox

### ISSUE THREAD

**Issue by arbitrary-dev** [ungoogled-software/ungoogled-chromium#1854]
![image](https://user-images.githubusercontent.com/6984946/156922591-def328c5-8b64-482e-9141-18f8ad36a547.png)

**Comment by Ph0rk0z** [comment]
When I look in policies for v99 I see:

"ChromeAppsEnabled"
"AllowedDomainsForApps" (and limit it to fake.com or something)

I too want this gone but policies not working on arch right now for some reason. Maybe someone can try those?

**Comment by plashenkov** [comment]
Wow! Thank you @fossfreak!

**Comment by PF4Public** [comment]
Given that there exists a trivial solution and no one expressed willingness to implement it, I think we may close this issue.
