### ISSUE TITLE
Disable opening in existing browser session

### ISSUE THREAD

**Issue by infosisio** [ungoogled-software/ungoogled-chromium#1860]
I am particularly concerned with restricting a session within the current window it exists in.

Right now, if I have a sensitive session open in a window and another instance is spawned, it has access to it.

I don't want that, for security reasons.

Is there a way that ungoogled-chromium can make this happen?

**Comment by PF4Public** [comment]
> if I have a sensitive session open in a window and another instance is spawned, it has access to it

Please elaborate, which access does it have and how does it affect you?

> I am particularly concerned with restricting a session within the current window it exists in

Have you tried opening "sensitive session"s in incognito mode instead?

**Comment by infosisio** [comment]
@PF4Public The idea is, there should be an option that would allow restricting a session within the current window, to prevent the creation of new windows from having access to it. Unfortunately incognito mode windows share sessions between them so that doesn't help.
