### ISSUE TITLE
Add an option to hide the url/tab bar?

### ISSUE THREAD

**Issue by piens1** [ungoogled-software/ungoogled-chromium#1919]
It already works like that in fullscreen mode, not sure if it's a valid request since as far as I can tell this project is supposed to be as close to chromium as possible. I'd expect it to work like the qutebrowser/surf browser bar where you can pull it up when you need it or just as a flag in the settings.

**Comment by JanMaslo2** [comment]
I'm gonna start trying to implement it, help needed

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
