### ISSUE TITLE
Consider restoring the feature flag to disable dark theme in incognito mode

### ISSUE THREAD

**Issue by ssokolow** [ungoogled-software/ungoogled-chromium#1928]
**Is your feature request related to a problem? Please describe.**

As of Chrome 100, Google removed the ability to use a non-dark theme for Incognito Mode, and the one they force you onto is badly designed too. (eg. very low contrast between selected and unselected tab)

I've seen other people on places like /r/chrome/ [characterizing it as](https://www.reddit.com/r/chrome/comments/tspkm6/how_do_i_turn_off_dark_theme_in_incognito_mode/) "Google, the ad company, wants to annoy you into not using incognito mode so it's easier to track you", so I'm not the only one who hates this change.

**Describe the solution you'd like**

At least a patch to restore the feature flag I was using prior to Ungoogled Chromium 100 to allow incognito to share the same color scheme as non-incognito windows.

(I've modified my launcher to always use incognito mode, so it makes Ungoogled Chromium a bit of a pain.)

**Describe alternatives you've considered**

Anything else which would allow dark mode to be themed... though what I proposed is probably the simplest and easiest to implement by going back and grabbing the code Google removed.

**Comment by alleypa** [comment]
@ssokolow  do you think we will ever have the ability to get back the light theme in google incognito mode? There seems not alot happening in this space since chorme 100 release

**Comment by ssokolow** [comment]
I'm not sure why you're asking me.

Do I think Google will put it back? Doubtful. This is the company that solicited feedback for their decision to remove `http://` from the address bar for a year and then locked the thread as not productive when it was more or less entirely people asking for an explanation for what problem it solved and pointing out things it made buggier or more difficult.

**Comment by PF4Public** [comment]
Fixed in https://github.com/ungoogled-software/ungoogled-chromium/pull/1969

**Comment by alleypa** [comment]
Hi @PF4Public so please what do we need to set to control the google theming in incognito mode?

**Comment by PF4Public** [comment]
You need to enable the flag added in that PR.

**Comment by alleypa** [comment]
@PF4Public can you please provide steps to follow and to use to apply the flag. Much appreciated

**Comment by networkException** [comment]
You go to chrome://flags/#enable-incognito-themes and set the value to enabled
