### ISSUE TITLE
Adding chrome webstore extension by default 

### ISSUE THREAD

**Issue by m-jishnu** [ungoogled-software/ungoogled-chromium#1973]
### Description

add the chrome webstore extension by default

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I'm installed this project today and tried adding a chrome add blocker extension but i want then i googled and found an extension which solved my issue tho it took me some searching, reading the readme and some clicks to achieve it, so it would have been great if the extension or something similar was added by default out of the box in the app like you get in google chrome

### Possible solutions

it will be great if you guys added the chrome webstore extension by default it will save the users a google search and make this much more similar to  google chrome out of the box.

chrome webstore extension: https://github.com/NeverDecaf/chromium-web-store

**Comment by PF4Public** [comment]
I remember there was a discussion to implement some kind of out-of-the-box experience by opening a webpage with the most essential information for new installations. This discussion might need another round of consideration :)

**Comment by PF4Public** [comment]
> As there weren't any major objections

Can't agree. See #988 for example.

**Comment by PF4Public** [comment]
I remember there was a huge discussion about integrating external things like webstore extension and I remember writing something like "…and then there will be people who say «what is this thing doing in my browser? I didn't ask for it to be pre-installed! privacy-oriented with third-party code, huh?»…", but unfortunately cannot find the discussion itself and this comment is taken out of context now of course :( I think that discussion didn't end up in any definitive conclusion, but that's my memory of it as I couldn't find the source.

**Comment by networkException** [comment]
oh right, I remember as well now (although no luck finding the source either)

I guess we are forced to stick with documenting the prodecure then

**Comment by m-jishnu** [comment]
i guess an inbuild option to add extension will be great for most user since almost all uses the chrome store but if its not possible adding a guide in the wiki page as @networkException said would be helpful, the current doc manual way of doing is a bit tiresome. still in my opinion adding it as default feature would be the right thing.

**Comment by jazei-AR** [comment]
this chromium tries to take off of google services, so take in mind that google store is a service of google, but you can find another addblocker here in github... ublockorigin  so you can download that from github without using google store.... and be NO GAFAM please, take off of google please
