### ISSUE TITLE
A SUGESTION: it is dificult to see where is the link to download the broser... 

### ISSUE THREAD

**Issue by jazei-AR** [ungoogled-software/ungoogled-chromium#1984]
Hi, could you put the steeps for download the browser.. I was looking for and not found that, so I download it from https://www.softpedia.com/get/Internet/Browsers/?utm_source=spd&utm_campaign=postdl_redir 
may be if your put in action the wiki page it helps about this matter for simple users like me 
thank you

**Comment by networkException** [comment]
The readme already contains enough information https://github.com/ungoogled-software/ungoogled-chromium#downloads to get a binary.

I would generally not recommend downloading software from random website with no association to a project whatsoever.
