### ISSUE TITLE
Can't detect and update components on chrome://components

### ISSUE THREAD

**Issue by AnErrorHasOccurred** [ungoogled-software/ungoogled-chromium#1987]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

101.0.4951.64

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

chrome://components failed to update components and detect their versions

### How to Reproduce?

1. Go to chrome://components and you'll find every component has the same version of 0.0.0.0
2. Click on 'Check for update', it shows 'Updater started'
3. Click on 'Check for update' again, it shows 'Checking for status…'
4. Keep Clicking and waiting, nothing happens

### Actual behaviour

Described in 'How to Reproduce?' section

### Expected behaviour

Every component shows its version and can be updated successfully

### Additional context

As we know UC has trouble playing DRM protected content, even if you follow the [guide](https://chromium.woolyss.com/#comment-1500), it still won't work properly (see #1258).

To most people my issue seems to be a subtle one, but I'm afraid it is components checking failure that leads WidevineCdm to behave abnormally.

I've tested on Chrome, Brave, Vivaldi and Edge, Widevine works properly with them. And on their components page every component shows it version and can be updated successfully. 

Widevine also did nothing wrong, I checked the CRC32 of WidevineCdm folder, Brave and Vivaldi store it in UserData, they are same, Chrome and Edge store it in Application\[version] folder and they are same too.

So there might be some problems on ungoogled layer(?) (#1831 ) I hope this info are helpful for solving problem.

**Comment by PF4Public** [comment]
Answered in https://github.com/ungoogled-software/ungoogled-chromium/issues/1836#issuecomment-1036455051
