### ISSUE TITLE
Patches for Chromium from ROSA Linux

### ISSUE THREAD

**Issue by mikhailnov** [ungoogled-software/ungoogled-chromium#1990]
### Description

Proposing to include some patches from ROSA into Ungoogled Chromium

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

Hello!

I maintain Chromium in ROSA Linux and have recently made some patches that may be useful from ungoogled-chromium.

1. First of all, I borrowed [block-requests.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/block-requests.patch) from ungoogled-chromium
2. [0001-Functional-new-tab-page-with-non-Google-search-engin.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0001-Functional-new-tab-page-with-non-Google-search-engin.patch) makes new tab page be usable if Google is not the default search engine
3. [0001-Functional-new-tab-page-with-non-Google-search-engin.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0001-Functional-new-tab-page-with-non-Google-search-engin.patch) sets Yandex as the default search engine for multiple regions. Approach used in ungoogled-chromium is simplier: Google is simply replaced with no search, but it makes Google miss in the list of search engines. Maybe my approach could be used to add a new — empty — search engine and set it as the default one to let users choose Google in the settings if they want to. But this may require more rediffs on updates.
4. [0003-Remove-voice-search-button.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0003-Remove-voice-search-button.patch) removes not working voice search button (broke probably when Googled blocked API keys for Chromium)
5. [0004-Hide-sync-with-Google.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0004-Hide-sync-with-Google.patch) removed not working buttons to turn on syncing with Google account

Also, Google logo in new tab page is replaced.

Most recent spec file and pathes are here: https://abf.io/import/chromium-browser-stable
If links above stop working, go here: https://abf.io/import/chromium-browser-stable/tree/2162f3096f

I think patch 0004 is simple and can be easily imported into ungoogled-chromium.

### Possible solutions

.

**Comment by PF4Public** [comment]
Are proposed patches align with ungoogled-chromium objectives? I doubt yandex'ing fits at all.

**Comment by mikhailnov** [comment]
I do not propose to yandex. I propose to change https://github.com/ungoogled-software/ungoogled-chromium/blob/01d2845/patches/core/ungoogled-chromium/replace-google-search-engine-with-nosearch.patch so that my approach is used, but default to that empty search engine instead of Yandex.

**Comment by mikhailnov** [comment]
I can prepare such a patch if needed

**Comment by PF4Public** [comment]
> 1. First of all, I borrowed [block-requests.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/block-requests.patch) from ungoogled-chromium

`Proposing to include some patches from ROSA into Ungoogled Chromium` point one included?

> 2\. [0001-Functional-new-tab-page-with-non-Google-search-engin.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0001-Functional-new-tab-page-with-non-Google-search-engin.patch) makes new tab page be usable if Google is not the default search engine

This one actually has some value to it.

> 3\. [0001-Functional-new-tab-page-with-non-Google-search-engin.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0001-Functional-new-tab-page-with-non-Google-search-engin.patch) sets Yandex as the default search engine for multiple regions.

I was having difficulties making sense of this, until it occurred to me that you meant `0002-Yandex-as-default-search-engine.patch` instead. 

Apart from that it is very-very vaguely phrased: `Proposing to include some patches from ROSA into Ungoogled Chromium` → <s>`0001-Functional-new-tab-page-with-non-Google-search-engin.patch`</s> `0002-Yandex-as-default-search-engine.patch sets Yandex as the default search engine` → `I do not propose to yandex`. What is your proposition exactly?


> * [0003-Remove-voice-search-button.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0003-Remove-voice-search-button.patch) removes not working voice search button (broke probably when Googled blocked API keys for Chromium)

Where is this button?

> * [0004-Hide-sync-with-Google.patch](https://abf.io/import/chromium-browser-stable/blob/rosa2021.1/0004-Hide-sync-with-Google.patch) removed not working buttons to turn on syncing with Google account

Where is this button?
