### ISSUE TITLE
Incognito Causes Logouts After Some Time

### ISSUE THREAD

**Issue by dm17** [ungoogled-software/ungoogled-chromium#1997]
### OS/Platform

Arch Linux

### Installed

Flatpak

### Version

102.0.5005.115 (Official Build, ungoogled-chromium) (64-bit) 

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Incognito causes logouts after some time

### How to Reproduce?

1) Open incognito window and login to a site that you know can stay logged in
2) Leave the window open for about 12h
3) Revisit the window and discover (all of your logins) are logged out

### Actual behaviour

All sites are logged out

### Expected behaviour

All sites are logged out only if the incognito window closes

**Comment by dm17** [comment]
> Could you name specific sites this happens with?

Any site so far that has a login. I've tested Stripe, Gmail, and a few others. They all logout at the same time as if cookies were automatically cleared.

**Comment by PF4Public** [comment]
You've ticked both "upstream" checks. Did you use the same profile for the checks?

**Comment by dm17** [comment]
> You've ticked both "upstream" checks. Did you use the same profile for the checks?

Yes I regularly use chromium & chrome in this way - leaving an incognito window open with several websites logged in for up to months; never a problem. I've only seen this in UG.

**Comment by PF4Public** [comment]
Well, I couldn't reproduce it. I have a tab open since yesterday. Still logged-in.

**Comment by dm17** [comment]
> Well, I couldn't reproduce it. I have a tab open since yesterday. Still logged-in.

A tab in an incognito window, right?

**Comment by PF4Public** [comment]
Try killing the tab from Chromium process explorer and let us know if it will be logged-out. :)

**Comment by dm17** [comment]
> Try killing the tab from Chromium process explorer and let us know if it will be logged-out. :)

Sorry for the delay. Tried that and it isn't the same behavior at all. It just shows the "aw snap" tab crash page, but when reloading it is not logged out. Perhaps it is a memory management think in flatpak? Will look into that next. (Yes I realize this almost certainly isn't UG-specific bug at this point, but would like to leave this open until I can post more info for others to stumble upon in the future. Feel free to close it so long as I can still post that here.)

**Comment by PF4Public** [comment]
It will be closed automatically upon inactivity.

**Comment by mehmetkursataydin** [comment]
> > Could you name specific sites this happens with?
> 
> Any site so far that has a login. I've tested Stripe, Gmail, and a few others. They all logout at the same time as if cookies were automatically cleared. I haven't timed it yet exactly, but definitely less than 12h idle it happens.

this is exactly what I am having and I was wondering if it is a problem with me somehow, thanks god finally someone else confirmed it
