### ISSUE TITLE
extensions not installed

### ISSUE THREAD

**Issue by ruboard** [ungoogled-software/ungoogled-chromium#1998]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

103.0.5060.53

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

extensions not installed

### How to Reproduce?

Handling of extension MIME type requests    always
boomarklet from here https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#downloading-the-crx-file

### Actual behaviour

https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=103.0.5060.53&x=id%3Daapbdbdomjkkjkaonfhkkikfgjllcleb%26installsource%3Dondemand%26uc

site clients2.google.com does not allow a connection to be established.
Try doing the following:

Check your Internet connection.
[Check your proxy and firewall settings](chrome-error://chromewebdata/#buttons).
ERR_CONNECTION_REFUSED

### Expected behaviour

.

**Comment by networkException** [comment]
I doubt this is an issue on our side, please test that you can access that url using a different browser / curl
