### ISSUE TITLE
WEBGL_debug_renderer_info extension is broken

### ISSUE THREAD

**Issue by HMaker** [ungoogled-software/ungoogled-chromium#1999]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

102.0.5005.61

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

WEBGL_debug_renderer_info extension is broken 

### How to Reproduce?

1. Navigate to https://webglreport.com/?v=2

### Actual behaviour

"Unmasked Vendor" and "Unmasked Renderer" is missing.

### Expected behaviour

"Unmasked Vendor" and "Unmasked Renderer" should be present.

### Additional context

The WEBGL_debug_renderer_info is supported but the values for unmasked renderer and vendor are probably null.

**Comment by HMaker** [comment]
Also to reproduce execute following JS on devtools console:
```js
var canvas = document.createElement('canvas');
var gl = canvas.getContext('webgl');

var debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
var vendor = gl.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL);
var renderer = gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL);

console.log(`Unmasked Vendor: "${vendor}"`);
console.log(`Unmasked Renderer: "${renderer}"`);
```
on ungoogled-chromium both strings are empty.

**Comment by networkException** [comment]
> Shouldn't this be optional and enabled through a command line switch?

probably, also it might be better to just return `null` from `gl.getExtension('WEBGL_debug_renderer_info')` to mimic Firefox with `privacy.resistFingerprinting` set to `true`

**Comment by PF4Public** [comment]
@Ahrotahn Should we change anything here?

**Comment by Ahrotahn** [comment]
I'd be interested to know what impact not having "Unmasked Vendor" and "Unmasked Renderer" causes.  I'm not against having it behind a flag if there's a reason for it.  Changing the value to null should be fine, I'll experiment with that later on.
