### ISSUE TITLE
AppImage - Ungoogled Chromium 103.0.5060.53-1 - 'GLIBC_X.XX' not found

### ISSUE THREAD

**Issue by armaccloud** [ungoogled-software/ungoogled-chromium#2001]
The latest versions of UnGoogled Chromium (AppImage) do not function for me anymore.
When opening from the terminal, I get the following errors.

```
/home/***username***/Applications/ungoogled-chromium_103.0.5060.53-1.1_76687ed297caff5c98a005d7c2ab6249.AppImage %U
/tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome)
/tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome)
/tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome)
/tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ungoogWXoCob/opt/google/chrome/chrome)

```

Operating System: 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
Package Type: AppImage
Version: 103.0.5060.53-1.1
Latest working version: 102.0.5005.61

**Comment by networkException** [comment]
CC @clickot

**Comment by clickot** [comment]
@armaccloud could you please try if the linux_portable package version instead of the appimage version works for you?

**Comment by clickot** [comment]
@armaccloud I tried it on myself using a debian bullseye live cd image, same error with the linux_portable package. I will change my build using an debian based builder docker image ( i switched to ubuntu:jammy two releases ago), maybe I made a mistake there.

**Comment by armaccloud** [comment]
> @armaccloud I tried it on myself using a debian bullseye live cd image, same error with the linux_portable package. I will change my build using an debian based builder docker image ( i switched to ubuntu:jammy two releases ago), maybe I made a mistake there.

Thank you for looking into this. I will wait for the next release to come out.

**Comment by clickot** [comment]
@armaccloud I rebuilt 103.0.5060.53-1.1 using a debian builder image, and got an appimage that works both on ubuntu and debian and re-released it. You already may download it at https://github.com/clickot/ungoogled-chromium-binaries/releases/tag/103.0.5060.53-1 and try it out. When the PR above is merged it will be also available on the download site.

**Comment by clickot** [comment]
@armaccloud could you please check if the re-released version 103.0.5060.53-1.1 works also for you? and if, could you please close this issue? Thanks :-)

**Comment by armaccloud** [comment]
@clickot I've installed the latest version and can confirm that it works.
Many thanks for solving this so quickly, I appreciate very much!

**Comment by gollum-z** [comment]
The same problem occurs again with version `114.0.5735.106-1.1`.
I also tried the linux_portable package version instead with the same issue.

Kernel: `5.15.0-75-generic x86_64`
Desktop: `Gnome 3.36.9`
Distro: `Ubuntu 20.04.6 LTS (Focal Fossa)`
Latest working version: `113.0.5672.63-1.1`

**Comment by gollum-z** [comment]
@clickot : the same issue with [https://github.com/clickot/ungoogled-chromium-binaries/releases/tag/114.0.5735.133-1](url)

**Comment by clickot** [comment]
@gollum-z : I had some problems to get the build running and struggled with compile errors since 114.xx . One thing I did was to switch to the brand new debian bookworm release for the docker image i build with (which uses a newer glibc version). Maybe this is the reason for the error. I try if i get things compiled with debian:bullseye that i used before 114.xx. but i'm not sure if some compile errors might reappear. we will see....

**Comment by gollum-z** [comment]
@clickot :+1:  Thank you for the reply.

From my (a user’s) point of view: do I understand it right: should not all required libraries be contained in the AppImage? So it would be able to run regardless the system on which it is started? 

For now I use the Flatpak version (there was another issue with `xdg-desktop-portal` (see [https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal/+bug/1951685](url)); after I upgraded `xdg-desktop-portal` everything runs fine.)

**Comment by clickot** [comment]
@gollum-z that's what i also thought, but there seems to exist exemptions. I do not really understand why this happens, so i try to get "around" it. There are some people who think appimage is somehow broken at all, but i can't really tell.
BTW: ever thought of upgrading to ubuntu 22.04, the latest LTS?

**Comment by gollum-z** [comment]
@clickot Might be I was too optimistic concerning the concept of AppImage at all. Thus I have the "backup solution" of Flatpak, even if there is also some trouble (as I decribed above).

As for the upgrade to next ubuntu LTS: I really do not like the idea of having such essential software as a browser (i.e. Mozilla Firefox) as a snap only. From the three concepts of "isolated/portable/whatever" software I like snap the least. Even a small piece of software as snap starts very much slower on my machine than a "native" installed as .deb or even as Flatpak/AppImage.
I am using UngoogledChromium for tests and occasionally for YouTube videos only.

**Comment by rany2** [comment]
@gollum-z Just FYI this issue also occurs if you are trying the 32-bit version of Ungoogled Chromium on a 64-bit machine while not having the 32-bit glibc libraries installed.

**Comment by rany2** [comment]
Anyway using the Flatpak is probably a safer bet, it doesn't have any dependency on your host libraries. It uses the glibc provided by the runtime, so it works on any Linux including musl-based distros.

**Comment by gollum-z** [comment]
It was just that until the version `113.0.5672.63-1.1` the browser worked as expected. I like the idea of AppImage because one does not need to install anything (as opposed to Flatpak) and the program just runs (or does not in this very case).

Thank you both @clickot @rany2  for the explanations!

**Comment by clickot** [comment]
@gollum-z : unfortunately my build failed with the bullseye image with a compile error and i don't think i get this fixed. At least  i checked that my appimage works on 22.04. Here are instructions how to install firefox as deb package if that is the  thing that keeps from upgrading to 22.04: 
https://askubuntu.com/questions/1399383/how-to-install-firefox-as-a-traditional-deb-package-without-snap-in-ubuntu-22/
I don't use snaps at all on my ubuntu installations and actually deinstalled snapd. I don't miss anything... ;-)

**Comment by armaccloud** [comment]
Hi @clickot Sorry to hear that things are not running well with the Bullseye version, I noticed not being able to run my Chromium anymore after upgrading.

Just to get some clarity and maybe advice if you could.

I am in the process of upgrading my Debian to Bookworm; will I be able to run the appimage there?
The reference to Firefox PPA I don't understand; is there a PPA for Ungoogled-Chromium? Why are you referencing Firefox?
What is the best option for my setup to keep to an as light (and secure) install base as possible with Bookworm; appimage / PPA / Flatpak?

**Comment by clickot** [comment]
Hi @armaccloud 
* you will be able to run the ungoogled chromium appimage on bookworm
* I mentioned the ppa for firefox to @gollum-z since he stated that the fact there is only a snap for firefox from ubuntu > 20.04 keeps him from upgrading, so that would be a solution for him to upgrade to ubuntu 22.04 (or higher) and use my ungoogled-chroium appimage and a firefox intalled as deb package
* as far as i know there is no PPA for ungoogled-chromium
* i don't know if flatpak is better than appimage, but @rany2 statet above that there is no dep to glibc there so maybe it's "a better bet"

**Comment by a-kriya** [comment]
>as far as i know there is no PPA for ungoogled-chromium

https://software.opensuse.org//download.html?project=home%3Aungoogled_chromium&package=ungoogled-chromium is linked at https://github.com/ungoogled-software/ungoogled-chromium-debian#getting-obs-packages
