### ISSUE TITLE
Dev tool lang

### ISSUE THREAD

**Issue by ruboard** [ungoogled-software/ungoogled-chromium#2003]
Why doesn't the language change in Dev tool? 
https://images4.imagebam.com/8b/9d/69/MEBEQFN_o.jpg

**Comment by PF4Public** [comment]
Have you tried that in vanilla Chromium?

**Comment by ruboard** [comment]
> Have you tried that in vanilla Chromium?

no. I don't even know what it is. 
why should I try it?

**Comment by networkException** [comment]
Vanilla just means unmodified, the normal upstream chromium without any patches applied

**Comment by networkException** [comment]
I would guess that ungoogled-chromium might block requests to google servers which store the translations

**Comment by ruboard** [comment]
it does not depend on servers
screenshot from chrome offline
https://images4.imagebam.com/5e/16/2f/MEBESX2_o.jpg

**Comment by ruboard** [comment]
is it possible to specify the language without connecting to google servers?

**Comment by PF4Public** [comment]
If it merely needs to download a file running vanilla Chromium could solve this issue for a profile :)

Someone needs to investigate this. 🤷

**Comment by ruboard** [comment]
I ran the latest version of chrome, chose the language, it changed. then closed the browser, and turned off the network. the next time you start the language becomes the default. that is, changing the language only works online.
it is logical to suggest that no file is loaded, but some parameters are changed. temporarily.

**Comment by PF4Public** [comment]
If it needs to call G servers for this feature to function one could find a file to exclude the substitution and rebuild the whole thing.

**Comment by ruboard** [comment]
it would not be bad.
but apparently it goes against the philosophy (ungoogled) of the browser?

**Comment by PF4Public** [comment]
@ruboard You're right, it is very unlikely to happen, but if you're building yourself, you may change sources however you want.

**Comment by ruboard** [comment]
I think that a compromise could be adding a flag

**Comment by networkException** [comment]
I don't think so. A flag shouldn't allow the browser to connect to google servers

**Comment by ruboard** [comment]
This is just my theoretical guess.
but still I would like the console to be in their native language. how this will be implemented is up to the developer.

**Comment by PF4Public** [comment]
I think, there's nothing left to discuss, closing this issue.

In case anyone is willing to investigate this issue further, feel free to share your findings.
