### ISSUE TITLE
Create a  package for opensuse

### ISSUE THREAD

**Issue by a61kt** [ungoogled-software/ungoogled-chromium#2009]
### Description

Create RPMs for opensuse

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Could we create RPMs for openSUSE  (tumbleweed)
:unlike fedora they are less dramatic about codecs  as arch

### Possible solutions

create rpms for opensuse tumbleweed

**Comment by mpaunovic** [comment]
Try this:

https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home%3AMister_Magister

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
