### ISSUE TITLE
53 Bank does not work

### ISSUE THREAD

**Issue by AE720** [ungoogled-software/ungoogled-chromium#2010]
### OS/Platform

Windows

### Installed

OS/Platform's package manager

### Version

Version 101.0.4951.54 (Developer Build, ungoogled-chromium) (64-bit)

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [x] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

At 53.com. the login only hangs and does not go any further. No issue with Google Chrome

### How to Reproduce?

Go to 53.com, login with credentials and see the never ending loading animation

### Actual behaviour

I have enabled everything I could in site settings, whitelisted the website for 3rd party cookie access, made sure secure DNS is off.

Here is the output of logs:

![image](https://user-images.githubusercontent.com/63013864/177047093-b41be871-960d-4c1e-9c56-6153d0ef9e43.png)

This is the console logs of Google Chrome, where I am signed in:
![image](https://user-images.githubusercontent.com/63013864/177047112-98de0ed8-cc06-40af-b17a-a36759afeb50.png)

Let me know what else I can provide. If the issue is how Google services are being blocked and letting this through will go against that,

### Expected behaviour

To be logged in

**Comment by PF4Public** [comment]
Have youtried [this](https://github.com/ungoogled-software/ungoogled-chromium/issues/1927#issuecomment-1107675294)?

**Comment by AE720** [comment]
> Have you tried [this](https://github.com/ungoogled-software/ungoogled-chromium/issues/1927#issuecomment-1107675294)?

Thanks for the response. I have tried that. That was the closest reference I could find when searching for the problem before submitting an issue. Even with all cookies allowed, the issue persists.

**Comment by AE720** [comment]
I'm not sure what happened but I decided to try again and it seems to be working now. Thank you for your assistance in the matter.
