### ISSUE TITLE
Can't access website

### ISSUE THREAD

**Issue by zeref-dragneel** [ungoogled-software/ungoogled-chromium#2012]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

103.0.5060.53

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Unable to access Disqus

### How to Reproduce?

disqus.com

### Actual behaviour

Video: https://streamable.com/ke8dwy

### Expected behaviour

Video

**Comment by ianmatt** [comment]
here working fine, same version
try to play with Settings->Privacy and security->Security->Secure DNS... maybe the one you're using now resolves the site to a server where your country is banned?

**Comment by zeref-dragneel** [comment]
Do you have a video tutorial?

**Comment by Request-timed-out** [comment]
here working fine, same version.
i think it's more about network and dns problem, not the appilication itself
