### ISSUE TITLE
Hardware Acceleration not being enabled.

### ISSUE THREAD

**Issue by jason88fr** [ungoogled-software/ungoogled-chromium#2024]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

Version 103.0.5060.134 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Issues with getting Hardware Acceleration

### How to Reproduce?

When going to chrome://gpu/ I notice that Hardware Acceleration is not enabled.

### Actual behaviour

I have installed the right drivers for my system and tried a plethora of command lines and flags one by one but to no avail.

### Expected behaviour

Hardware Acceleration enabled.

**Comment by jason88fr** [comment]
I was able to solve most of the issues I saw except "video_encode".

I don't have screenshots of what things were like before but I will add my current configuration to show what worked for me.

This has to be renamed to chromium-flags.conf and placed in "~/.config/"
I used the Kate editor.
[chromium-flags.txt](https://github.com/ungoogled-software/ungoogled-chromium/files/9181008/chromium-flags.txt)

These are the flags I enabled within ungoogled-chromium.
[ungoogle-chromium-Experiments.pdf](https://github.com/ungoogled-software/ungoogled-chromium/files/9181021/ungoogle-chromium-Experiments.pdf)

This was my end result.
[ungoogle-chromium-gpu.pdf](https://github.com/ungoogled-software/ungoogled-chromium/files/9181026/ungoogle-chromium-gpu.pdf)


If anyone has an idea on how to get hardware encode working that will be nice but I don't think I need it for Stadia, Twitch, Netflix, Youtube, which are all I use on this, for everything else, there's LibreWolf.

**Comment by jstkdng** [comment]
which GPU are you using?

**Comment by jason88fr** [comment]
> which GPU are you using?

I believe it was Intel GMA on an old HP Elitebook 2540p or Intel HD Graphics 520 on a Microsoft Surface Pro 4.

I've since moved on to Firefox Developer Edition.

**Comment by diligentlystereotypedinvestment** [comment]
Sorry to revive an old bug, but I also experienced this issue. What information can I provide to help debug this?
