### ISSUE TITLE
Is there a version for RPi4?

### ISSUE THREAD

**Issue by LunaDoll** [ungoogled-software/ungoogled-chromium#2025]
Hi,

I happily use this on Windows: https://portapps.io/app/ungoogled-chromium-portable/

But I can't find a simple method for me to use ungoogled-chromium on my RPi4 (Raspberry Pi 4 Model B)

can someone advise me please?

**Comment by tomasz1986** [comment]
I haven't tested it myself, but the Flatpak release seems to be available for aarch64.

**Comment by LunaDoll** [comment]
can your write a command or a link, I'm a noob in this :-p

**Comment by tomasz1986** [comment]
You need to install Flatpak first (see https://flatpak.org/setup), and then you will be able to install Ungoogled Chromium with it too (see https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium).

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
