### ISSUE TITLE
Cookies saving but not being logged in

### ISSUE THREAD

**Issue by SomeHybrid** [ungoogled-software/ungoogled-chromium#2035]
### OS/Platform

macOS

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

Version 104.0.5112.81 (Official Build, ungoogled-chromium) (x86_64)

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Cookies being saved but not logging into service

### How to Reproduce?

1. Login to a website
2. Exit ungoogled chromium
3. Open ungoogled chromium
4. Go back to the website

### Actual behaviour

Although clearing cookies and site data when closing all windows is off, you still get logged out. Checking chrome://settings/siteData reveals that the cookies are still stored.

### Expected behaviour

The expected behavior would be that you would still be logged in on restart.

### Additional context

Used homebrew to install ungoogled chromium

**Comment by networkException** [comment]
Can you provide a specific website on which this occurs on?
