### ISSUE TITLE
Wayland support out of the box

### ISSUE THREAD

**Issue by marshallishere** [ungoogled-software/ungoogled-chromium#2041]
### Description

Idea for a better wayland compatibility without needing to change anything

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

By default, #ozone-platform-hint uses the Default option which makes it use X11.

### Possible solutions

Use the option Auto by default, it detects if Wayland can be used, otherwise uses X11.

**Comment by PF4Public** [comment]
I think, this should be directed to the corresponding platform repository as Gentoo for example already supports running on Wayland, as does Arch, I suppose.

**Comment by jstkdng** [comment]
I guess OP wants the flag `--ozone-platform-hint` to default to `auto` so wayland works oob.

**Comment by marshallishere** [comment]
> I guess OP wants the flag `--ozone-platform-hint` to default to `auto` so wayland works oob.

Exactly, this would make the use of wayland automatically.

**Comment by PF4Public** [comment]
Still, I think this should be addressed in a specific manner.

**Comment by marshallishere** [comment]
Ok, thanks!
