### ISSUE TITLE
How to Install Extensions using registry path in Ungoogled Chromium

### ISSUE THREAD

**Issue by nirazv** [ungoogled-software/ungoogled-chromium#2045]
### Discussed in https://github.com/ungoogled-software/ungoogled-chromium/discussions/2044

<div type='discussions-op-text'>

<sup>Originally posted by **nirazv** August  7, 2022</sup>
In google chrome or in edge browser we can install extensions from out side of browsers using registry path for example:

In "**sample.reg**" file for chrome
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Edge\Extensions\jkhapebnlgocjncbbfccgiepjlghehmj]
"path"="C:\\Users\\nirazv\\Desktop\\extension_file_name.crx"
"version"="3.14.0.0"

`

How we can install the same for Chromium? 

How to get the path?</div>

**Comment by PF4Public** [comment]
Why duplicating?

**Comment by nirazv** [comment]
> Why duplicating?

Because there was no reply on that Q&A post so I thought to shift it on issues.

**Comment by nirazv** [comment]
> Why duplicating?

Still no reply? Could you help me please.

**Comment by tomasz1986** [comment]
This is extremely niche, so my guess is that no-one has probably even tried to use this method. You'd likely need to do your research. The basic instructions seem to be available at https://developer.chrome.com/docs/extensions/mv3/external_extensions/#registry.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
