### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by 01iverrozario** [ungoogled-software/ungoogled-chromium#2047]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

104.0.5112.81

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

ungoogled chromium crashes

### How to Reproduce?

run chrome.exe
*crashes*

### Actual behaviour

No answer

### Expected behaviour

No answer

**Comment by networkException** [comment]
you mean the installer?
