### ISSUE TITLE
Godaddy Login "Your browser is a bit unusual..."

### ISSUE THREAD

**Issue by nirazv** [ungoogled-software/ungoogled-chromium#2053]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

104.0.5112.81 (Official Build, ungoogled-chromium) (64-bit) 

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Godaddy Login Not working It says "Your browser is a bit unusual..." Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

### How to Reproduce?

Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

### Actual behaviour

Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

### Expected behaviour

Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

### Relevant log output

```sh
Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.
```

### Additional context

Try disabling ad blockers and other extensions, enabling javascript, or using a different web browser.

**Comment by networkException** [comment]
Any errors in the JavaScript console?

**Comment by nirazv** [comment]
I posted it wrong. It was the problem of proxy. Please delete this issue.
