### ISSUE TITLE
No Option to add Custom Search Engine

### ISSUE THREAD

**Issue by blinkor** [ungoogled-software/ungoogled-chromium#2054]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

103.0.5060.134

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [x] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

There is no option to add a custom search engine.

### How to Reproduce?

1. GoTo chrome://settings/searchEngines
2. Look at the search engines list.

### Actual behaviour

There is no button to add a search engine. If you try to edit an existing search engine, it is impossible to change the %s and suggestion fields.

### Expected behaviour

There to be a button to add a custom search engine. I am trying to add google as a search engine.
![image](https://user-images.githubusercontent.com/66094636/185675219-c89678b3-2790-4ff6-a4cd-c3f8dde5fe46.png)

### Additional context

I can delete an existing search engine, but I **cannot edit or add** a new one.
![image](https://user-images.githubusercontent.com/66094636/185675398-7608a268-d829-4a0c-a809-8016ba6a8962.png)

**Comment by tomasz1986** [comment]
It seems the layout has changed in the last version. You can still add custom search engines by clicking the "Add" button next to "Site search". It's even visible in the screenshot in the background.

**Comment by blinkor** [comment]
I fixed it by adding it to site search, then selecting the site search as **default**. This moves the site search up to the search engines incase anyone else needs to know.
