### ISSUE TITLE
Occasional graphical artifacts and/or blank screen only on "google.com"

### ISSUE THREAD

**Issue by tomasz1986** [ungoogled-software/ungoogled-chromium#2057]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 104.0.5112.102 (Official Build, ungoogled-chromium)

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Occasionally, searching on Google results in graphical artifacts and/or blank screen displayed instead of the actual content.

### How to Reproduce?

I can't reproduce this at will. I use Google as my default search engine. Normally, when I search for something using the address bar, the Google website loads up and displays the content with no problems. However, from time to time, the search results come up either unreadable and crumbled with graphical artifacts, or the content is almost completely blank.

### Actual behaviour

This is what the site looks like when the problem happens.

![image](https://user-images.githubusercontent.com/5626656/185786559-09407ccc-b650-49bc-83c5-ff204b19fef8.png)

### Expected behaviour

The Google website with the search results should be displayed normally.

### Additional context

I've encountered this problem on at least two completely different devices. The only similarity is that they run Windows 10. Otherwise, the hardware has nothing in common — one is a tablet with Intel CPU and GPU, the other a desktop with AMD CPU and GPU, which is why I don't really suspect a GPU failure here.

I believe this started sometime after Ungoogled Chromium v100, so it wasn't that long ago. In the past, I  don't remember having this kind of a problem. I'm curious whether I'm the only one to experience the issue. Also, what's peculiar is that it seems to only affect "google.com" and no other websites.

**Comment by PF4Public** [comment]
Have you tried the same in a new empty profile?

**Comment by tomasz1986** [comment]
It's difficult to reproduce at will, unfortunately. It just seems to happen randomly, so even if I do create a clean profile and have no problems there, there's no guarantee that the culprit was something specific to the other profile, or rather I was just lucky.

The profiles on the two devices, where I've encountered the problem, are completely separate though.

I will try to do more testing nonetheless. I was just curious whether I was the only one affected by this, or maybe someone else's experienced this problem too.

**Comment by PF4Public** [comment]
I remember having a blank page very-very rarely on Linux at some point, don't know if it is related to your issue, but it was likewise totally random. For me it got gradually better. And I already do not remember when was the last time that I got an empty screen instead of a webpage. I never had artifacts in browser though. 🤷

I would suggest trying Chromium and see if you could reproduce it there.

**Comment by PF4Public** [comment]
@tomasz1986 I think by now you can guess what my question would be? :)

**Comment by PF4Public** [comment]
@tomasz1986 Maybe this is your issue or at least related to yours: https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

Try the workaround from there.

**Comment by tomasz1986** [comment]
Thank you for the investigation! The issue and the screenshots do indeed look very similar to what I've been experiencing. I must say though that it's been happening very rarely in the recent times.

I'm now going to try running the browser with the `--disable-gpu-driver-bug-workarounds` flag and see whether there is any difference.
