### ISSUE TITLE
Chromium reopens after closing it down

### ISSUE THREAD

**Issue by Euro3000** [ungoogled-software/ungoogled-chromium#2058]
### OS/Platform

macOS

### Installed

Compiled from source

### Version

Version 101.0.4951.41 (Official Build, ungoogled-chromium) (arm64)

### Tested upstream?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

If Chromium closed, it reopens instantly

### How to Reproduce?

Open Chromium
Close Chromium
It reopens by itself.
Need to "forcefully" shut it down via activity monitor (taskmanager)

### Actual behaviour

Open Chromium. (Surf a bit)
Close Chromium via short cut or in menu.
It reopens by itself almost instantly.

### Expected behaviour

If I close the App, it shouldn't reopen itself :)

**Comment by PF4Public** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-macos stopped at v88. Did you use any of the forks?
