### ISSUE TITLE
Clear data on exit: Add option to exclude passwords

### ISSUE THREAD

**Issue by kangarko** [ungoogled-software/ungoogled-chromium#2064]
https://github.com/ungoogled-software/ungoogled-chromium/blob/4a84c3eb4925fbd41f1ca48be5a09f9c2133d021/patches/extra/ungoogled-chromium/add-flag-to-clear-data-on-exit.patch#L26

I'm happy with the password manager in Chromium but I'd only like to clear other data while not removing passwords on each exit. Would be it possible to add a dropdown to the flag above selecting: "Remove All Data" / "Remove All Except Passwords" instead of a simple "Enabled/Disabled" toggle?

Thanks so much!

**Comment by PF4Public** [comment]
Similar to #1923
