### ISSUE TITLE
Custom Background Picture for Default NTP

### ISSUE THREAD

**Issue by mezhgano** [ungoogled-software/ungoogled-chromium#2081]
### Description

Let users define custom background picture for the default "chrome://newtab/" page

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Lack of possibility to choose user custom background picture for the default new tab page

### Possible solutions

Let user choose custom background picture in way as official Google Chrome do (pen button in right bottom corner of a new tab page):
![Screenshot 2022-09-07 16-09-43](https://user-images.githubusercontent.com/8752899/188886545-a40da880-e516-4d20-ab79-5617493c9c7d.png)

![Screenshot 2022-09-07 16-09-57 New_Tab_-_Google_Chrome](https://user-images.githubusercontent.com/8752899/188886592-24bedf47-7176-4634-8643-049bb1182ee0.png)

or via "Appearance" section of settings page

### Alternatives

Less user-oriented, but more simple solution is add a custom flag, for example **"Custom New Tab Page Background"**, when set to enabled chromium uses any picture named **ntp_background.png** in installation folder as background picture for new tab

### Additional context

I know it is possible to use "Custom New Tab Page" flag and set my own url or local html file as new tab template, but then i will loose "most visited websites" icons, so there is no way to keep these icons and set custom background picture, please correct me if i wrong

**Comment by PF4Public** [comment]
Please try using chrome://new-tab-page/ via [--custom-ntp](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.) or chrome://flags/#custom-ntp
