### ISSUE TITLE
Spell check is not functioning on many websites

### ISSUE THREAD

**Issue by amsamam** [ungoogled-software/ungoogled-chromium#2083]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

105.0.5195.102

### Description

Spell check is not functioning on many websites. Spell check works on these websites with regular chromium and firefox.

### How to Reproduce?

1. Open pastebin as an example.
2. Incorrectly spell something
3. Notice how spell check doesn't underline it while it does in Firefox

### Actual behaviour

Spell check doesn't always kick in

### Expected behaviour

Spell check to function

**Comment by PF4Public** [comment]
Please [do a search first](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+spell).

**Comment by amsamam** [comment]
> Please [do a search first](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+spell).

The en-US 9.0 bdic file the flatpak came with doesn't work correctly with the latest chromium version. 10.1 does work so that should be included instead. I should've included that in my post sorry I've been drinking all day.

**Comment by PF4Public** [comment]
Yep, that would've been essential information. Nonetheless, you might have better luck if filing this issue at flatpak since this repository does not provide dictionaries in any way.
