### ISSUE TITLE
Whats the difference between Iridium browser and ungoogled-chromium?

### ISSUE THREAD

**Issue by Raj2032** [ungoogled-software/ungoogled-chromium#2089]
Hey guys I am trying to find the difference between the ungoogled-chromium and iridum browser but not too sure what the differences are?

**Comment by better319** [comment]
Iridium browser cannot stop the Extension

**Comment by whyredow** [comment]
As i can see, Iridium is not updated as frequently as ungoogled-chromium. FYI, ungoogled-chromium is currently based on 106 version of Chromium.
![image](https://user-images.githubusercontent.com/102296008/194815553-3d45ccae-3acc-4ae4-8cbd-9258df6fadcf.png)

**Comment by Raj2032** [comment]
I see, well thanks mate :)

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
