### ISSUE TITLE
question and help to open external link in same profile of browser is open

### ISSUE THREAD

**Issue by jacob755** [ungoogled-software/ungoogled-chromium#2090]
hello
i open browser with  .bat file with custom switch and flag
and its default browser
now if i open html file or click link in another program it open another instance
which is not logined in site no extension....
how can i force to open this html/link in instance of ug that run with .bat file?

thanks

**Comment by Nifury** [comment]
You can give [chrlauncher](https://github.com/henrypp/chrlauncher) a try. It can register itself as the default browser and append your custom commanline.

**Comment by jacob755** [comment]
> You can give [chrlauncher](https://github.com/henrypp/chrlauncher) a try. It can register itself as the default browser and append your custom commanline.

thank you this work almost.
its open new window extension is there boomark cookie all there
but it wont work if there is a lot switch and command when click link and or open html file it just open window
i thought there is problem with switch and command i removed many but did not help
example instead of open
https://github.com/ungoogled-software/ungoogled-chromium/issues/2090
it open https://github.co
i think there is problem with windows that short command.

many appreciated for help anyway.

**Comment by jacob755** [comment]
its seems reported 
already
https://github.com/henrypp/chrlauncher/issues/203
https://github.com/henrypp/chrlauncher/issues/215
