### ISSUE TITLE
Unable to login to vk.com

### ISSUE THREAD

**Issue by Flashwalker** [ungoogled-software/ungoogled-chromium#2092]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

105.0.5195.125

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Unable to login on vk.com

### How to Reproduce?

1. use clean profile
2. allow all cookies in settings
3. go to vk.com
4. try to login
5. see error: 
![Clipboard_1](https://user-images.githubusercontent.com/2188215/191288002-16896aae-1301-4414-8170-da6dfc484da0.jpg)

### Actual behaviour

got login error

### Expected behaviour

login success

### Additional context

Tried on fresh new profile `ungoogled-chromium-flatpak --user-data-dir=/tmp/tmp-data-dir`, got the same issue;  
Login to vk.com works on ungoogled-chromium v.98 .deb package;  
Login to vk.com works on vanila chromium appimage;

**Comment by networkException** [comment]
Are there any error messages in the console?

**Comment by Flashwalker** [comment]
It looks like `--user-data-dir` option was passed two times, for the old and new folders.  
imho the last one should have override the first one, but it seemed to work somehow both of them

**Comment by Flashwalker** [comment]
I found that option: `--disable-web-security` cause this issue
