### ISSUE TITLE
Not able to put in a custom DOH address

### ISSUE THREAD

**Issue by haptizum** [ungoogled-software/ungoogled-chromium#2093]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

105.0.5195.125

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Issue Adding A Custom DOH Service Provider

### How to Reproduce?

Naviagte to: Privacy and Security => Security Advanced => Use secure DNS => With Custom

Copy or manually add a custom DOH service provider

### Actual behaviour

Tried to add Quad9 to Chromium and I am getting an error.

When I use https://dns.quad9.net/dns-query I get the error message, "**Please verify that this is a valid provider or try again later**".

This is also happens with other DOH service providers like BlahDNS and UncensoredDNS.

### Expected behaviour

After adding a DOH servcie provider I should be able to hit enter for Chromium to accept it.

**Comment by networkException** [comment]
I'm pretty sure this is just an UI problem, from what I can tell it makes requests to the DOH server just fine

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by networkException** [comment]
Yes it uses the DOH server just fine but still complains in UI

**Comment by John4266** [comment]
Happens to me too. Getting this error but the DNS still works.
![image](https://user-images.githubusercontent.com/70203256/220228816-38ac87ee-e7a4-4bca-a6b2-ac80f4cc347f.png)
Version 110.0.5481.100 (Official Build, ungoogled-chromium) (64-bit)

**Comment by pferreir** [comment]
Same here.

**Comment by m0x61h0x64i** [comment]
I have same issue, any updates?

**Comment by stnert** [comment]
And until when will we continue without a correction?

**Comment by networkException** [comment]
Until someone is willing to implement a fix (again, to my knowledge this is purely visual).

**Comment by JohnnyMysterious** [comment]
As of 12/04/2024 the UI error still exists but it has successfully been connected to my private dns server and I can see the logs. So it's not a big issue but still would be good if it gets fixed.

**Comment by t0ma5** [comment]
As of 19/07/2024 the UI error still exists

**Comment by KitsuneNoBaka** [comment]
139.0.7258.66 and error is still here

![Image](https://github.com/user-attachments/assets/3f877b3a-f436-45e3-8771-e6392388faa1)

**Comment by dumbmoron** [comment]
> 139.0.7258.66 and error is still here

@KitsuneNoBaka have you tried doing what the error message says? it works for me

**Comment by tomasz1986** [comment]
Have you tried removing the final `/` slash?

**Comment by KitsuneNoBaka** [comment]
> > 139.0.7258.66 and error is still here
> 
> [@KitsuneNoBaka](https://github.com/KitsuneNoBaka) have you tried doing what the error message says? it works for me

How?

**Comment by KitsuneNoBaka** [comment]
> Have you tried removing the final `/` slash?

No change

**Comment by dumbmoron** [comment]
> > > 139.0.7258.66 and error is still here
> > 
> > 
> > [@KitsuneNoBaka](https://github.com/KitsuneNoBaka) have you tried doing what the error message says? it works for me
> 
> How?

<img width="613" height="233" alt="Image" src="https://github.com/user-attachments/assets/9e2b643c-5090-4d31-b8b5-2bf64ede741e" />

<img width="854" height="464" alt="Image" src="https://github.com/user-attachments/assets/613a9a18-e35f-4635-bd74-1064926507ef" />

**Comment by KitsuneNoBaka** [comment]
OK. Somehow I've had typo in address
