### ISSUE TITLE
Segmentation Fault on closing video/music control menu 

### ISSUE THREAD

**Issue by rubynt** [ungoogled-software/ungoogled-chromium#2094]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

Version 103.0.5060.53 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

On the sound control menu if you click it then try to exit it, the browser seg faults.

### How to Reproduce?

1. Start a audio source or video
2. Click the "Control for video, music, and more" menu
3. Try to exit it

### Actual behaviour

Segfault

### Expected behaviour

It just exits the menu

### Additional context

I use void linux with the dainra repo
https://github.com/DAINRA/ungoogled-chromium-void

**Comment by DAINRA** [comment]
I do mention it in the new [readme](https://github.com/DAINRA/ungoogled-chromium-void/blob/DAINRA-patch-1/README.md#general-tweaks), but it doesn't have anything to do with ungoogled-chromium, I can reproduce it even on void's regular chromium package.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
