### ISSUE TITLE
After updating from Win64 build 102.0.5005.61-1 to current latest (106.0.5249.91-1), several sites do not load or become unresponsive

### ISSUE THREAD

**Issue by account123123123** [ungoogled-software/ungoogled-chromium#2110]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

106.0.5249.91-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Twitter.com, mail.tutanota.com, Ebay.com (among others likely) don't load

### How to Reproduce?

1. Ensure version is 106.0.5249.91-1 on Windows 64 bit
2. Try going to Twitter.com 

### Actual behaviour

The Twitter loading screen shows, but never goes past that. Ebay.com loads, but the site can't be interacted with.

### Expected behaviour

The sites should load quick (depending on connection speed) and be functional.

### Relevant log output

```sh
DevTools failed to load source map: Could not load content for https://ton.local.twitter.com/responsive-web-internal/sourcemaps/client-web/vendor.77b95e49.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://ton.local.twitter.com/responsive-web-internal/sourcemaps/client-web/i18n/en.47e42a79.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://ton.local.twitter.com/responsive-web-internal/sourcemaps/client-web/main.f36e2959.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://ton.local.twitter.com/responsive-web-internal/sourcemaps/client-web/ondemand.Dropdown.b3b06289.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
twitter.com/:1 The resource https://abs.twimg.com/responsive-web/client-web/feature-switch-manifest.1361a819.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

### Additional context

The log output pasted is in yellow and am not sure why it says name_not_resolved, as I have adblocker off and no modified hosts file.

**Comment by Nifury** [comment]
It might have something to do with secure DNS (chrome://settings/security). 
Disabling it or using a provided one (such as Cloudflare) might help.
