### ISSUE TITLE
question how use this flag --netifs-to-ignore

### ISSUE THREAD

**Issue by jacob755** [ungoogled-software/ungoogled-chromium#2120]
hello anybody know how use this flag **--netifs-to-ignore**
--netifs-to-ignore===>List of network interfaces to ignore. Ignored interfaces will not be used for network connectivity.
i used bellow  but still when check  ip it connected to vpn interface

--netifs-to-ignore="OpenVPN TAP-Windows6"
edit:i know about ForceBindIP but if above work its much better
thankyou

**Comment by varunseth5788** [comment]
In this question there is syntax error it should be like this
--netifs-to-ignore "OpenVPN TAP-Windows6"

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
