### ISSUE TITLE
Extra space on header when in Full Screen

### ISSUE THREAD

**Issue by d6o** [ungoogled-software/ungoogled-chromium#2142]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

Version 107.0.5304.88 (Official Build, ungoogled-chromium) (arm64)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Sometimes when I use ungoogled chromium on full screen an extra empty space on the header is added

### How to Reproduce?

1. Open the Browser
2. Click on the green circle on the header

### Actual behaviour

The application goes full screen, but empty space is added to the header.
![image](https://user-images.githubusercontent.com/683170/201112759-e663ba8f-6e8d-4de9-bb18-10006be359a6.png)

### Expected behaviour

The application goes full screen without the empty space added to the header.

### Additional context

- Installed using homebrew
- macOS Monterey 12.6 (Apple M1 pro)
- Sometimes, going out of the full screen and clicking to go full screen again fixes the problem
- It also happened in older versions

**Comment by networkException** [comment]
> [x] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

If that's the case your profile is broken, you could transferring only the data you care about to a new profile.

**Comment by d6o** [comment]
@networkException I also can't reproduce this on my profile. It only occasionally happens. I'll try your suggestion and see if it happens again.

**Comment by PF4Public** [comment]
So, how is it doing?
