### ISSUE TITLE
Search Engines Somehow Getting Removed

### ISSUE THREAD

**Issue by dm17** [ungoogled-software/ungoogled-chromium#2144]
### OS/Platform

Portable Linux

### Installed

Flatpak

### Version

107.0.5304.110

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

google.com disappears after being re-added as an enabled search engine repeatedly

### How to Reproduce?

1) Have a non-google default search engine
2) Go to the search engine list and click activate
3) Use the browser for a while and somehow tab-complete stops working and I see the search engine is not activated in settings

### Actual behaviour

Search engines somehow get de-activated for URL bar tab-complete

### Expected behaviour

Once they're activated in settings, then I don't think they're supposed to be deactivated by anything without our permission - but I could be wrong

### Additional context

I'm guessing this happens for other search engines, but it never seems to have happened with youtube.com for example.

**Comment by PF4Public** [comment]
@rany2 Have you encountered a similar issue?

**Comment by rany2** [comment]
@PF4Public I followed the submitter's steps and I wasn't able to face the issue on the flatpak.

**Comment by PF4Public** [comment]
Thanks for verifying this, @rany2.
