### ISSUE TITLE
Updating to Chromium 108.0.5359.48

### ISSUE THREAD

**Issue by a51kot** [ungoogled-software/ungoogled-chromium#2145]
In https://omahaproxy.appspot.com/ there are 4 chromiums (_107_/108/109/110)
** 107 as abandoned
** 108 swill be stable
** 109 beta
** 110 dev/canary

So  google will  update to chromium 108 in some days

**Comment by SaswatPadhi** [comment]
108 is now Beta.

Source: https://chromereleases.googleblog.com/

**Comment by PF4Public** [comment]
@a51kot How many times have you been asked not to spam issue tracker with something that is not yet released? We have a GitHub workflow for that.
