### ISSUE TITLE
PATCH_BIN env var not mentioned in building docs

### ISSUE THREAD

**Issue by madhattertea** [ungoogled-software/ungoogled-chromium#2149]
Following the build docs I got this error about patch_bin. What value was I supposed to create that env var with?

C:\src\ungoogled>"./utils/patches.py" apply build/src patches
INFO: Applying patches from patches
Traceback (most recent call last):
  File "C:\src\ungoogled\utils\patches.py", line 250, in <module>
    main()
  File "C:\src\ungoogled\utils\patches.py", line 246, in main
    args.callback(args, parser.error)
  File "C:\src\ungoogled\utils\patches.py", line 198, in _apply_callback
    apply_patches(
  File "C:\src\ungoogled\utils\patches.py", line 113, in apply_patches
    patch_bin_path = find_and_check_patch(patch_bin_path=patch_bin_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\ungoogled\utils\patches.py", line 60, in find_and_check_patch
    raise ValueError('Could not find patch from PATCH_BIN env var or "which patch"')
ValueError: Could not find patch from PATCH_BIN env var or "which patch"

**Comment by madhattertea** [comment]
I see I am able to pass a command line arg "--path-bin". Which appears to start the patches, but errors at the start with "returned non-zero exit status 2".


C:\src\ungoogled>"./utils/patches.py" apply "./build/src" "patches" --patch-bin="C:\Users\Administrator\AppData\Local\Programs\Python\Python311\python.exe"
INFO: Applying patches from patches
INFO: * Applying 0001-fix-building-without-safebrowsing.patch (1/98)
Unknown option: -p
usage: C:\Users\Administrator\AppData\Local\Programs\Python\Python311\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
Traceback (most recent call last):
  File "C:\src\ungoogled\utils\patches.py", line 250, in <module>
    main()
  File "C:\src\ungoogled\utils\patches.py", line 246, in main
    args.callback(args, parser.error)
  File "C:\src\ungoogled\utils\patches.py", line 198, in _apply_callback
    apply_patches(
  File "C:\src\ungoogled\utils\patches.py", line 132, in apply_patches
    subprocess.run(cmd, check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-p1', '--ignore-whitespace', '-i', 'C:\\src\\ungoogled\\patches\\core\\inox-patchset\\0001-fix-building-without-safebrowsing.patch', '-d', 'build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 2.

**Comment by PF4Public** [comment]
It seems you need to put a path to an actual `patch` utility in that variable.

**Comment by madhattertea** [comment]
Oh I see, I assumed python did the grunt work here. Something like this: https://gnuwin32.sourceforge.net/packages/patch.htm  ?

**Comment by PF4Public** [comment]
I'm not familiar with the building procedure on Windows, someone else might give you a better advice, but that one might work. Be careful with the binaries you download from internet though.

**Comment by Nifury** [comment]
For Windows build, you'll need to use this repo: https://github.com/ungoogled-software/ungoogled-chromium-windows

**Comment by madhattertea** [comment]
Thank you! I am getting progress now. 

However I'm a bit confused. In the developing docs under "Updating patches". Step 3 uses quilt push command to apply the patches, but then step 5 uses quilt pop to remove the patches. Why remove them? My use case for this browser build must be different. I simply want to apply the patches then do some hand code updates myself and build it.

**Comment by networkException** [comment]
When updating you unapply the patches on the chromium sources so that you have a clean checkout. Otherwise building afterwards wouldn't work as the build script would apply those patches again which fails if they are applied already
