### ISSUE TITLE
mime request isnt appearing

### ISSUE THREAD

**Issue by 3flowin** [ungoogled-software/ungoogled-chromium#2154]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 107.0.5304.107 (Official Build) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

mime request doesnt appear

### How to Reproduce?

go to chrome://flags/
search "mime request"
change "chrome://flags/#extension-mime-request-handling" to "Always prompt for install"

### Actual behaviour

doesnt appear
doesnt work

### Expected behaviour

work

### Additional context

![screenshot](https://user-images.githubusercontent.com/93292345/201499615-4bab3c66-f550-48cb-b3d2-4dafcf3faf2e.png)

**Comment by PF4Public** [comment]
It would be useful to also know which binary did you download.

**Comment by 3flowin** [comment]
> It would be useful to also know which binary did you download because there is no 107.0.5304.107 binary at https://ungoogled-software.github.io/ungoogled-chromium-binaries/
the binary i use was made by Hibbiki

**Comment by PF4Public** [comment]
Then you should file this issue elsewhere. We cannot provide support for third-party binaries.

Try to use a binary from https://ungoogled-software.github.io/ungoogled-chromium-binaries/ instead.
