### ISSUE TITLE
Can't run on freebsd

### ISSUE THREAD

**Issue by rubynt** [ungoogled-software/ungoogled-chromium#2156]
### OS/Platform

Gentoo

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

 107.0.5304.122-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Maybe package conflict?

### How to Reproduce?

start chrome

### Actual behaviour

`ld-elf.so.1: Shared object "libicui18n.so.71" not found, required by "chrome"`

found https://github.com/helloSystem/ISO/issues/396 but ungoogled-chromium didnt install or tried to install mozjpeg, but there are conflicts with jpeg-turbo.

### Expected behaviour

start chrome

### Additional context

I use freebsd but there isnt an option to choose it. I already made an issue [here](https://github.com/tangalbert919/ungoogled-chromium-freebsd/issues/3), but i havent got an answer.

**Comment by networkException** [comment]
FreeBSD builds get uploaded voluntarily, if they weren't linked against the libraries on your system you will have to build it manually.

**Comment by rubynt** [comment]
Okay i fixed it with help from archlinux forum
```
# ln -s /usr/local/lib/libicui18n.so.72.1 /usr/local/lib/libicui18n.so.71
# ln -s /usr/local/lib/libicuuc.so.72.1 /usr/local/lib/libicuuc.so.71
# ln -s /usr/local/lib/libicudata.so.72.1 /usr/local/lib/libicudata.so.71
```
