### ISSUE TITLE
Where is the patch for --disable-encryption and --disable-machine-id?

### ISSUE THREAD

**Issue by madhattertea** [ungoogled-software/ungoogled-chromium#2157]
I looked through every patch and none of them contain the code for setting up those switches. What is controlling/installing those?

**Comment by networkException** [comment]
The patches are part of the windows packaging repository: https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/master/patches/ungoogled-chromium/windows/windows-disable-encryption.patch

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
