### ISSUE TITLE
Include gtk-dark-mode-switch-fix patch

### ISSUE THREAD

**Issue by emansom** [ungoogled-software/ungoogled-chromium#2161]
### Description

Resolve prefer-color-scheme not reflecting GTK dark mode issue

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Currently Chromium [has a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) where it doesn't respect the preferred color scheme of the system.

### Possible solutions

Including [this patch](https://github.com/qcasey/chromium-patches/blob/main/patches/gtk-dark-mode-switch-fix.patch) would resolve this.

### Additional context

My eyes bleed at 4 AM otherwise.

**Comment by PF4Public** [comment]
I doubt this falls within objectives of the project, so one should apply this fix locally when compiling. 

Please also note that the bug you mentioned has a proper fix for this (not the one you linked) and it works flawlessly for me for quite some time: https://github.com/PF4Public/gentoo-overlay/commit/84f77f55a09f6ce0523591d7c300bf9deb2a1c01

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue as there is nothing left to do.
