### ISSUE TITLE
websites are not loading,  some sort of DNS resolve issue. 

### ISSUE THREAD

**Issue by barrywilcox** [ungoogled-software/ungoogled-chromium#2182]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

108.0.5359.95

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

websites are not loading,  some sort of DNS resolve issue. 

### How to Reproduce?

1. search for a site I've not been to before
2.  the page will try to load, fail, refresh once and sometimes load, sometimes wont.

### Actual behaviour

the site does not load,  it auto-refreshes once that I can see, then will usually fail.  looks like a DNS issue with the browser.

### Expected behaviour

the page should load,  it loads fine on chrome and firefox (latest versions) without any of this DNS problems or refreshing of a page.

### Additional context

I'm using Win10 Enterprise LTSC 1809, this is a work systems critical computer that has to use long term branches.

**Comment by AE720** [comment]
It would help if you hit F12 after loading the website and telling us the errors the console is giving you in red.
