### ISSUE TITLE
Disable Chromecast option

### ISSUE THREAD

**Issue by jonholdsworth** [ungoogled-software/ungoogled-chromium#2193]
I can't see this exact request anywhere so I'm filing it.

I find having Chromecast always on is very dangerous. In the old chromium which used the Media Router subsystem it was possible to disable or enable Chromecast via a flag.  This is no longer possible.

Could an option please be added to disable Chromecast.
If there is already a way to do this, could it be pushed to a Wiki somewhere please.
I have searched and have not found any way to do it.

**Comment by PF4Public** [comment]
> I find having Chromecast always on is very dangerous.

[Does it function though?](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+is%3Aopen+cast)
