### ISSUE TITLE
Make Ungoogled Chromium Unmanged

### ISSUE THREAD

**Issue by hellorunner** [ungoogled-software/ungoogled-chromium#2195]
I can't change some settings because the browser is managed?

> This browser is not managed by a company or other organization. Activity on this device may be managed outside of Chromium.

How can I remove this management?

**Comment by networkException** [comment]
What do you mean? The text (which I assume to be the output of `chrome://management/`) explicitly states that the browser is not managed

**Comment by hellorunner** [comment]
Some settings cannot be changed and are labeled "This setting is disabled on managed browsers".

**Comment by jacob755** [comment]
check this registry path if there is an entry
export first then delete
HKEY_CURRENT_USER\Software\Policies\Chromium

**Comment by hellorunner** [comment]
I don't have that entry

**Comment by achtchaern** [comment]
Maybe there's something under HKLM\Software\Policies\Chromium?

**Comment by hellorunner** [comment]
I don't have that entry

**Comment by Makxik** [comment]
Same problem. I can't change these "Use secure DNS" settings (note the description).
![IMG-d600323505b576bf79be2db1f4931321-V](https://user-images.githubusercontent.com/12545047/216226711-137e220a-ddd1-436e-ae7e-d63bb3ad733c.jpg)

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

**Comment by alto4truth** [comment]
The problem is still actual on Linux with 142.0.7444.175 version

**Comment by alto4truth** [comment]
This issue should be reopened TBH

**Comment by PF4Public** [comment]
@alto4truth Please provide more details. Also try reproducing this issue with portable binaries and with a new and empty profile.

**Comment by alto4truth** [comment]
@PF4Public 

I am sorry, I moved off ungoogled-chromium
