### ISSUE TITLE
Remove 'Theme - Open Chrome Web Store' line in Settings

### ISSUE THREAD

**Issue by calhix** [ungoogled-software/ungoogled-chromium#2197]
### Description

Remove 'Theme - Open Chrome Web Store' line in Settings

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Just an OCD thing as I mentioned in #2196. Could we remove this line within the Appearance section since it's useless? I also think it would also be a good idea to think/discuss about updating more of the language used within the Settings menu removing mentions of Google starting with the English language and go from there for other languages. People can submit their own issues/PRs about how to directly translate the changes we would make in English into their language. Also does the option to use Google Translate under Languages do anything? I don't see the ability to translate the page within the context menu when I right-click.

### Possible solutions

Remove line about the Chrome Web Store.

**Comment by Ahrotahn** [comment]
This is already handled by [remove-uneeded-ui.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/108.0.5359.125-1/patches/extra/ungoogled-chromium/remove-uneeded-ui.patch#L9).
Are you using a build that doesn't include that patch?

**Comment by tomasz1986** [comment]
I use the official Windows builds. The link is gone, but the text itself is still present.

![image](https://user-images.githubusercontent.com/5626656/209858844-1fa64fb3-6f73-4597-9aef-2ce9e7786f9e.png)

**Comment by Ahrotahn** [comment]
I took a look into this and it seems only non-linux users are shown that text.   This change *should* remove the text:
```diff
--- a/chrome/browser/resources/settings/appearance_page/appearance_page.ts
+++ b/chrome/browser/resources/settings/appearance_page/appearance_page.ts
@@ -353,8 +353,8 @@
       return;
     }
 
-    let i18nId;
     // <if expr="is_linux">
+    let i18nId;
     switch (this.systemTheme_) {
       case SystemTheme.GTK:
         i18nId = 'gtkTheme';
@@ -366,11 +366,8 @@
         i18nId = 'classicTheme';
         break;
     }
-    // </if>
-    // <if expr="not is_linux">
-    i18nId = 'chooseFromWebStore';
-    // </if>
     this.themeSublabel_ = this.i18n(i18nId);
+    // </if>
   }
 
   /** @return Whether applied theme is set by policy. */
```

I don't have a way to build and test for windows at the moment though, so someone else would have to test that out.

**Comment by calhix** [comment]
Thanks for the help, I think it's also the case for MacOS but I'll have to check when I get back home later today on that as well.

**Comment by PF4Public** [comment]
@Ahrotahn Would it be reasonable to include this into 109 version bump?

**Comment by Ahrotahn** [comment]
It would probably be best to have confirmation that it works first.  I can set up a draft with the change after 109 if no one has tested that out by then.

**Comment by PF4Public** [comment]
Or maybe this belongs to Windows repository… I don't recall us defining guidelines on what goes where…

**Comment by calhix** [comment]
Sorry I didn't post sooner, I think this is the best place since this does affect both Mac and Windows.
