### ISSUE TITLE
Compatibility with GNU FSDG?

### ISSUE THREAD

**Issue by Kreyren** [ungoogled-software/ungoogled-chromium#2201]
This project is a common source of an argument among FOSS developers in relation to the compilance with GNU FSDG (https://www.gnu.org/distros/free-system-distribution-guidelines.en.html) to be kept in the distribution's main repositories, please clarify whether it's compatible ideally in the readme.

Thanks!

**Comment by networkException** [comment]
The guidelines are to be followed by linux distributions, not software projects. We are a software project, as such looking for compliance with the guidelines doesn't make sense generally.

Patches in this repository are licensed under licences regarded as "Free licences, compatible with the GNU GPL" by the fsf however, I think that (besides the obvious commitments like not distributing malware) is the only point we could and do comply with

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
