### ISSUE TITLE
Download fails because of DBus.Error.NoReply

### ISSUE THREAD

**Issue by hoclun-rigsep** [ungoogled-software/ungoogled-chromium#2203]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

Version 103.0.5060.134 (Official Build, ungoogled-chromium) Debian GNU/Linux (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

File download fails because of putative DBus NoReply error

### How to Reproduce?

Download a file, choose location for it.

### Actual behaviour

This is a brand new, upgraded install of Debian 11 with KDE Plasma. Nothing exciting going on. When I download a file, the normal system file dialog appears but when it is submitted nothing happens and the console prints the following:

> [1608:1626:0104/143022.653046:ERROR:select_file_dialog_linux_portal.cc(719)] Portal returned error: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

### Expected behaviour

Naturally the file should be downloaded to the user's chosen destination.

### Relevant log output

```sh
[1608:1626:0104/143022.653046:ERROR:select_file_dialog_linux_portal.cc(719)] Portal returned error: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

### Additional context

Workaround is to uncheck the "Ask where to save each file before downloading" option in `chrome://settings/?search=downlo`

**Comment by PF4Public** [comment]
IIRC there was a bug in Chromium with download manager, but it should be fixed with recent versions. Please try building any more recent version and check again.
