### ISSUE TITLE
Download precompiled binaries files

### ISSUE THREAD

**Issue by Natalia-Oreiro** [ungoogled-software/ungoogled-chromium#2205]
Hi,

I'm sorry for my layman's question, but I used it: https://github.com/portapps/ungoogled-chromium-portable

Unfortunately, this version is very outdated, is there any way to use your awesome edited-browser in the new version and in portable mode (simple ZIP package)?

**Comment by tomasz1986** [comment]
Nothing like that is available out of the box, but you can make your own portable copy simply by extracting the installer and then running `chrome --user-data-dir=<path-to-folder>` from the command line. Of course, this does require a little more technical skills than using a pre-configured archive that can be run with a single click.

**Comment by Natalia-Oreiro** [comment]
> extracting the installer and then running chrome

where does it get the installation version?
I only see source codes: https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/108.0.5359.125-1

**Comment by tomasz1986** [comment]
The Windows installers are available at https://github.com/ungoogled-software/ungoogled-chromium-windows/releases.

**Comment by Natalia-Oreiro** [comment]
thanks

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
