### ISSUE TITLE
Make this be able to run on windows xp

### ISSUE THREAD

**Issue by dawido90183** [ungoogled-software/ungoogled-chromium#2206]
### Description

So hello,i whould like to run this on xp and i saw some people on a website (collab vm) on the xp vm its running ungoogled chromium so could you make this a feature?

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

.

### Possible solutions

.

### Alternatives

.

### Additional context

.

**Comment by networkException** [comment]
I'm strongly against adding support for an operating system like this. Modern security features will not be available making the browser less secure, getting it to run at all will be non trivial and giving people reasons to keep running outdated system in general is a bad idea.

**Comment by PF4Public** [comment]
Cannot agree more with @networkException!

And yes, I do run Windows XP on a daily basis :) a-a-and Windows 7 :)

**Comment by tomasz1986** [comment]
The last version of Chromium for Windows XP was v49 released 7 years ago, so even if someone wanted to support the OS, the task would probably end up being almost impossible anyway.

There are some unofficial kernel extensions for Windows XP that could possibly allow you to run newer browser versions, so I think you could possibly try following this route if you're interested, however the details you will likely need to figure out by yourself.
