### ISSUE TITLE
Unmicrosoftied Edgium

### ISSUE THREAD

**Issue by jansuchomel** [ungoogled-software/ungoogled-chromium#2210]
### Description

Make and similar build of Microsoft Edge

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Edge has several features over Chrome (notably tree style tabs) but I'm as uncomfortable with Microsoft spying as I am with Google spying.

### Possible solutions

It would be nice to make a build of Edge without Microsoft tracking.

**Comment by tomasz1986** [comment]
Not really possible, because Microsoft's modifications are proprietary. In other words, there is no source code to work with.

**Comment by jansuchomel** [comment]
So it's Embrace, extend, and extinguish all over again :( thanks for the info

**Comment by PF4Public** [comment]
> So it's Embrace, extend, and extinguish

I would love to see the show of Microsoft extinguishing Google :)
