### ISSUE TITLE
unable to build ungoogled chromium for portable linux anymore since new 109.0.5414.xx versions

### ISSUE THREAD

**Issue by clickot** [ungoogled-software/ungoogled-chromium#2211]
### OS/Platform

Portable Linux

### Installed

Compiled from source

### Version

109.0.5414.74-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [x] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [x] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [x] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

my build procedure for portable linux fails since the new 109.xxx versions

### How to Reproduce?

execute docker-build.sh in https://github.com/clickot/ungoogled-chromium-build

### Actual behaviour

the ninja build for chrome fails during typescript compilations because of assignments of String to TrustedHtml Type and vica versa

### Expected behaviour

the ninja build procedure completes successfully

### Relevant log output

```sh
[27959/54204] ACTION //ui/webui/resources:library(//build/toolchain/linux/unbundle:default)
FAILED: gen/ui/webui/resources/tsconfig_library.json gen/ui/webui/resources/library.manifest [...many lines]
python3 ../../tools/typescript/ts_library.py --root_dir gen/ui/webui/resources/preprocessed --gen_dir gen/ui/webui/resources --out_dir gen/ui/webui/resources/preprocessed --output_suffix library --in_files [...many lines]
Traceback (most recent call last):
  File "/repo/target/src/out/Default/../../tools/typescript/ts_library.py", line 220, in <module>
    main(sys.argv[1:])
  File "/repo/target/src/out/Default/../../tools/typescript/ts_library.py", line 183, in main
    node.RunNode([
  File "/repo/target/src/third_party/node/node.py", line 34, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '/repo/target/src/third_party/node/node_modules/node-linux-x64/bin/node /repo/target/src/third_party/node/node_modules/typescript/bin/tsc --project gen/ui/webui/resources/tsconfig_library.json' failed
gen/ui/webui/resources/preprocessed/cr_elements/cr_a11y_announcer/cr_a11y_announcer.ts:90:7 - error TS2322: Type 'TrustedHTML' is not assignable to type 'string'.

90       messagesDiv.innerHTML = window.trustedTypes!.emptyHTML;
         ~~~~~~~~~~~~~~~~~~~~~

gen/ui/webui/resources/preprocessed/js/custom_element.ts:26:5 - error TS2322: Type 'string | TrustedHTML' is not assignable to type 'string'.
  Type 'TrustedHTML' is not assignable to type 'string'.

26     template.innerHTML =
       ~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  gen/ui/webui/resources/preprocessed/cr_elements/cr_a11y_announcer/cr_a11y_announcer.ts:90
     1  gen/ui/webui/resources/preprocessed/js/custom_element.ts:2
```

### Additional context

i've been using my build procedure successfully for about a year now, and except of minor adjustements converning the used llvm version and stack and some node installation details that were neccessary over time, it worked fine for me, until the new 109 version. Since i don't have a glue how to fix the issue (i played around with the used node version, without success) i wonder if some of You guys could give me a hint where to look at (as I assume that you of course sucessfully executed builds of the new version, including linux). 

About my build procedure: it is based on the build in ungoogled-software/ungoogled-chromium-portablelinux repo, that i adapted and adjusted until it worked for me. i use a debian bullseye based docker image with the current llvm 15 version (15.0.7 at this moment) and the node lts 16.xx version and execute a bash build script in it that is an adapted version of the build.sh in the portablelinux repo. So (i think) i just apply the patches from ungoogled-chromium  and execute the ninja builds (first gn tool, then chromium) without own code adjustements.

Thanks in advance for any hint or advice!

**Comment by clickot** [comment]
I wonder if it is correct to label this as a bug, but the other options when creating this issue seemed to me even more inappropriate..

**Comment by Ahrotahn** [comment]
My hunch would be that you need a newer version of node, but you mentioned that you already tried other versions.  

There have been a lot of changes to enable the TrustedType checks:  [(1098690)](https://bugs.chromium.org/p/chromium/issues/detail?id=1098690)
The more recent commits may be of interest:  [[3970137]](https://chromium-review.googlesource.com/c/chromium/src/+/3970137), [[3972236]](https://chromium-review.googlesource.com/c/chromium/src/+/3972236), [[3978936]](https://chromium-review.googlesource.com/c/chromium/src/+/3978936), [[3972221]](https://chromium-review.googlesource.com/c/chromium/src/+/3972221)

It might be possible to make a temporary workaround by reverting the changes they made in `third_party/node/node_modules/typescript/lib/lib.dom.d.ts`.

**Comment by clickot** [comment]
Thanks @Ahrotahn for your reply. What node version do you use during your builds? I would assume that the actual typescript code to be compiled is the same in my build and in your build, whatever platform or node version, or not?

**Comment by PF4Public** [comment]
I too suspect the need for a newer node. I'm building with v18 without issues.

**Comment by Ahrotahn** [comment]
I'm currently building with nodejs 19.4.0.  Yes that code should be the same as far as I'm aware.

**Comment by PF4Public** [comment]
> Yes that code should be the same as far as I'm aware.

Could be some backward compatibility breakages though.

@clickot Have you tried node 18 or 19?

**Comment by clickot** [comment]
build also fails with 19.4.0. I'm out of ideas and close this issue. Thanks!

**Comment by Ahrotahn** [comment]
Another idea to try would be to remove `node.patch` and in your build script change
`(cd "$_src_dir/third_party/node" && npm install node-linux-x64)`
to
`(cd "$_src_dir/third_party/node/linux" && npm install node-linux-x64)`


At least that's the path I use to link my system's version:
```
  mkdir -p third_party/node/linux/node-linux-x64/bin
  ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
```

**Comment by clickot** [comment]
@Ahrotahn : setting a symlink to the installed node on OS instead of additionally installing node as node module did the trick! my build works again, thank you very much!
