### ISSUE TITLE
Get rid of "mailto:" when copying email address

### ISSUE THREAD

**Issue by Nifury** [ungoogled-software/ungoogled-chromium#2224]
### Description

Please see below

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

When copying an email address (link), the "mailto:" scheme is also copied. It's frustrating to paste and remove the scheme every time I send an email. 

### Possible solutions

Do not change this variable 
https://github.com/ungoogled-software/ungoogled-chromium/blob/ec75c03e2555ab060abb534a9b0d34d39aabdbe9/patches/extra/ungoogled-chromium/disable-formatting-in-omnibox.patch#L16

so that the mailto scheme can be removed by `RenderViewContextMenu::FormatURLForClipboard`. 
https://github.com/chromium/chromium/blob/cec6fdae2e86af277796f89b801acc3a30698b67/chrome/browser/renderer_context_menu/render_view_context_menu.cc#L921-L935

Since the mailto link doesn't actually open a webpage, I think it's perfectly fine even if the mailto scheme is hidden in the address bar.

**Comment by PF4Public** [comment]
I suppose you do not want for some reason to just click the link for mail client to open, right?

**Comment by Nifury** [comment]
Yeah because I haven't found an email client on Windows that suits my needs. 

Anyway it's just a suggestion. I'm actually surprised that no one complained about it 😂.

**Comment by PF4Public** [comment]
> I'm actually surprised that no one complained about it .

I remember me copying some email I wanted to send a message to, got `mailto:`, shrugged my shoulders, removed the prefix and forgot about it. Maybe it just so happens that this is needed once in a century nowadays, so no one is angry :)

But anyway I believe this would be a benign change to the patch.

**Comment by Nifury** [comment]
Ah it happens to me so many times that even seeing `mailto:` drives me nuts. 

> But anyway I believe this would be a benign change to the patch.

Cool I'll go ahead and submit a PR.
