### ISSUE TITLE
Flag to create new button

### ISSUE THREAD

**Issue by calhix** [ungoogled-software/ungoogled-chromium#2226]
I was thinking about what would be the best way to make getting new updates as smooth/easy as possible in the future and thought of this. What about creating a flag that creates a button (like where the profile/sidebar/extensions buttons are) that points to a custom link. It could just be a link icon (ex: https://fontawesome.com/icons/link?s=solid&f=classic) and one could set it to go to https://github.com/ungoogled-software/ungoogled-chromium-windows/releases for example for the latest updates on Windows or whatever you want. Yes I know I can just create a bookmark on the bookmarks bar but I'm OCD and my bar doesn't have site names, they are just the site icons which would just be the Github icon in this case. It would also be nice for those that don't like having the bookmark bar showing also.

**Comment by PF4Public** [comment]
> I can just create a bookmark on the bookmarks bar but […] my bar doesn't have site names, they are just the site icons which would just be the Github icon in this case.

There are extensions, which allow changing icon for bookmarks.

**Comment by calhix** [comment]
For sure but I try to only have ublock origin be the only one enabled for fingerprinting purposes.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
