### ISSUE TITLE
Hardware decoding support for AV1 on LInux

### ISSUE THREAD

**Issue by Dkoeddnsnp** [ungoogled-software/ungoogled-chromium#2228]
### Description

Consider applying a patch, which adds vaapi hardware decoding support on Linux: https://chromium-review.googlesource.com/c/chromium/src/+/3952302

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

There is no hardware decoding support on supported devices for AV1 videos on Linux.

### Possible solutions

Please consider adding this patch:
https://chromium-review.googlesource.com/c/chromium/src/+/3952302

**Comment by jstkdng** [comment]
This will make a fine addition to my vaapi patches collection. I'll add it to my arch build, looks simple enough. But why wasn't this added?

**Comment by Dkoeddnsnp** [comment]
No idea. Here is an issue on their bugtracker.
https://bugs.chromium.org/p/chromium/issues/detail?id=1325824&q=av1%20hardware%20decoding%20linux&can=2

**Comment by PF4Public** [comment]
> But why wasn't this added?

There is a comment by one of the developers in the review.

I think this should go to a platform repository and like @jstkdng i'm taking this into mine :) Thanks for the heads-up.

**Comment by jstkdng** [comment]
Patch works great! [test video](https://www.youtube.com/watch?v=m1jY2VLCRmY)

That being said, this patch could benefit more people if added here.

**Comment by PF4Public** [comment]
> benefit more people

That [requires a rather recent hardware](https://wiki.archlinux.org/title/Hardware_video_acceleration#:~:text=AV1%208%2Dbit,6000%20and%20newer). 🤷
 
> added here

Like I've already mentioned, it should go into platform repo IMHO.

**Comment by Dkoeddnsnp** [comment]
> Patch works great! [test video](https://www.youtube.com/watch?v=m1jY2VLCRmY)
It works fine. But the hardware decoding of AV1 videos in Firefox is better. 8k60 videos stutter heavily in Chromium with RDNA 2  GPU, while Firefox plays them effortlessly without any dropped frames. 4k60 and lower videos play nicely with this patch.

**Comment by jstkdng** [comment]
> 8k60 videos stutter heavily in Chromium with RDNA 2 GPU

8k videos play fine with intel-media-driver

> That [requires a rather recent hardware](https://wiki.archlinux.org/title/Hardware_video_acceleration#:~:text=AV1%208%2Dbit,6000%20and%20newer). shrug

The patch will do it's job in recent hardware, but it doesn't hurt to have it still.
