### ISSUE TITLE
108.0.5359.124: libwayland: wl_surface@54: error 2: Buffer size ... is not divisible by scale

### ISSUE THREAD

**Issue by arbitrary-dev** [ungoogled-software/ungoogled-chromium#2229]
### OS/Platform

Gentoo

### Installed

Compiled from source

### Version

108.0.5359.124

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Browser exits when moving a picture

### How to Reproduce?

1. Go to https://gab.com/WholeHearted4God/posts/109771967867525776
2. Click on the image to open it
3. Try moving the pic (left mouse press and hold and move)
4. Rejoice!

### Actual behaviour

Browser exits with error.

### Expected behaviour

Browser continues working and picture is movable.

### Relevant log output

```sh
ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@59: error 2: Buffer size (399x331) is not divisible by scale (2)
```
```


### Additional context

wayland-1.21.0

CHROMIUM_FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland"
CHROMIUM_FLAGS="--enable-features=VaapiVideoDecoder --disable-features=UseChromeOSDirectVideoDecoder ${CHROMIUM_FLAGS}"
CHROMIUM_FLAGS="--disable-sharing-hub --hide-sidepanel-button ${CHROMIUM_FLAGS}"
CHROMIUM_FLAGS="--remove-tabsearch-button --scroll-tabs=never --tab-hover-cards=none ${CHROMIUM_FLAGS}"
CHROMIUM_FLAGS="--show-avatar-button=never ${CHROMIUM_FLAGS}"

**Comment by networkException** [comment]
Its highly unlikely that our patchset caused this as a regression. Please test with vanilla chromium (also this is an outdated version which won't be supported further)

**Comment by arbitrary-dev** [comment]
Fixed in later versions.
