### ISSUE TITLE
Headless HTML to PDF

### ISSUE THREAD

**Issue by ivanjaros** [ungoogled-software/ungoogled-chromium#2231]
### Description

Headles PDF generation is not working

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Using headless/CLI chromium/chrome used to be able to save a website into PDF or image by providing a url argument but it is no longer working. I have not tried it for a long time so I don't know when or why it stopped working. Is there a workaround? I tried ungoogled chromium, chrome and chrome canary(all should be the same core) but none are working.

### Possible solutions

Missing documentation?

**Comment by DAINRA** [comment]
Running:
`ungoogled-chromium --headless --disable-gpu --window-size=1920,5400 --screenshot https://somesite.com`
saves it as a png image. To output to pdf:
`ungoogled-chromium --headless --disable-gpu --print-to-pdf https://somesite.com`

**Comment by ivanjaros** [comment]
> 

unfortunately it does not work. it seems to be a windows issue since people on linux say it works. ff is the same along will all flavours of chrome.

**Comment by DAINRA** [comment]
Using ungoogled-chromium v97.0.4692.71 (win 32-bit) this works:
`chrome.exe --headless --dissable-gpu --window-size=1920x5400 --screenshot="C:\\Users\User\\Pictures\\shot.png" "https://somesite.com"`
Without a path it just saves it to the chromium directory (...\Appdata\Local\Chromium\Application\97.0.4692.71\shot.png) (also doesn't want to save it as c:\shot.png).

**Comment by ivanjaros** [comment]
Thank worked, thanks!

**Comment by ivanjaros** [comment]
One more thing - is there a way to get the cli configuration? chrome help, chrome -help nor chrome --help does not work. Also, is it possible to pipe the output into a socket or network connection instead of a file? Possibly getting some progress update as well in case of a big file or an error?
