### ISSUE TITLE
Is there a way to remove the search engine icon from address bar?

### ISSUE THREAD

**Issue by lapank0** [ungoogled-software/ungoogled-chromium#2233]
![Untitled](https://user-images.githubusercontent.com/124567794/216931333-937730a6-9545-4ceb-919a-2fb28a3a2f31.png)

**Comment by Ahrotahn** [comment]
There is [a patch](https://github.com/ungoogled-software/contrib/blob/master/tweaks/visual/default-search-icon.patch) on the contrib repo that you can build with to make it use the default search icon instead of the favicon.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
