### ISSUE TITLE
crash on start 110.0.5481.78-1.1

### ISSUE THREAD

**Issue by jacob755** [ungoogled-software/ungoogled-chromium#2241]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

110.0.5481.78-1.1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

run ungoogled-chromium X86 then crash

### How to Reproduce?

here screenshot
![crash](https://user-images.githubusercontent.com/65178892/218744310-1823ac21-09fd-4396-b7a7-0c5a0a94507e.png)

### Actual behaviour

.i have run it in clean profile and my using profile its crash with and without custom commands

### Expected behaviour

Run normally

**Comment by networkException** [comment]
Are you are you have a 32 bit system?

**Comment by tomasz1986** [comment]
I think the culprit may be Windows 8 (as that's what the window style looks like) which is no longer supported by Chromium. I can't test on Windows 8 here, but this version no longer starts in Windows 7 as well with a error about "entry point not found" in `kernel32.dll`.

On the other hand, there are no problems under Windows 10 32-bit.

**Comment by jacob755** [comment]
> Are you are you have a 32 bit system?

yes

**Comment by PF4Public** [comment]
Which makes it a no-issue for ungoogled-chromium, right?

**Comment by tomasz1986** [comment]
> Which makes it a no-issue for ungoogled-chromium, right?

It would be good to have a 100% confirmation that the OS is indeed Windows 8, but according to https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023, Chromium 110 and later does require Windows 10, so yeah.

**Comment by jacob755** [comment]
no idea [this](https://www.catsxp.com/) is opensource or not  but if its will you get part of code and build separate version for windows8 users? thanks

**Comment by networkException** [comment]
We do not provide support for other projects.

**Comment by jacob755** [comment]
> We do not provide support for other projects.
i mean if it is has patch take patch and separate version of ungoogled-chromium
