### ISSUE TITLE
How about to fix: window-position and window-size

### ISSUE THREAD

**Issue by Flashwalker** [ungoogled-software/ungoogled-chromium#2243]
### OS/Platform

Linux

### Installed

Flatpak, Appimage, apt

### Version

109

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

New window position and size are ignored

### How to Reproduce?

1. Run normal Chromium window and then sized one
```
firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ${HOME}/Downloads/Chromium-107.0.5297.0.glibc2.17-x86_64.AppImage \
--user-data-dir=/tmp/tmp-chr-dir "https://wttr.in" @@ >/dev/null 2>&1 &
sleep 3s
firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ${HOME}/Downloads/Chromium-107.0.5297.0.glibc2.17-x86_64.AppImage \
--user-data-dir=/tmp/tmp-chr-dir --window-size=800,600 --window-position=100,100 --chrome-frame --app="https://wttr.in"

```

2. Run normal Ungoogled-Chromium (Appimage) window and then sized one
```
firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ${HOME}/Downloads/ungoogled-chromium_107.0.5304.110-1.1.AppImage \
--user-data-dir=/tmp/tmp-ung-chr-dir "https://wttr.in" @@ >/dev/null 2>&1 &
sleep 3s
firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage ${HOME}/Downloads/ungoogled-chromium_107.0.5304.110-1.1.AppImage \
--user-data-dir=/tmp/tmp-ung-chr-dir --window-size=800,600 --window-position=100,100 --chrome-frame --app="https://wttr.in"

```

3. Run normal Ungoogled-Chromium (Flatpak) window and then sized one
```
flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u \
--user-data-dir=/tmp/tmp-ung-chr-flt-dir "https://wttr.in" @@ >/dev/null 2>&1 &
sleep 3s
flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u \
--user-data-dir=/tmp/tmp-ung-chr-flt-dir --window-size=800,600 --window-position=100,100 --chrome-frame --app="https://wttr.in" @@

```

### Actual behaviour

`--window-position` and `--window-size` options are ignored if you start a normal window before starting a sized window

### Expected behaviour

`--window-position` and `--window-size` options are respected if you start a normal window before starting a sized window

### Additional context

Known Chromium bags:
https://bugs.chromium.org/p/chromium/issues/detail?id=823991
https://bugs.chromium.org/p/chromium/issues/detail?id=178104

**Comment by networkException** [comment]
The scope of this project generally does not include fixing upstream issues
