### ISSUE TITLE
CTRL+Space unvailable

### ISSUE THREAD

**Issue by Quetzaal** [ungoogled-software/ungoogled-chromium#2250]
Hello everyone,
my chromium ungoogled version : 109.0.5414.120
- I checked on Edge : 110.0.1587.50
- on firefox nightly
and the keyboard shortcut CTRL + Space, no longer works (I used it to reload with AHK)
you might think i have a keyboard problem,
but on Otter Browser 1.0.02 it works without any problem
and worked until recently on Chromium

who will prevent them from trying to rot the keyboard,
- it's hardware, so not their property... grrrr

**Comment by networkException** [comment]
Can explain exactly what worked in a previous version and what doesn't now? I don't quite know what you mean by Edge, Firefox and AHK - none of these are related to this project

**Comment by Quetzaal** [comment]
hm, more explanation about a hotkey? CTRL+Space no longer works, like others on chromium... 
this may not actually be the place to do this well... 
since it has been banned on Edge and on firefox. in short, on all chromium forks... 
and I'm tired of them attacking the basic function of my PC
may have you a better adress to complain about their illegal action?

**Comment by tomasz1986** [comment]
Not really sure what the problem is about as there is no `Ctrl+Space` shortcut defined in the browser by default. Do you mean a custom mapping that you've created in AutoHotkey yourself? If yes, then the issue likely belongs to the AutoHotkey support forums, not here. At the very least, you should have posted the actual AutoHotkey script so that everyone could see what kind of shortcut you really mean.

And, Firefox is not a Chromium fork 😉.

**Comment by Quetzaal** [comment]
you're not wrong, it's may not the good place for it... but i was a few grrr... then i've post here first (why not)

here my code for ahk... pretty basic one
`#IfWinActive, ahk_exe chrome.exe 
   ^Space:: Send, {F5}            ; reload`

it's weird because i use it for a long time now, and still works fine with otterBrowser wich works on a Qtweb-engine. 

and as you say, firefox is nota chromium fork,then (as usual) i certainly did something wrong in my AHK code

thanks a lot

**Comment by Alex313031** [comment]
@Quetzaal @tomasz1986 @networkException I think what he means are quick commands (previously known as commander) which brings up a little dialog to do common tasks and show the keyboard shortcuts for them.

This is controlled by a chrome://flags (chrome://flags/#quick-commands) but can also be enabled by default here: 
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/ui_features.cc?q=kQuickCommands

**Comment by tomasz1986** [comment]
@Alex313031 Thank you for the tip, however I also use AutoHotkey and I've just tried to enable `#quick-commands`, yet my custom AutoHotkey shortcut still overrides the built-in one.

**Comment by Quetzaal** [comment]
hi all, 
i found the problem, and next, the solution
first, i thank you a lot, for your listening and advice

but, simply, as it has been said upper, just a problem of configuration of my AHK shortcuts
then LControl & Space:: Send,  {F5} and RControl & Space {F5} must replace, ^Space:: Send, {F5} (that i was using)

may it has been changed ??? but it been pretty disturbing for me as you read it upper. 

then make two shortcuts line instend of one... suprising, caus not usual at all... 

thanks a lot again
