### ISSUE TITLE
no sound on web-teams

### ISSUE THREAD

**Issue by crimsonduelist** [ungoogled-software/ungoogled-chromium#2258]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 103.0.5060.114 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

no sound in web-teams, notifications are showing properly though

### How to Reproduce?

add coockies as per https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-sign-in/sign-in-loop (first 3 marks) so as to rule that out
go to msteams official page and "Sign in"
go to chrome://settings/content or directly from "view site information" lock-sign on the left of the address bar and allow 1.notification 2.sound

### Actual behaviour

no sound upon receiving a message

### Expected behaviour

when a message is received sound should be made

**Comment by networkException** [comment]
> this is on a clean install of chromium

Do you mean you've tested this on vanilla (not ungoogled) chromium?

**Comment by crimsonduelist** [comment]
> > this is on a clean install of chromium
> 
> Do you mean you've tested this on vanilla (not ungoogled) chromium?

no I just mean I havent really messed with anything in settings

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by crimsonduelist** [comment]
Last I needed teams yeah, it s been a few weeks.
There was sound on calls but not on messages. Desktop notifications were showing though if enabled.
It s fine if it s not a priority, just wanted to mention the issue. If I have time I ll test it and update

**Comment by ureimers** [comment]
Hi,
just wanted to say, that I have the same problem since a few weeks. I'm on `Version 114.0.5735.134 (Official Build, ungoogled-chromium) (64-Bit)` and cannot pinpoint the start of this problem to a specific version.

Teams doesn't complain about my hardware and if I switch to Firefox it works.

**Comment by TimB87** [comment]
maybe `chrome://flags/#webrtc-ip-handling-policy`?

**Comment by ureimers** [comment]
> maybe `chrome://flags/#webrtc-ip-handling-policy`?

To what should I set this? "Default"?

And would that explain, why I can see video but simply cannot transmit microphone audio?

**Comment by TimB87** [comment]
I have it on Default.

**Comment by ureimers** [comment]
Thanks. Setting `chrome://flags/#webrtc-ip-handling-policy` to `Default` didn't help.Still no microphone audio transmitted. My mic is listed and selected, but my co-workers cannot hear me.

It works in Jitsi (even with the default "Disable non proxied udp") and in Firefox. But not in Chromium.

**Comment by TimB87** [comment]
Out of curiosity: what sound system do you use? alsa/jack/pulseaudio/pipewire/oss/..?

**Comment by ureimers** [comment]
As the platform is Windows, neither of those.

This is how it looks like in the Teams Web App (sorry, couldn't set the language to English, but I hope you get the gist):

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/1671217/529e62a8-7aa0-43be-a373-e8be49b65661)

**Comment by TimB87** [comment]
Sorry, I am out of ideas then

**Comment by PF4Public** [comment]
> I'm on `Version 114.0.5735.134 (Official Build, ungoogled-chromium) (64-Bit)`

@ureimers How did you install ungoogled-chromium?

**Comment by ureimers** [comment]
https://chromium.woolyss.com/

The portable, ungoogled build, which uses chrlauncher to keep Chromium updated (https://chromium.woolyss.com/f/chrlauncher-win64-stable-ungoogled.zip).

My current version is `Version 117.0.5938.150 (Official Build, ungoogled-chromium) (64-Bit)`.

**Comment by PF4Public** [comment]
@ureimers Please check if you could reproduce this issue with https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/117.0.5938.150-1
