### ISSUE TITLE
How to build custom settings?

### ISSUE THREAD

**Issue by cffgnu** [ungoogled-software/ungoogled-chromium#2268]
### OS/Platform

Windows

### Installed

Compiled from source

### Version

ungoogled-chromium version

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

guide me build custom settings with disable "Clear cookies and site data when you close all windows" by default..

### How to Reproduce?

guide me build custom settings with disable "Clear cookies and site data when you close all windows" by default.

### Actual behaviour

guide me build custom settings with disable "Clear cookies and site data when you close all windows" by default..

### Expected behaviour

guide me build custom settings with disable "Clear cookies and site data when you close all windows" by default..

**Comment by PF4Public** [comment]
Which steps have you attempted and what didn't work?

**Comment by cffgnu** [comment]
I using puppeteer automation to open browser:
`const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({
	executablePath: '../ungoogled-chromium_110.0.5481.177-1.1_windows/chrome.exe'
});`
But when i close browser by `browser.close();` will clear all session/cookies.
I want to keep session everything when close browser as normal chrome. How to fix it?
thanks

**Comment by Nifury** [comment]
Isn't it how puppeteer is designed? It creates a new profile every time you launch a headless instance. 
ungoogled-chromium won't clear data on its own.

**Comment by cffgnu** [comment]
sory, i also specific user data in puppeteer to keep cookie & session.
`userDataDir:'./myuserdata'`
but still clear cache after `browser.close();`

**Comment by Nifury** [comment]
So the vanilla chromium can keep cookie & session?
I remember there was a bug regarding relative user data dir and headless mode, but I'm not sure if it has been fixed or not.

**Comment by zer0mania** [comment]
Trying to do the same thing with "Clear cookies and site data when you close all windows" too, have you found any solutions?
