### ISSUE TITLE
System font scaling being ignored, text too small as result

### ISSUE THREAD

**Issue by Xathros1** [ungoogled-software/ungoogled-chromium#2272]
### OS/Platform

Opensuse Tumbleweed

### Installed

Flatpak

### Version

Version 111.0.5563.64 (Official Build, ungoogled-chromium) (64-Bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

The system font scaling is being ignored, the text stays too small as result, for e.g. in all UI elements and bookmarks.
Changing the font size in settings doesn't change the text in those UI elements. 

### How to Reproduce?

Running GNOME 43.3
Goto Gnome Tweaks 
Fonts
Adjust scaling factor to for e.g. 1.5
run Ungoogled Chromium
Nothing changes the font doesn't adjust.

The normal scaling (display settings) does work however for e.g. 200%.

### Actual behaviour

The font stays small

### Expected behaviour

The fonts adjust to the scaling factor

### Relevant log output

```sh
Note sure if this output is relevant to the issue:
cb@tumbleweed-pc:~> flatpak run com.github.Eloston.UngoogledChromium 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2:2:0318/173553.466780:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

**Comment by PF4Public** [comment]
@rany Is something broken in flatpak release?

**Comment by Xathros1** [comment]
To illustrate the issue here are two images

1)Ungoogled Chromium with 150% Site- Zoom. (Only works on sites; makes it usable at least)
![ungoogled](https://user-images.githubusercontent.com/72621668/226416115-8ada5475-b157-44d6-a131-aab9a4dc6a97.png)

2)Firefox without zoom and just the set font scaling to 1.5 (in gnome tweaks)
![firefox](https://user-images.githubusercontent.com/72621668/226416167-56158c85-7d8c-41ab-ad9f-fe16dd9a1d02.png)

**Comment by PF4Public** [comment]
Have you tried filing this issue with flatpak repository?

**Comment by rany2** [comment]
Flatpak could not get the settings you set in GNOME Tweaks. The reason why that setting is not exposed in regular GNOME settings is because it causes issues with sandboxed applications, however I do think that if you did not override any of the default permissions it should work (It has full access to home directory, so the config should be accessible.. unless you "hardened it")

**Comment by Xathros1** [comment]
No, I have not tried to file this issue with flatpak repo.

I haven't tried messing with the default permissions either.

**Comment by rany2** [comment]
@Xathros1 Another Chromium fork (Brave) seem to have had an issue with font rendering on Linux, maybe it got fixed in the latest updates. I can't reproduce any of the issues filed anymore.

**Comment by rany2** [comment]
Are you by any chance using Wayland?

**Comment by Xathros1** [comment]
> Are you by any chance using Wayland? Edit: to elaborate, I have tested it and scaling works fine with latest Flatpaked Ungoogled on X11.

Yes, I'm using Wayland and it looks like that is indeed the issue. 
Apparently I've set the "Flag" 'Preferred Ozone platform' to 'Auto' some time ago (which attempts to use Wayland) - I've since upgraded to a bigger screen with UHD resolution. Setting it back to 'Default' and restarting the Browser does fix my issue.
