### ISSUE TITLE
Browsing and Download History got deleted automatically, even when settings are off.

### ISSUE THREAD

**Issue by TontyTon** [ungoogled-software/ungoogled-chromium#2274]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 110.0.5481.177 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

In one of my profiles of ug-chromium, all histroy (both download and browsing) got deleted automatically in one profile. I have #keep-old-history flag enabled for more than a year. All auto clear settings are off.

### How to Reproduce?

Not applicable

### Actual behaviour

Not applicable

### Expected behaviour

Not applicable

### Additional context

I think the reason is that file size limit was reached, I think so because same didn't happen in any other profile, as I use them less regularly.

I have a backup from December 2022, in that 'history' file size is around 14 MB. It has history from December 2021.

If you need any logs, or want to know anything, please do ask.

**Comment by networkException** [comment]
My History file is almost 200MB, I don't think there is a limit

**Comment by TontyTon** [comment]
@networkException Then how to check possible cause? Any logs which can be useful to diagnose?

**Comment by PF4Public** [comment]
@TontyTon Is this an issue in 114 version?

**Comment by TontyTon** [comment]
It happened only once, so can't say if it will happen again or not. Since, we don't have information, ig it's safe to close the issue. What do you say?

**Comment by PF4Public** [comment]
Agreed! I'd like to have open only those issues on which we can act somehow.

But feel free to add more information when/if you have it.
