### ISSUE TITLE
Journeys Support in History

### ISSUE THREAD

**Issue by javaskript** [ungoogled-software/ungoogled-chromium#2283]
### Description

Journeys Support in History

### The problem

The Journeys tab displays in the History menu, but there is no content shown in Journeys. Is this intended?

### Possible solutions

Enable Journeys in Ungoogled Chromium, the option to disable it is also already present in needed.

**Comment by networkException** [comment]
I feel like these used to work

**Comment by PF4Public** [comment]
It newer worked for me IIRC, I didn't do a rigorous test though.

**Comment by javaskript** [comment]
> It never worked for me IIRC, I didn't do a rigorous test though.

Does it possibly require Google services to function? Because it seems to work in Thorium and other Chromium forks (not all of them, but some).

**Comment by PF4Public** [comment]
I guess, no one botherd to investigate what it needs.

**Comment by larrasket** [comment]
It actually used to work fine with me months ago I thought it was a bug.

**Comment by BachoSeven** [comment]
@javaskript did you ever figure out why?
