### ISSUE TITLE
Ungoogle chrome://new-tab-page/ and make it able to be used without using an obscure flag

### ISSUE THREAD

**Issue by TorutheRedFox** [ungoogled-software/ungoogled-chromium#2284]
### Description

The default (and more capable) new tab page is inaccessible without using the custom-ntp flag.
As a side note, it still has the Google branding.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Chromium by default only uses chrome://new-tab-page/ if your search engine is the built-in Google option, which isn't even a thing here, making it fall back to chrome://new-tab-page-third-party/ instead, which has very limited functionality (it doesn't even allow you to use custom shortcuts, which is what the issue was originally about).

### Possible solutions

Ungoogle chrome://new-tab-page/ and make it so that the conditions it requires can actually be met (full and working info in a custom search engine, which the default ones already have)

**Comment by PF4Public** [comment]
Have you tried [`--custom-ntp`](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.)?

**Comment by TorutheRedFox** [comment]
> Have you tried [`--custom-ntp`](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.)?

I prefer having the shortcuts, but with the ability to curate them myself rather than Chromium doing it for me

**Comment by PF4Public** [comment]
Have you tried using `chrome://new-tab-page/` via [`--custom-ntp`](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.) or `chrome://flags/#custom-ntp`?

**Comment by networkException** [comment]
@PF4Public do you want to add that URL to the flags documentation (/wiki)?

**Comment by TorutheRedFox** [comment]
> Have you tried using `chrome://new-tab-page/` via [`--custom-ntp`](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.) or `chrome://flags/#custom-ntp`?

the feature requested here is to add the "Customize this page" button to the new tab page from Chrome which brings up this menu, from which you can customize the shortcuts shown on the built-in page or hide them completely, among other things.
![image](https://user-images.githubusercontent.com/15708278/228807604-ef69c539-5dd6-49c0-8103-7f154cf3de74.png)

**Comment by PF4Public** [comment]
@TorutheRedFox Sorry, but my patience isn't infinite. Have you tried what I suggested 2 times already, or not?
![image](https://user-images.githubusercontent.com/10319700/228809620-c865f122-95a3-477d-8c7b-3568dcf902f0.png)

**Comment by PF4Public** [comment]
> there should be an option to customize the default one though

chrome://flags/#custom-ntp

**Comment by TorutheRedFox** [comment]
without having to set a flag

kinda a user friendliness issue here, maybe change the conditions under which the third party one is used, since here you can make any search engine as good as using google, while in chrome you can't (guess why that could possibly be), making using the standard one (sans google branding) be more logical

say, if you set up a search engine fully with search prediction URL and all, use the default one, otherwise use the third party one

**Comment by PF4Public** [comment]
> say, if you set up a search engine fully with search prediction URL and all, use the default one, otherwise use the third party one

Would you be willing to implement this feature?

**Comment by TorutheRedFox** [comment]
if i get the time to get accustomed to the source structure then i would, but right now i'm not sure about that coming in the near future, but maybe

oh and side note, the custom-ntp flag makes the favicon keep showing the loader

**Comment by hyperion4** [comment]
The way --custom-ntp=chrome://new-tab-page/ works is not a solution.
Because the way it works cripples functionality.
For example if a user installs the web store and installs a new tab extension like Humble New Tab extension, then the extension can't change the new tab page.
The user is stuck with the new tab page set by the setting.
If the setting could only change the default, but could also "respect" the change of it from an extension, that would be the ideal solution.
