### ISSUE TITLE
Can't install any extensions

### ISSUE THREAD

**Issue by DraconicNEO** [ungoogled-software/ungoogled-chromium#2294]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

Version 111.0.5563.146 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

I am unable to install any extensions either from file or from the webstore

### How to Reproduce?

1. Go to Webstore
2. Click on extension Page
3. Install/add button will not be present

Alternatively for local installs

1. Go to chrome://extensions
2. Enable developer mode
3. Drag crx extension into window to install it

### Actual behaviour

When attempting to install from the webstore the button to install the extesnions isn't there on the extension page. If I try to go to the crx link directly it'll say that the extension cannot be installed from this site.

When attempting to install locally it'll give the message CRX_REQUIRED_PROOF_MISSING

### Expected behaviour

The extensions should install without hitch or complaints and the install button should be present in the webstore

**Comment by Nifury** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore

**Comment by DraconicNEO** [comment]
Resolved:

Solution: `change chrome://flags/#extension-mime-request-handling`  to `Always prompt for install` and Importantly **Restart the Browser**

**Comment by DraconicNEO** [comment]
> https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore

Ah I see, I didn't know about that though I guess it makes sense that it wouldn't work normally.

> Wow Night Fury!

Thanks, I guess.

**Comment by PF4Public** [comment]
This is definitely one of the things we should put into welcome page!
