### ISSUE TITLE
 Prevent WEBRTC Leaks in UNG.C by Adding "WEBRTC Leak Prevent" Extension's Feature Natively

### ISSUE THREAD

**Issue by Cleveho** [ungoogled-software/ungoogled-chromium#2296]
### Description

 Prevent WEBRTC Leaks in UNG.C by Adding "WEBRTC Leak Prevent" Extension's Feature Natively

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Ungoogled-chromium, by default, exposes the local IP address of a computer on the network, which is a potential privacy risk. Although there is a flag called "Anonymize local IPs exposed by WebRTC," enabling it does not effectively hide the leaking address.

### Possible solutions

Fortunately, an open-source Chrome extension called [WebRTC-Leak-Prevent](https://github.com/aghorler/WebRTC-Leak-Prevent), available on GitHub, can help prevent these leaks. It is recommended to implement this extension natively in order to effectively stop the local IP address from being exposed.

**Comment by PF4Public** [comment]
Should be fixed with upcoming release.
