### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by AssassinK786** [ungoogled-software/ungoogled-chromium#2297]
### Description

Auto Update Ungoogled chromium

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

It is not easy to download every version of ungoogled chromium and the winget and other Package Manager(including linux repo) take time to update their repo which is not advantageous. It will be better to make a this request viable

### Possible solutions

auto update in the browser itself

**Comment by networkException** [comment]
Having an auto updater won't make releases available faster than in winget. Releases in this repository only include source code, actually building binaries takes time. With the resources currently available to this project, however long it takes to get a winget release out is already the fastest way possible

**Comment by AssassinK786** [comment]
![image](https://user-images.githubusercontent.com/85348050/229334338-5eca5cfc-4204-4a81-8a5f-e01fc23d71f6.png)
I'm asking for this update

**Comment by networkException** [comment]
We generally don't want to deal with adding our own updating infrastructure into the patchset.

**Comment by techgamers2** [comment]
> ![image](https://user-images.githubusercontent.com/85348050/229334338-5eca5cfc-4204-4a81-8a5f-e01fc23d71f6.png) I'm asking for this update

https://github.com/ltguillaume/librewolf-winupdater check this repo out its same thing i also want for chromium browser
