### ISSUE TITLE
Search engine suggestions don't appear in omnibar

### ISSUE THREAD

**Issue by krosa100** [ungoogled-software/ungoogled-chromium#2301]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

108.0.5359.99

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Search engine suggestions don't appear in omnibar

### How to Reproduce?

1. Type 'bing.com cat' in omnibar

### Actual behaviour

Only suggestions based on your history appear.

### Expected behaviour

In Chrome, you would see e.g. "caterpillar".

**Comment by Nifury** [comment]
It seems you need to enable this option. 
![image](https://user-images.githubusercontent.com/7867461/229591004-55a2a8e5-9e32-4cea-8a81-58e18dcad67b.png)

**Comment by krosa100** [comment]
Thanks. 

For Google, you need to set 'Suggestions URL with %s in place of query' to, for example, 'https://www.google.com/complete/search?client=chrome&q=%s'.
