### ISSUE TITLE
Add Thorium browser patches

### ISSUE THREAD

**Issue by xplshn** [ungoogled-software/ungoogled-chromium#2302]
### Description

Performance optimizations from Thorium browser

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I used to use this browser, https://github.com/Alex313031/thorium it is not privacy oriented, but it has tons of performance optimizations, and is pretty vanilla, its the same as Chromium but optimized, also, the patches are listed and are applied in a clean way. Maybe you can add these https://thorium.rocks/optimizations.html
Useful links and detailed documentations: https://thorium.rocks/docs/ https://thorium.rocks/misc/dev

### Possible solutions

Applying just the compiler optimizations

**Comment by xplshn** [comment]
Also interesting https://thorium.rocks/docs/sandbox.html

**Comment by PF4Public** [comment]
Please be more specific about which patches you mean exactly. Thorium has lots of patches which are already present in ungoogled-chromium.

**Comment by xplshn** [comment]
I mean these, also they are compiler optimizations listed here https://thorium.rocks/optimizations.html and the sandbox patches are excellent and well explained https://thorium.rocks/docs/sandbox.html

**Comment by PF4Public** [comment]
Please be more specific about which patches you mean exactly. Thorium has lots of patches which are already present in ungoogled-chromium.
