### ISSUE TITLE
Add Chrome memory saver/vertical tabs

### ISSUE THREAD

**Issue by vvirtues** [ungoogled-software/ungoogled-chromium#2303]
### Description

Add Chrome's new memory saver.  Also consider vertical tabs

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Both of these features are not currently found in Ungoogled-Chromium, but can be found in Google Chrome

### Possible solutions

You can implement Google Chrome's memory saver, or make an open-source alternative that doesn't replace the page URL, like extensions do.

 Though vertical tabs are not officially supported in Google Chrome (afaik), they can be found in chrome://flags on chrome, not chromium

### Alternatives

Using the great tab suspender (overruled because of previous drama with the extension, also replaces tab URLs, losing them if you remove the extension

Using a vertical tabs extension (overruled because they do not move the tab bar and make chrome look ugly)

**Comment by networkException** [comment]
The memory saver should be available starting with version 113.0.5672.63-1.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by BachoSeven** [comment]
@networkException regarding this, I'm experiencing that the "Memory Saver" feature over at chrome://settings/performance is not saved upon restarting Ungoogled Chromium, is there a flag to make it persistent somehow?

**Comment by networkException** [comment]
On what platform?

**Comment by BachoSeven** [comment]
Arch Linux, 

116.0.5845.140 (Official Build, ungoogled-chromium) (64-bit)

Btw it hasn't happened since, but I feel like it periodically reset, maybe after updating it (will check next update).

**Comment by Connor-GH** [comment]
more about this: here is the brave browser's commit for vertical tabs: https://github.com/brave/brave-core/commit/e9c04aa282166f0b83c2e3de4028af303228a45c
