### ISSUE TITLE
need win Portable

### ISSUE THREAD

**Issue by sixgodfan** [ungoogled-software/ungoogled-chromium#2307]
### Description

111

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

need win Portable

### Possible solutions

need win Portable

**Comment by PF4Public** [comment]
Is it not?

**Comment by PF4Public** [comment]
Please provide more information on the issue, so that someone could help you further.

**Comment by plashenkov** [comment]
Probably @sixgodfan wants Ungoogled Chromium to store settings and user data inside its directory to be completely portable. 

Currently Ungoogled Chromium, like Chrome, stores settings and user data in a system-wide directory.

As an example, VSCodium (unmicrosofted VS Code) allows you to create the `/data` folder inside its directory, and after that it starts to keep all settings and user data there (to be fair, this is thanks to original VS Code itself allows to do this).

It would be great if Ungoogled Chromium allowed this. Everything lives in one dir.

**Comment by TheNocoder** [comment]
In my case I use the portable version of linux (I imagine that in windows there is a similar solution, but I don't know it) in pen drive and in a usb hard disk.

Just run it like this: 

`./chrome --user-data-dir=./config-data`

Maybe someone who knows windows can find the equivalent.

**Comment by plashenkov** [comment]
@TheNocoder 

Yes, this works, thank you!

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
