### ISSUE TITLE
Popup window not show

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium#2323]
### OS/Platform

Windows
Manjaro

### Installed

Compiled from source

### Version

112.0.5615.49
112.0.5615.138

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Popup window is blank

### How to Reproduce?

* Reproduce
  1. Open https://www.ithome.com
  2. Click the login button
  3. The login window is blank

* Screenshot
![image](https://user-images.githubusercontent.com/3665590/233289961-f99cb74a-6ac8-47fb-88de-75b17764e557.png)

### Actual behaviour

The login window is blank.

### Expected behaviour

The login window should work normally.

**Comment by PF4Public** [comment]
Have you tried disabling all extensions?

**Comment by playgithub** [comment]
no extension there

**Comment by PF4Public** [comment]
I highly doubt it could be an issue with ungoogled-chromium and you didn't show how you identified it to be one.

**Comment by playgithub** [comment]
Tried chromium 116.0.5841.0, same problem, i.e. it's not ungoogled-chromium specific.

**Comment by PF4Public** [comment]
Have you tried contacting website owner? They may be unaware of a problem.

**Comment by playgithub** [comment]
> Have you tried contacting website owner?

Yes, I've reported it several weeks ago, it's likely ignored.
