### ISSUE TITLE
Can't authenticate twitch from extension settings

### ISSUE THREAD

**Issue by ReyZ19** [ungoogled-software/ungoogled-chromium#2325]
### Description

Can't authenticate twitch from extension settings

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I installed this extension, when I try to login to twitch from the settings of the extension, even if I log in, I am not seen logged in. It redirects me to `https://iiljidcefnbhbpamageahhblhbbhhopm.ch40m1umapp.qjz9zk`

i've tried other extension that does same thing happens

### Possible solutions

I think `https://iiljidcefnbhbpamageahhblhbbhhopm.ch40m1umapp.qjz9zk` should be `https://iiljidcefnbhbpamageahhblhbbhhopm.chromiumapp.org` or something

### Additional context

![image](https://user-images.githubusercontent.com/77238876/233786353-fcf366d7-d18d-4fd1-bcd2-a65b506584cf.png)

**Comment by PF4Public** [comment]
This might be due to domain substitution which is a part of ungoogled-chromium. 

One could probably avoid this issue by selectively disabling domain substitution, but that requires manual building.
