### ISSUE TITLE
Disneyplus Error 83 

### ISSUE THREAD

**Issue by Itsredsect** [ungoogled-software/ungoogled-chromium#2330]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

 112.0.5615.165 

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

When I try to turn on a movie on Disney plus, I get the error code (Error 83). 

### How to Reproduce?

1. go to disneyplus 
2. open a Movie or Episode
3. The Error code 83 appears

### Actual behaviour

When I try to start a movie on Disney plus, I just get an error message. In the logs it says only :30:17.326 Mel[1] 5301 DRM_SYSTEM_ACCESS_FAILED no drm system access for com.widevine.alpha -while- starting 1-c Multivariant playlist url: null
c

### Expected behaviour

Actually the film should start

### Relevant log output

```sh
ndor.aa6e91ed2604bc6a2238.js:2 You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
c

ndor.aa6e91ed2604bc6a2238.js:2 (ERROR):  [ErrorEpic] Fatal Error {playhead: 0, cause: 'error', errorName: null, error: 'drmDecryption', errorDetail: '5301 DRM_SYSTEM_ACCESS_FAILED no drm system access for com.widevine.alpha -while- starting 1-c', …}
c
:30:17.326 Mel[1] 5301 DRM_SYSTEM_ACCESS_FAILED no drm system access for com.widevine.alpha -while- starting 1-c Multivariant playlist url: null
c
```

### Additional context

![image](https://user-images.githubusercontent.com/95378207/235238332-29665ef8-23a5-4c8e-a64f-dac99e70f90e.png)

**Comment by PF4Public** [comment]
> ### Expected behaviour
> Actually the film should start

This [quoted] is actually the opposite of what is to be expected.
Have you seen these issues: [is:issue disney](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+disney) and [is:issue widevine](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+widevine)?

**Comment by Itsredsect** [comment]
I tried a few of these solutions, but found that there was no folder with Widevine. Also, the folder structure did not match at a certain level.

**Comment by PF4Public** [comment]
@rany2 Does widevine work in Flatpak anyway?

**Comment by Itsredsect** [comment]
yes it works i installed Google Chrome via Flatpak and Disney plus works perfectly. In Google Chrome i also found the Widevine Folder

**Comment by PF4Public** [comment]
> In Google Chrome i also found the Widevine Folder

Have you tried copying it into ungoogled-chromium folder?

**Comment by Itsredsect** [comment]
yes but i cant copy the folder. it shows an error that the folder cant be creat

**Comment by Itsredsect** [comment]
ok it works now. I copied the WidevineCdm Folder into the chromium folder. this is the adress:
com.github.Eloston.UngoogledChromium/x86_64/stable/0f9739c930868afdf9b9c7758e8b945fc104e9bbe5c32980cc1283d9a90a34de/files/chromium/
It worked after i reboot my System. Maybe this can help for future Problems. thanks for your support

**Comment by PF4Public** [comment]
So it seems that widevine does in fact work with ungoogled-chromium.
