### ISSUE TITLE
Dns mimic check removal.

### ISSUE THREAD

**Issue by ToxicMushroom** [ungoogled-software/ungoogled-chromium#2331]
### Description

Remove dns mimic checks if they contact some service

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

`Attackers sometimes mimic sites by making hard-to-see changes to the web address`
![image](https://user-images.githubusercontent.com/32853531/235300895-ca0efbb8-6c65-4f81-badc-687cf88f138e.png)

How does it detect this ?
Is it simply going through my browser history and checking for close matches or is it getting this info from googles database, if the latter then it's leaking my dns requests ?

### Possible solutions

Remove this if this is the latter.

**Comment by networkException** [comment]
According to their docs its local only: https://chromium.googlesource.com/chromium/src/+/master/docs/security/lookalikes/lookalike-domains.md

To be honest I've never seen one of those warnings while using ungoogled-chromium

**Comment by ToxicMushroom** [comment]
> According to their docs its local only:

Ah okay that's a relieve.
thanks a lot for taking the time to check it out and the fast response <3


> To be honest I've never seen one of those warnings while using ungoogled-chromium

The domain that triggered it is private site and a 1 letter missmatch of a popular site so it is a valid popup still.
