### ISSUE TITLE
HEVC / x265 support

### ISSUE THREAD

**Issue by guria9** [ungoogled-software/ungoogled-chromium#2332]
### Description

add hevc support 

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

HEVC / x265 support missing

i have seen one issue closed with tag duplicate, but i could not find the one being open / closed which discussed the issue
and it would be really nice if you could add it.

### Possible solutions

https://github.com/search?q=repo%3AAlex313031%2Fthorium+hevc&type=commits

https://github.com/Alex313031/thorium/blob/51dbe0c8af8bcc779beef2c4523c1537762c49a4/other/add-hevc-ffmpeg-decoder-parser.patch#L4

https://github.com/Alex313031/thorium/tree/main/src/third_party/ffmpeg/libavcodec
https://github.com/Alex313031/thorium/blob/main/src/third_party/ffmpeg/libavcodec/hevc.h

>I'm willing to implement this feature myself

sadly im involved in other projects so much that my job etc already suffer from it. 
it would not come soon or could i guaranty it would come for sure.

### Alternatives

use Microsoft edge, hope it triggers someone :smile:

**Comment by PF4Public** [comment]
This should go into platform repo. Gentoo and Arch have hevc support since some time already.

**Comment by guria9** [comment]
It would be very kind when all platforms / packaging formats could have it.

**Comment by PF4Public** [comment]
Please file this issue with the platform that you think should support it.

**Comment by guria9** [comment]
https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/105#issuecomment-1529813718

> Bring this request to [upstream](https://github.com/eloston/ungoogled-chromium), this is beyond the scope of this package.

guys where is your teamwork. 

just closing the issue seems not reasonable to me.

**Comment by PF4Public** [comment]
@rany2 This should be implemented per platform, not here. Do you not agree?

Like I've already mentioned, Gentoo and Arch have implemented hevc in platform repositories.

**Comment by rany2** [comment]
@PF4Public Why isn't x265 support added on ungoogled-chromium proper? Why the inconsistency between platforms? Seems like this is a recipe for confusion as users switch between platforms expecting the same core functionality.

**Comment by rany2** [comment]
Anyway I'm not here to start a war, if the consensus is that this should be implemented on the platform side then I will do just that. I just thought that crucial functionality like video codec would be done on UGC so we don't have "franken UGC" where every platform eventually has a variant of UGC unrecognizable from the source.

**Comment by PF4Public** [comment]
Hmm, it seems to be enabled by default nowadays.
https://source.chromium.org/chromium/chromium/src/+/refs/tags/113.0.5672.63:media/media_options.gni;l=116-122;drc=1ec72b6410df5f90eaf4f24f33074f8682c7ffc5
```gn
  # Enable inclusion of the HEVC/H265 parser and also enable HEVC/H265 decoding
  # with hardware acceleration assist. Enabled by default for fuzzer builds,
  # Windows, Mac, and Android.
  enable_hevc_parser_and_hw_decoder =
      proprietary_codecs &&
      (use_fuzzing_engine || is_win || is_mac || is_android || is_linux)
}
```
If my assumption is correct, it should be working out of the box. @guria9 Are you sure it does not work for you?

**Comment by rany2** [comment]
@PF4Public https://html5test.com says not, but it is the same for Google Chrome and Microsoft Edge.

**Comment by jstkdng** [comment]
it is enabled, but HEVC videos don't play without a patch at least in 112. With the patch hevc videos play but aren't hw accelerated, only software playback through ffmpeg.

>Gentoo and Arch have implemented hevc in platform repositories

it was on arch but was removed after an update broke it, it is still in the AUR though.

**Comment by jstkdng** [comment]
@rany2 have you tried to play hevc videos? it also appears as disabled in that test page but playback works.

**Comment by rany2** [comment]
@jstkdng X265 videos do not play on Edge (flatpak), Chrome (deb), Chromium (flatpak), or Ungoogled Chromium (flatpak).

**Comment by guria9** [comment]
I can confirm HEVC Videos work on [thorium](https://github.com/Alex313031/thorium)

**Comment by jstkdng** [comment]
Huh, that is weird, I guess the patch doesn't work with everyone.

**Comment by guria9** [comment]
i did use: https://aur.archlinux.org/packages/ungoogled-chromium (self compiling) back in the days. 
fact is it does not work or can anyone confirm otherwise ? im no longer using arch

**Comment by guria9** [comment]
> would not fit into this core repository

i some what disagree. why you dont add a simple case switch to use ffmpeg in linux. i agree using windows build-in codecs is most likely the best way to go but to have such (from my point of view) massive patches every linux packaging format to manually decide which way to go makes it less easier to maintain from the people who package it for linux which is not necessary.  i mean it would be a nice to have, i would not count that every dev figures it out for each packaging format by his own and is even aware of this situation so i would suggest it should be in the core.

it would be the decision if you are fine with losing users to less private chromium builds and keep it the way it is 
or do you make the effort to make it as easy as possible to support it out of the box for all package maintainers.

maybe you are right and it would be best to leave it out of core but than it might be time to educate the package maintainers on how to try to support it, but i dont know how much sense it makes to let 5 linux packaging formats each by its own figure it out how it works when it could just be enabled by default.

**Comment by rany2** [comment]
@guria9 Don't worry too much about this, I'll add support in the Flatpak. @PF4Public provided enough guidance for me to pull it off, essentially I need to patch `bool IsHevcProfileSupported` to always return true which is relatively straight forward all things considered.

I would have also preferred if this was in core UGC, it's funny how they are decoding AV1 without any checks like these but HEVC magically needs to run ONLY on platforms which _definitely_ have hardware decoding support. Absolutely ridiculous...

**Comment by PF4Public** [comment]
@guria9 I'm not trying to convince anyone, I was just stating my own opinion. If maintainers of ungoogled-chromium would consider hevc patching a fitting thing for core repo — so be it.

>if you are fine with losing users

Please stop it right away :) We're not winning users, we're not losing users. We're making modifications _available_ for everyone to use. What they do with these modifications is up to them (as long as licensing terms are not breached).

You see, patching `IsHevcProfileSupported` might have unknown consequences, so that's one of the concerns.

>essentially I need to patch bool IsHevcProfileSupported to always return true

[Exactly](https://github.com/PF4Public/gentoo-overlay/blob/b19cb1445792956848aab89f7b94ffcaad4ab0bf/www-client/ungoogled-chromium/ungoogled-chromium-113.0.5672.63_p1.ebuild#L393-L396)!

>it's funny how they are decoding AV1 without any checks like these but HEVC magically needs to run ONLY on platforms which definitely have hardware decoding support. Absolutely ridiculous...

If I had to guess, I'd imagine this would be in the realm of `proprietary-codecs` distinction thing, supplemented by the need to advertise and spread AV1 codec in favour of others, like HEVC for instance :)

**Comment by rany2** [comment]
@PF4Public Thank you, I hope you don't mind me stealing that sed command. Looks like a work of art!

**Comment by PF4Public** [comment]
> @PF4Public Thank you, I hope you don't mind me stealing that sed command. 

Sure, take it. By default sed doesn't return error if no matches found, this command is so convoluted to be able to detect if they changed something so that regexp no longer applies. It should die with error in that case.

> Looks like a work of art!

Oh, stop it you \*blush\*

**Comment by rany2** [comment]
There you go @guria9 https://github.com/flathub/com.github.Eloston.UngoogledChromium/pull/106 :)

**Comment by PF4Public** [comment]
@rany2 I usually build ungoogled-chromium against system ffmpeg, not built-in, so I'd suggest checking that also. Cannot tell you if built-in ffmpeg decodes hevc or not.

**Comment by rany2** [comment]
@PF4Public From a quick look it appears necessary, built-in ffmpeg does not have support for this. I'm not going to bother with this as it involves too many changes to built-in ffmpeg and I can't just have it use system ffmpeg due to Red Hat licensing reasons.

**Comment by guria9** [comment]
I thank you both so much for stating my own opinions and effort in order to make this modifications available.
