### ISSUE TITLE
Tiny cursor in Chrome-based Flatpak browsers

### ISSUE THREAD

**Issue by illeng** [ungoogled-software/ungoogled-chromium#2335]
I'm experiencing an issue with Chrome-based Flatpak browsers where the cursor appears very small upon opening. This includes browsers like Google Chrome and Chromium. The small cursor makes it difficult to navigate and use the browser effectively. I'm running the latest version of Chrome OS on my device. Is there a fix or workaround for this issue?

**Comment by PF4Public** [comment]
What does it have to do with ungoogled-chromium?

**Comment by illeng** [comment]
> What does it have to do with ungoogled-chromium?

I meant chromium based. And as we both know Ungoogled-Chromium is chromium based and it also has a tiny consor and makes the browser unusable.

**Comment by PF4Public** [comment]
Please file this issue with Flatpak. It has nothing to do with ungoogled-chromium.
