### ISSUE TITLE
Media Control Button crashes the browser

### ISSUE THREAD

**Issue by MineTechCode** [ungoogled-software/ungoogled-chromium#2338]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

113.0.5672.64

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Clicking the media control button closes the browser immediately

### How to Reproduce?

1. Go to youtube.com
2. Play some video
3. Click the media control button

### Actual behaviour

Clicking the media control button closes the browser immediately without an error message

### Expected behaviour

Open the media hub

### Additional context

https://chromium.woolyss.com/

**Comment by PF4Public** [comment]
Sorry, we do not provide support for third party binaries. Please try https://ungoogled-software.github.io/ungoogled-chromium-binaries/
