### ISSUE TITLE
Downloaded files are not visible on the desktop

### ISSUE THREAD

**Issue by SerdarSaglam** [ungoogled-software/ungoogled-chromium#2339]
### OS/Platform

Windows 11

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

113.0.5672.64-1.1

### Description

Downloaded files are not visible on the desktop

### How to Reproduce?

Select the desktop as the download location.

### Actual behaviour

When Desktop is selected as the download location, you need to Refresh the Desktop to see the downloaded files.

C:\Users\User\Desktop = Downloaded files in this location are not visible. (Refresh required)

C:\Users\User\Downloads = No problem

### Expected behaviour

The file should appear on the desktop without refreshing.

**Comment by PF4Public** [comment]
Have you tested that this is not an upstream issue or an issue with your configuration?

**Comment by SerdarSaglam** [comment]
Yes that's how it only happens with ungoogled-chromium.

**Comment by PF4Public** [comment]
I really doubt that this is an issue with ungoogled-chromium patches rather then Windows itself. Please try latest version, this might be fixed there if it is a genuine Chromium bug.
