### ISSUE TITLE
Should we consider adding crbug.com and anglebug.com into domain substitution?

### ISSUE THREAD

**Issue by PF4Public** [ungoogled-software/ungoogled-chromium#2340]

**Comment by networkException** [comment]
Are there any codepaths that would attempt loading those domains? I'd assume its just comments

**Comment by rany2** [comment]
@networkException In some instances, crbug.com is printed to stderr to warn user of some bug.

**Comment by PF4Public** [comment]
They also appear on internal pages:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/836679f8-f376-452a-a012-073d80e746cb)
Thus I suspected they might be lurking somewhere deeper?

**Comment by PF4Public** [comment]
They appear in comments, so probably not a big deal.
