### ISSUE TITLE
Ungoogled-chromium Flatpak has no Vulkan

### ISSUE THREAD

**Issue by Flashwalker** [ungoogled-software/ungoogled-chromium#2346]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

112

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Ungoogled-chromium Flatpak has no Vulkan enabled

### How to Reproduce?

1. 
```
flatpak run --env=__NV_PRIME_RENDER_OFFLOAD=1 --env=__GLX_VENDOR_LIBRARY_NAME=nvidia --env=PW_PRIME_RENDER_OFFLOAD=1 --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u \
    --enable-gpu-rasterization \
    --enable-accelerated-2d-canvas \
    --enable-accelerated-video-decode \
    --ignore-gpu-blocklist \
    --enable-zero-copy \
    --enable-unsafe-webgpu \
    --enable-features=UseSkiaRenderer,Vulkan \
    --disable-quic \
    --extension-mime-request-handling=always-prompt-for-install \
    --hide-sidepanel-button \
    --enable-smooth-scrolling \
    --tab-hover-cards=tooltip \
    --enable-features=CanvasOopRasterization,EnableDrDc,RawDraw \
    --custom-ntp=chrome://gpu \
@@
```

### Actual behaviour

Vulkan Disabled

### Expected behaviour

Vulkan Enabled

### Relevant log output

```sh
F: Not sharing "/usr/lib/x86_64-linux-gnu/gtk-3.0/modules" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/lib/x86_64-linux-gnu/gtk-2.0/modules" with sandbox: Path "/usr" is reserved by Flatpak
Gtk-Message: 17:39:01.032: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:39:01.033: Failed to load module "appmenu-gtk-module"
Gtk-Message: 17:39:01.594: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:39:01.594: Failed to load module "appmenu-gtk-module"
[2:2:0509/173901.747329:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
Warning: vkCreateInstance: Found no drivers!
Error: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:416)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:302)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:232)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:491)

Error: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:53)
```

### Additional context

![image](https://github.com/flathub/org.chromium.Chromium/assets/2188215/b7baaffb-45db-4534-a956-4e26121845f7)

`--enable-features=VaapiVideoDecoder` - doesn't helps
`--disable-features=UseChromeOSDirectVideoDecoder` -  doesn't helps
`--use-gl=egl` - disables gpu acceleration at all

`inxi -G`:
```
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia
    v: 525.105.17
  Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 22.3.5
```

Flatpak GL installaed:
Mesa org.freedesktop.Platform.GL.default 21.3.9	21.08 flathub system
Mesa org.freedesktop.Platform.GL.default 23.0.2	22.08 flathub system
Mesa (Extra) org.freedesktop.Platform.GL.default 23.0.2	22.08-extra flathub system
nvidia-525-85-05 org.freedesktop.Platform.GL.nvidia-525-85-05 1.4 flathub system

(Ungoogled-chromium Not Flatpak 100 - Vulkan Enabled)

**Comment by Flashwalker** [comment]
https://github.com/flathub/org.chromium.Chromium/issues/169

**Comment by Bixilon** [comment]
Exactly the same issue here on 3 devices (nvidia, intel, amd). I removed the opengl flag and only vulkan is missing. Not sure what it does performance wise.

**Comment by PF4Public** [comment]
Please file this issue with the Flatpak repo: [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium)

**Comment by Flashwalker** [comment]
https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/110
