### ISSUE TITLE
Add Customize Button to Allow Changing of Themes and Backgrounds on newtab

### ISSUE THREAD

**Issue by witherslayer0** [ungoogled-software/ungoogled-chromium#2353]
### Description

Adding a button on the newtab page allowing users to change the theme and background.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I have moved from using chromium and noticed that I am not able to use the "Customize Chromium" button. In chromium when the search engine is set to google the "Customize Chromium" button is visible on the newtab page (chrome://newtab) which allows you to change the theme from several default chromium themes or to make your own. It also allows you to set a background image.

In chromium
![chromium_newtab](https://github.com/ungoogled-software/ungoogled-chromium/assets/71404229/f936131f-f838-4166-ad98-5acfde537699)

In ungoogled chromium
![ungoogled_chromium_newtab](https://github.com/ungoogled-software/ungoogled-chromium/assets/71404229/eff555b9-e55a-4203-8305-56f322097fd6)

### Possible solutions

It may be possible to add the button from chromium.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
