### ISSUE TITLE
Disable webgl

### ISSUE THREAD

**Issue by calhix** [ungoogled-software/ungoogled-chromium#2354]
### Description

I would like the ability to disable webgl

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Webgl is a potential security risk. I know that Bromite has this disabled by default and I understand that making this browser privacy friendly is secondary. It would be nice if there were at least a flag to disable.

### Possible solutions

Create flag to disable webgl

**Comment by networkException** [comment]
Have you tried `--disable-webgl`?
