### ISSUE TITLE
Extension login error (purevpn) - blocked URL - accessed via chrome_proxy (domain substitution?)

### ISSUE THREAD

**Issue by id2hub** [ungoogled-software/ungoogled-chromium#2360]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

113.0.5672.93

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

login url access blocked within Extensions via chrome_proxy

### How to Reproduce?

Install Chromium Webstore
Install latest PureVPN extension
Try to login within extension

### Actual behaviour

PureVPN login error:

{
  "error" : "invalid_request",
  "error_description" : "Invalid redirect_uri https://bfidboloedlamgdmenmlbipfnccokknp.ch40m1umapp.qjz9zk/oauth2",
  "error_reason" : "invalid_redirect_uri"
}

### Expected behaviour

Is there a way we can whitelist Domain substation per URL/ per extension?

Or this could related to different security issue?

### Additional context

If I call the URL in question directly on the browser following error occurs:
bfidboloedlamgdmenmlbipfnccokknp.ch40m1umapp.qjz9zk is blocked

This could be due to domain substitution

**Comment by rany2** [comment]
> I initially thought all extensions would be working when installed via Chromium Store or is only that does not have google integration, which makes it a considerable subset of extensions that would work?

Those that have Google integration might work fine, however in the case of that PureVPN extension it appears that it fails if contacting the Google API fails. It just depends how the extension handles such a failure, it depends. :tm: 

> Also is there way to bypass/whitelist domain substitutions for select urls/extensions?

It is not possible.

**Comment by id2hub** [comment]
I understand why it is not working but I think it is paramount to use a VPN extension to use the browser in a secured way and I believe Ungoggled need to facilitate use of a VPN with the browser, especially when security is at the helm of it.

Thanks

**Comment by rany2** [comment]
If the VPN extension isn't working without Google integration, then I'd use another VPN ASAP. It's not a bad look for Ungoogled, rather it's a very bad look for that VPN service and I'd suggest you look for another service like Mullvad or just use Tor.

**Comment by id2hub** [comment]
Thanks, any Chrome extension you cold suggest with very performance, only want to apply for this browser not at the computer level, I'm ok if it is reasonably priced.

**Comment by rany2** [comment]
Mullvad is decent and has a good reputation among the privacy crowd: https://mullvad.net/en/download/browser/extension

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
