### ISSUE TITLE
DRM video not working

### ISSUE THREAD

**Issue by popis1** [ungoogled-software/ungoogled-chromium#2361]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Wersja 115.0.5790.0 (Build) (64-bitowa)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

DRM Video not working

### How to Reproduce?

Go to https://play.hbomax.com/
Choose any film to watch
You should see like this 
![obraz](https://github.com/ungoogled-software/ungoogled-chromium/assets/78849816/784b45b8-456d-46b2-bc95-0ef7e4bca6f6)

### Actual behaviour

Not working DRM player

### Expected behaviour

Should DRM content work

**Comment by networkException** [comment]
We don't provide support for non stable versions. Please also note that DRM is error prone and largely won't be tested by maintainers. Refer to the https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq for a best effort guide

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
