### ISSUE TITLE
Adding Live Caption to Accessibility

### ISSUE THREAD

**Issue by Sunspark-007** [ungoogled-software/ungoogled-chromium#2363]
### Description

Bundling the live caption feature from Chrome which does not need a network connection to work in order to provide subtitles for audio and video

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Live Caption in Settings>Accessibility>Live Caption is an amazing feature for all forms of media that has an audio track and don't come with subtitles. This feature helps a great deal with accessibility for those with hearing-related issues. Right now, for those who need or wish to use it, they need to keep Chrome and ungoogled-chromium installed side-by-side and switch over to Chrome whenever live caption is needed. Having it bundled would reduce the dependency of always having regular Chrome present for this feature.

### Possible solutions

Given that live caption works offline and doesn't require a network connection to work (not sure if the dataset is bundled, or if it requires an initial download of the language corpus, but if so, it is only done once) I figure since it doesn't transmit data back to Google, just have this feature available if it is accessible to use.

### Alternatives

Before it got bundled, I used to use a smartphone with cloud-based speech recognition on. This required the PC to be broadcasting audio over speakers. Live caption has the ability to work if the audio is muted which is good for non-private environments.

**Comment by luphoria** [comment]
It's likely proprietary which is why it isn't included. But a note to add here is that there are little fragments in UI which ask if you would like to enable Live Caption (which doesn't work) - this should be addressed:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/60309933/c8cd2663-9c32-47d7-8dd9-d4d7dc310ee9)

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
