### ISSUE TITLE
 CryptoTokenExtension 0.9.74  

### ISSUE THREAD

**Issue by lilianjaaneman** [ungoogled-software/ungoogled-chromium#2378]
Hello Mibs!
Please teach me how to remove this Cryptocurrency Extension from the browser. I've tried everything I know, and nothing works.

[ CryptoTokenExtension
0.9.74
CryptoToken Component Extension
ID: kmendfapggjehodndflmmgagdbamhnfd
Inspect views background page (Inactive)  ] 

Version 90.0.4430.212  built on Debian 10.9, running on Debian 10.13 (64-bit)

Thank u

**Comment by PF4Public** [comment]
What does it have to do with ungoogled-chromium?
