### ISSUE TITLE
VA-API support Wayland

### ISSUE THREAD

**Issue by pflanzenandi** [ungoogled-software/ungoogled-chromium#2381]
### Description

Implement Chromium patch to enable VA-API video decoding on the Ozone Wayland backend

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Not a coder.

### Possible solutions

[https://aur.archlinux.org/packages/chromium-wayland-vaapi](https://aur.archlinux.org/packages/chromium-wayland-vaapi)

**Comment by rany2** [comment]
Already available if you use the Flatpak variant.

**Comment by pflanzenandi** [comment]
> Already available if you use the Flatpak variant.

I managed to activate VA-PI drivers. But practically they aren't used. Do you have an idea how to solve this? I used following config variables:

```
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder
--disable-features=UseChromeOSDirectVideoDecoder
```


![Screenshot-20230612085659-844x590](https://github.com/ungoogled-software/ungoogled-chromium/assets/60046516/4f6d3b8b-cec8-4561-9454-0079db4dcec5)

**Comment by jstkdng** [comment]
It seems the latest `chromium-wayland-vaapi` requires patched wayland libraries.

https://aur.archlinux.org/packages/wayland-chromium

**Comment by pflanzenandi** [comment]
Should I close?
