### ISSUE TITLE
Keychain Mac OS Bug

### ISSUE THREAD

**Issue by george-emerald** [ungoogled-software/ungoogled-chromium#2382]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

114.0.5735.106-1.1,1686570558

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Ungoogled-chromium stops working and needs to be quit and re-launched.

### How to Reproduce?

1. Use ungoogled-chromium.
2. It randomly stops loading websites.
3. All the new tab logos are replaced by a folder with a pixelated sad emoji.

### Actual behaviour

Ungoogled-chromium randomly stops working and needs to be quit and re-opened. When I re-open it, a System Settings window says it's trying to access information in my keychain and asks for my password and then it starts working again.

### Expected behaviour

Ungoogled-chromium never stops loading websites.

### Relevant log output

```sh
I'm sorry but I can't find how to produce/access them.
```

### Additional context

I suspect it happens every time I update as Little Snitch would also tell me the signature of the binary changed and I had to set it to disable identity check for Chromium. It was installed from the homebrew cask and is updated automatically through it.

**Comment by networkException** [comment]
I assume pulling the rug from under the running process in an update breaks for ungoogled-chromium. Is disabling automatic updates an option for you?

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
