### ISSUE TITLE
How do I get the browser to support shareArrayBuffer?

### ISSUE THREAD

**Issue by missBlueWhite** [ungoogled-software/ungoogled-chromium#2388]
### Description

How do I get the browser to support shareArrayBuffer?

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

1，i want use http
2，i do not want use https
2，when i use http ， how do I get the browser to support shareArrayBuffer?

### Possible solutions

i  do not konw

**Comment by PF4Public** [comment]
Please try adding more details or rephrasing your message, it is very hard to understand what you want.

**Comment by networkException** [comment]
Allowing SharedArrayBuffer outside of secure contexts (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) is a very bad idea and definitely very much out of scope for this project.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
