### ISSUE TITLE
VAAPI support for AMD Mesa driver 

### ISSUE THREAD

**Issue by Fei1Yang** [ungoogled-software/ungoogled-chromium#2390]
### Description

Add support for AMD Mesa driver in Chromium's VAAPI implementation

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

AMD Mesa driver currently can't use VaapiVideoDecoder due to https://crbug.com/974438, and the legacy VDAVideoDecoder doesn't work on Wayland even when running under XWayland mode.

### Possible solutions

This patch should be able to fix this issue, and its author seems positive on integration of downstream Chromium distributions: https://gist.github.com/thubble/235806c4c64b159653de879173d24d9f

**Comment by PF4Public** [comment]
This does not alight with the project goals and cannot be pulled into this repository, but might be a fit for a platform repo though.

**Comment by jstkdng** [comment]
That patch looks like it's going to break as soon as there's a new chromium release.
