### ISSUE TITLE
ld.lld: error: undefined symbol: referrer_sanitizer::sanitize_referrer(...)

### ISSUE THREAD

**Issue by iskunk** [ungoogled-software/ungoogled-chromium#2393]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

114.0.5735.133-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Undefined-symbol link error in the build

### How to Reproduce?

I applied the patches to the Debian Chromium tree using [my framework](https://github.com/ungoogled-software/contrib/issues/15), and built as usual on an Ubuntu 23.04 amd64 system.

### Actual behaviour

```
[56262/56272] LINK ./content_shell
FAILED: content_shell 
"python3" "../../build/toolchain/gcc_link_wrapper.py" --output="./content_shell" -- clang++ -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -m64 -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -pie -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--stats -o "./content_shell" -Wl,--start-group @"./content_shell.rsp" ./libtest_trace_processor.so -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -ljsoncpp -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -latk-1.0 -latk-bridge-2.0 -ljpeg -lpng16 -lfreetype -ldouble-conversion -levent -lresolv -lgio-2.0 -lbrotlidec -lz -lopus -lopenh264 -lm -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lgbm -lEGL -ldrm -lexpat -lwebpdemux -lwebpmux -lwebp -lfontconfig -lxcb -lxkbcommon -lXi -lpci -l:libffi_pic.a -lXNVCtrl -ldbus-1 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lre2 -lasound -lpulse -lFLAC -lsnappy -latspi -lxml2 -lxslt -lwoff2dec -lcups -lminizip -lxshmfence 
ld.lld: error: undefined symbol: referrer_sanitizer::sanitize_referrer(GURL const&, GURL const&, network::mojom::ReferrerPolicy const&, bool)
>>> referenced by dedicated_or_shared_worker_fetch_context_impl.cc
>>>               obj/third_party/blink/renderer/platform/loader/loader/dedicated_or_shared_worker_fetch_context_impl.o:(blink::DedicatedOrSharedWorkerFetchContextImpl::WillSendRequest(blink::WebURLRequest&))
>>> referenced by navigation_request.cc
>>>               obj/content/browser/browser/navigation_request.o:(content::NavigationRequest::NavigationRequest(content::FrameTreeNode*, mojo::StructPtr<blink::mojom::CommonNavigationParams>, mojo::StructPtr<blink::mojom::BeginNavigationParams>, mojo::StructPtr<blink::mojom::CommitNavigationParams>, bool, bool, bool, content::FrameNavigationEntry const*, content::NavigationEntryImpl*, std::unique_ptr<content::NavigationUIData, std::default_delete<content::NavigationUIData>>, scoped_refptr<network::SharedURLLoaderFactory>, mojo::PendingAssociatedRemote<content::mojom::NavigationClient>, scoped_refptr<content::PrefetchedSignedExchangeCache>, base::WeakPtr<content::RenderFrameHostImpl>, int, bool, bool, bool, mojo::PendingReceiver<content::mojom::NavigationRendererCancellationListener>, absl::optional<std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t>>>))
>>> referenced by render_frame_impl.cc
>>>               renderer/render_frame_impl.o:(content::RenderFrameImpl::WillSendRequestInternal(blink::WebURLRequest&, bool, ui::PageTransition, base::StrongAlias<blink::ForRedirectTag, bool>)) in archive obj/content/renderer/librenderer.a
>>> referenced 1 more times

ld.lld: error: undefined symbol: referrer_sanitizer::sanitize_referrer(GURL const&, GURL const&, net::ReferrerPolicy const&, bool)
>>> referenced by network_service_network_delegate.cc
>>>               network_service/network_service_network_delegate.o:(network::NetworkServiceNetworkDelegate::MaybeTruncateReferrer(net::URLRequest*, GURL const&)) in archive obj/services/network/libnetwork_service.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected behaviour

The ungoogled-chromium build has always worked for me before, if/when regular Chromium is able to build.

**Comment by iskunk** [comment]
@implicitfield: I've confirmed that the patch, applied prior to starting a build on the same source tree that failed earlier, allows the build to complete successfully.

**Comment by PF4Public** [comment]
@iskunk Which gn flags you use for building?

**Comment by iskunk** [comment]
I append the u-c flags (from `flags.gn`) to the ones used by Debian. Beyond that, I set `use_thin_lto=true` and unset `concurrent_links`. Here is the relevant bit from my build log:

`gn gen out/Release --args="clang_use_chrome_plugins=false host_toolchain=\"//build/toolchain/linux/unbundle:default\" custom_toolchain=\"//build/toolchain/linux/unbundle:default\" host_cpu=\"x64\" use_vaapi=true is_debug=false use_goma=false use_sysroot=false use_libjpeg_turbo=true use_custom_libcxx=false use_gnome_keyring=false use_unofficial_version_number=false enable_vr=false enable_nacl=false enable_swiftshader=false dawn_use_swiftshader=false build_dawn_tests=false enable_reading_list=false enable_iterator_debugging=false enable_hangout_services_extension=false angle_has_histograms=false build_angle_perftests=false treat_warnings_as_errors=false use_qt=false is_cfi=false use_thin_lto=true chrome_pgo_phase=0  use_gio=true is_official_build=true symbol_level=0 use_pulseaudio=true link_pulseaudio=true rtc_use_pipewire=true icu_use_data_file=true enable_widevine=true v8_enable_backtrace=true use_system_zlib=true use_system_lcms2=true use_system_libjpeg=true use_system_libpng=true use_system_freetype=true use_system_libopenjpeg2=true  proprietary_codecs=true ffmpeg_branding=\"Chrome\" disable_fieldtrial_testing_config=true  build_with_tflite_lib=false chrome_pgo_phase=0 clang_use_chrome_plugins=false disable_fieldtrial_testing_config=true enable_hangout_services_extension=false enable_mdns=false enable_mse_mpeg2ts_stream_parser=true enable_nacl=false enable_reading_list=false enable_remoting=false enable_reporting=false enable_service_discovery=false enable_widevine=true exclude_unwind_tables=true google_api_key=\"\" google_default_client_id=\"\" google_default_client_secret=\"\" safe_browsing_mode=0 treat_warnings_as_errors=false use_official_google_api_keys=false use_unofficial_version_number=false "`

**Comment by PF4Public** [comment]
I believe that due to not defining `use_ozone` and `ozone_auto_platforms` explicitly, they both get defined to be true by default, which [according to docs](https://chromium.googlesource.com/chromium/src/+show/master/docs/ozone_overview.md#:~:text=If%20%60ozone_auto_platforms%60%20is,by%20default.) implies `ozone_platform=headless`, which in turn must be pulling in all the `headless` stuff including `headless_testing` and `content_shell_app` along with `content_shell_lib`. This might be the reason why others didn't catch this.

**Comment by iskunk** [comment]
FWIW, adding `ozone_platform_headless=false` and leaving out the patch still gets me the link error. But if there is a different flag tweak you have in mind, I'll be happy to give it a try.

**Comment by PF4Public** [comment]
@iskunk Please try `use_ozone=true ozone_auto_platforms=false ozone_platform_x11=true ozone_platform_wayland=false ozone_platform=x11` or `wayland` if you use the latter instead. There might be need to add and escape quotes: `\"x11\"` . 

This could limit the resulting binary to a single platform, but I'm not sure about that, didn't test. And if this assumption is true, we should definitely patch this thing for those who build for both platforms.

**Comment by iskunk** [comment]
No dice, unfortunately. I use X11, so I added
```
defines+=use_ozone=true \
         ozone_auto_platforms=false \
         ozone_platform_x11=true \
         ozone_platform_wayland=false \
         ozone_platform=\"x11\"
```
(no complaints from gn), but I still get
```
[55935/55936] LINK ./content_shell
FAILED: content_shell 
"python3" "../../build/toolchain/gcc_link_wrapper.py" --output="./content_shell" -- clang++ -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -m64 -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O0 -pie -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--stats -o "./content_shell" -Wl,--start-group @"./content_shell.rsp" ./libtest_trace_processor.so -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -ljsoncpp -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -latk-1.0 -latk-bridge-2.0 -ljpeg -lpng16 -lz -lfreetype -ldouble-conversion -levent -lresolv -lgio-2.0 -lbrotlidec -lopus -lopenh264 -lm -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender -lXrandr -lXtst -lgbm -lEGL -ldrm -lexpat -lwebpdemux -lwebpmux -lwebp -lfontconfig -lxcb -lxkbcommon -lXi -lpci -lXNVCtrl -lre2 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lasound -lpulse -lFLAC -lsnappy -ldbus-1 -latspi -lxml2 -lxslt -lwoff2dec -lcups -lminizip -lxshmfence 
ld.lld: error: undefined symbol: referrer_sanitizer::sanitize_referrer(GURL const&, GURL const&, network::mojom::ReferrerPolicy const&, bool)
>>> referenced by dedicated_or_shared_worker_fetch_context_impl.cc
>>>               thinlto-cache/llvmcache-2932CCA7805107002887657388AEE32FAA2904C4:(blink::DedicatedOrSharedWorkerFetchContextImpl::WillSendRequest(blink::WebURLRequest&))
>>> referenced by navigation_request.cc
>>>               thinlto-cache/llvmcache-2DBB311C725E3EE21E6CD28C23191266DABF6FA5:(content::NavigationRequest::NavigationRequest(content::FrameTreeNode*, mojo::StructPtr<blink::mojom::CommonNavigationParams>, mojo::StructPtr<blink::mojom::BeginNavigationParams>, mojo::StructPtr<blink::mojom::CommitNavigationParams>, bool, bool, bool, content::FrameNavigationEntry const*, content::NavigationEntryImpl*, std::unique_ptr<content::NavigationUIData, std::default_delete<content::NavigationUIData> >, scoped_refptr<network::SharedURLLoaderFactory>, mojo::PendingAssociatedRemote<content::mojom::NavigationClient>, scoped_refptr<content::PrefetchedSignedExchangeCache>, base::WeakPtr<content::RenderFrameHostImpl>, int, bool, bool, bool, mojo::PendingReceiver<content::mojom::NavigationRendererCancellationListener>, absl::optional<std::__cxx11::basic_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t> > >))
>>> referenced by render_frame_impl.cc
>>>               thinlto-cache/llvmcache-785EC5A048574DB2A3AE515BD840FE9B1C5896FD:(content::RenderFrameImpl::WillSendRequestInternal(blink::WebURLRequest&, bool, ui::PageTransition, base::StrongAlias<blink::ForRedirectTag, bool>))
>>> referenced 1 more times

ld.lld: error: undefined symbol: referrer_sanitizer::sanitize_referrer(GURL const&, GURL const&, net::ReferrerPolicy const&, bool)
>>> referenced by network_service_network_delegate.cc
>>>               thinlto-cache/llvmcache-B75843E84E4200BF057F65596035DE2FB09AEFF2:(network::NetworkServiceNetworkDelegate::MaybeTruncateReferrer(net::URLRequest*, GURL const&))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Hope there's a way of finagling the flags in a cross-platform/environment way. I can try further flag combinations, but will need more turnaround time due to other activities on my end.

**Comment by PF4Public** [comment]
@iskunk Please grep your logs for `dedicated_or_shared_worker_fetch_context_impl.o`. What was the full command to build it?

**Comment by iskunk** [comment]
Unfortunately, all I get is
```
$ grep -n dedicated_or_shared_worker_fetch_context_impl ../build-uc3.out 
47518:[39708/55936] CXX obj/third_party/blink/renderer/platform/loader/loader/dedicated_or_shared_worker_fetch_context_impl.o
71755:>>> referenced by dedicated_or_shared_worker_fetch_context_impl.cc
```

Would the contents of `out/Release/obj/content/shell/content_shell.ninja`, or some other `.ninja` file, be helpful?

> Do you have any other targets except for `chrome` for ninja invocation?

The Debian build runs with these ninja targets:
```
ninja -C out/Release chrome chrome_sandbox content_shell chromedriver
```
They package `content_shell` as `chromium-shell` in a `chromium-shell` package. They describe the latter thusly: "This package provides a minimal version of the chromium user interface (the content shell)."

**Comment by PF4Public** [comment]
Well, that would explain, why `content_shell` target is built! Because it was asked for! And since no one else had built it, we didn't catch this failure earlier. 🤷
