### ISSUE TITLE
Ruffle failing in the latest version

### ISSUE THREAD

**Issue by pikakid98** [ungoogled-software/ungoogled-chromium#2394]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

v114.0.5735.134

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Ruffle is broken in the latest Ungoogled Chromium

### How to Reproduce?

[Ruffle](https://ruffle.rs/) is broken in the latest version. I've reported this to Ruffle too. I've tested on an older version and it works perfectly. However, the latest version constantly gives me an error 
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/12392651/f46da28e-5884-4ded-a700-7ba3dddd79ec)
I'm not sure who's at fault here but something is off.

- I've tried enabling WebGL
- I've re-enabled the Angle renderer
- I've used hardware acceleration

nothing seems to work

### Actual behaviour

"WebAssembly is not defined"

### Expected behaviour

I get to play Flash games

### Additional context

So. I DID try using a seperate install of the latest version with `--user-data-dir` and it produced the same error. I misread the tickbox

**Comment by pikakid98** [comment]
wait.. never mind.. sorry.. I forgot to enable Javascript JIT.... if you would, please delete my issue

**Comment by PF4Public** [comment]
Why delete? This should provide a quick solution for anyone getting into the same situation as you.

**Comment by pikakid98** [comment]
fair point

**Comment by PF4Public** [comment]
@pikakid98 BTW, you do not seem to use https://ungoogled-software.github.io/ungoogled-chromium-binaries/ contrary to your statement. We do not ship JavaScript JIT in those, so this issue couldn't have happened should you actually use ungoogled-chromium from https://ungoogled-software.github.io/ungoogled-chromium-binaries/. We cannot provide support if you obtain ungoogled-chromium any other way.

**Comment by pikakid98** [comment]
sorry for the delays but I use chrlauncher so it appears I use builds from [chromium.woolys.com](https://chromium.woolyss.com/). not sure if this is recommended at all

**Comment by pikakid98** [comment]
ok. I just went back to the official UGC builds and now all of the issues I was having before have been fixed.. so.. note to chrlauncher users... don't use chrlauncher unless you can either figure out how to autodownload THESE builds.. or.. find/make a new one.. or alter the existing chrlauncher code
