### ISSUE TITLE
libicui18n.so.72: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jab416171** [ungoogled-software/ungoogled-chromium#2401]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

114.0.5735.133-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory

### How to Reproduce?

Install 114.0.5735.133-1 on archlinux
Launch chromium
Observe error in console

### Actual behaviour

chromium fails to launch due to the missing library

### Expected behaviour

chromium works as expected

### Additional context

I see #746 is a similar issue.

**Comment by jab416171** [comment]
I see the github build is still running, I will test again once that's finished
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/5402551597

**Comment by jab416171** [comment]
This is still broken with the same error on 114.0.5735.198-1

**Comment by networkException** [comment]
Is that the Actions or the OBS build?

**Comment by jab416171** [comment]
I'm not sure what the difference is, but the current version on the AUR is broken (114.0.5735.198-1)
https://aur.archlinux.org/packages/ungoogled-chromium-bin

**Comment by tenpast** [comment]
This seems to happen every so often when Lib Icu is upgraded. The browser needs to be rebuilt with Lib Icu 73. Same problem for me, running Arch, with ungoogled-chromium-bin 114.0.5735.198-1.

**Comment by 31337** [comment]
Is there a way to somehow synchronize the build process with the arch system updates, like automatically checking which libicu (and others) is needed and then rebuild ungoogled-chromium-bin / triggering a rebuild as soon as a new libicu is released via arch updates?

**Comment by bbaster** [comment]
A version with up-to-date `icu` is currently building (see line 30 in the "Install dependencies" section: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/5414664373/jobs/9859177190)

What @31337 is asking for could be possibly done with a Bash script ran every hour which would search the output of `checkupdates` (provided by the `pacman-contrib` package) for Chromium's dependencies and trigger a rebuild if needed

**Comment by kohane27** [comment]
is there a fix for this please? I can't even open chromium now... thanks guys.

**Comment by binarynoise** [comment]
Yes, update is just done building.

**Comment by kohane27** [comment]
@binarynoise thank you for the update! I just ran `paru -S ungoogled-chromium-bin` and it is working fine now. Thank you and have a good day!

**Comment by rubyando** [comment]
> @binarynoise thank you for the update! I just ran `paru -S ungoogled-chromium-bin` and it is working fine now. Thank you and have a good day!

I did the paru command as well as updating with pacman - and it still crashes with so.72 error. How do I fix this?

**Comment by kohane27** [comment]
@rubyando What is your `ungoogled-chromium-bin` version?

My working version:

```
➜ chromium --version
Chromium 114.0.5735.198 Arch Linux
```

**Comment by rubyando** [comment]
> @rubyando What is your `ungoogled-chromium-bin` version?
> 
> My working version:
> 
> ```
> ➜ chromium --version
> Chromium 114.0.5735.198 Arch Linux
> ```

My current that works is 114.0.5735.198

**Comment by jab416171** [comment]
> > @binarynoise thank you for the update! I just ran `paru -S ungoogled-chromium-bin` and it is working fine now. Thank you and have a good day!
> 
> I did the paru command as well as updating with pacman - and it still crashes with so.72 error. How do I fix this?

Just to confirm you've done a pacman -Syu and rebooted? what's your version of icu? it should be 73.2-1

**Comment by rubyando** [comment]
> > > @binarynoise thank you for the update! I just ran `paru -S ungoogled-chromium-bin` and it is working fine now. Thank you and have a good day!
> > 
> > 
> > I did the paru command as well as updating with pacman - and it still crashes with so.72 error. How do I fix this?
> 
> Just to confirm you've done a pacman -Syu and rebooted? what's your version of icu? it should be at least 73.2-1

Yea I did reboot couple of times but have no idea how to check icu version. I guess since it works on old version I shouldn't touch anything

**Comment by jab416171** [comment]
pacman -Qi icu

**Comment by rubyando** [comment]
> pacman -Qi icu

73.2-1

**Comment by jab416171** [comment]
I would suggest opening a new github issue

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-archlinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux)

**Comment by tenpast** [comment]
This issue is still a problem every time a new version of libicu is released. Current error on Archlinux:

`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory`

**Comment by Sorrydough** [comment]
broken again here

**Comment by erogers88** [comment]
Same error here on Artix (Arch) Linux.

ungoogled-chromium version 119.0.6045.105-1
icu version 74.2-1

**Comment by networkException** [comment]
You are using an outdated and vulnerable build.

Arch based distributions don't have any concept to prevent runtime dependencies from breaking except rebuilding everything. This is handled by each distribution by their own build farm. ungoogled-chromium builds are provided voluntarily, builds take at least 24 hours on GitHub Actions and we do not have the capacity to match the releases of Arch derivatives.

**Comment by erogers88** [comment]
Ah thanks, I see - my ungoogled-chromium was outdated. I fixed it by reinstalling it from the AUR. 

I didn't realize it wasn't a native package and it wasn't updating along with the other dependencies.

You can see all AUR-installed packages with `pacman -Qem`.

**Comment by RealYukiSan** [comment]
Is the libicu library loaded using a dynamic linker? If I understand correctly, the issue is a version mismatch because the dependency was updated. Could this be solved by creating a symbolic link to the updated library with the persistent name?
