### ISSUE TITLE
Enable browser size fingerprinting protection in Ungoogled-Chromium

### ISSUE THREAD

**Issue by MikeNavy** [ungoogled-software/ungoogled-chromium#2405]
### Description

Round the browser size to multiples of 50 or 100

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hi,
Firefox has a protection against browser size fingerprinting: it displays browsers sizes as multiples of 100.
This limits the possibility of browser size fingerprinting, since there are more users with the same browser size.
Some fingerprinting protections are still enabled in ungoogled-chromium in "chrome://flags".
It would be nice to add a browser size fingerprinting protection, which would display to websites dimensions (width and height) in multiples of 50 or 100 pixels.
Example:
My browser size can be checked at https://browsersize.com/. The results are:
- Screen size: 1428 x 803
- Browser window size: 1429 x 656

(I have a laptop with 17.25 inches screen, with 1920x1080 resolution, and a display density of 129 dpi; with this, ungoogled-chromium, as chromium would do, selects a screen size of 1428x803).

When I use EFF "cover your tracks", the resulting fingerprinting is high:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62835567/916ec6ed-e7dd-4ad2-bff1-37879b85c01a)

Displaying rounded screen size values, such as 1400x800 instead of 1428x803 would strongly increase the number of computers with the same screen size, and would decrease the number of bits of identifying information.

### Possible solutions

Use Firefox technique of protection against browser size fingerprinting.

**Comment by PF4Public** [comment]
If you're on Gentoo you can try uazo's patches. Otherwise you could apply those patches manually while building ungoogled-chromium. uazo randomizes the screensize a little instead of snapping to close 100th. 

For example my screen is detected as 

> Current:
> Browser window size: 1993 x 1043
> Screen size: 1997 x 1045

Should I reopen the tab it becomes

> Current:
> Browser window size: 1950 x 1020
> Screen size: 1971 x 1031

**Comment by MikeNavy** [comment]
Hi,

I use ungoogled-chromium flatpak on Linux Mint.

And I can't build ungoogled-chromium.

I don't know uazo's patches, but it would be great to have them implemented in ungoogled-chromium, at least the screen size randomising.

Regards,

MN

**Comment by PF4Public** [comment]
Unfortunately we cannot pull uazo's Bromite patches in ungoogled-chromium for the time being.

**Comment by MikeNavy** [comment]
Hi,

I don't really understand your licensing difficulties: yes, ungoogled-chromium has a BSD like license, while bromite and uazo's patches are licensed under GPL V3; **but ungoogled-chromium still incorporates some features from bromite**:
```
Borrowed Features
In addition to the features introduced by ungoogled-chromium, ungoogled-chromium selectively borrows many
features from the following projects (in approximate order of significance):
[...]
[Bromite](https://github.com/bromite/bromite)
[...]
```
Meanwhile, I have found a workaround. I launch ungoogled-chromium with the following options in the command line:
`--high-dpi-support=1 --force-device-scale-factor=1.2 `
The first option disables the default screen size behavior and forces ungoogled-chromium to use the full screen size; the second option forces a scale factor of 1.2. 
With that:
- width = 1920/1.2 = 1600
- height = 1080/1.2 = 900.

Tabs and bookmarks police size is acceptable (large enough to be readable).
And I finely tune the default web pages zoom with "Zoom page WE" extension, and the web pages font size with ungoogled-chromium settings.

Fingerprinting tracking is strongly reduced:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62835567/de12f8a5-1c81-4438-ad68-4524d591c556)
Now, my screen size is 1 among 51.4 instead of 1 among 15258!

Regards,

MN

**Comment by PF4Public** [comment]
> I don't really understand your licensing difficulties

You may have a look [there](https://github.com/ungoogled-software/ungoogled-chromium/pull/1845) if you will. I'm not repeating it all here.

> Fingerprinting tracking is strongly reduced

I'm glad you've found acceptable solution for your issue, given that other possible solution is at the moment unrealistic, I'll close the issue.
