### ISSUE TITLE
Flag collide with enable_mse_mpeg2ts_stream_parser, proprietary_codecs and ffmpeg_branding

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2419]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

106.0.5249.119-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Flag collide with enable_mse_mpeg2ts_stream_parser, proprietary_codecs and ffmpeg_branding

### How to Reproduce?

Set `proprietary_codecs` to `true` in `flags.gn` and then build.

### Actual behaviour

If i leave `enable_mse_mpeg2ts_stream_parser` on `true` in `flags.gn`, then the build fails, because it needs `proprietary_codecs` set to `true` too. However, i cannot set it, because `ffmpeg_branding` is set to `"Chromium"`.
I can set `enable_mse_mpeg2ts_stream_parser` to `false` and then it builds, but then i barely can play any videos.

### Expected behaviour

Is it possible to setup this somehow, without setting `ffmpeg_branding` to `"Chrome"`? Also, will it solve the problem, if i set `use_system_ffmpeg` to `true`? I would like to use the system's FFMPEG anyway.

### Relevant log output

```sh
Not needed.
```

**Comment by PF4Public** [comment]
Please try latest version. 106 is too old.

**Comment by TCH68k** [comment]
I already planning to do that, but i'd like to know if i can turn both `use_system_ffmpeg` and `proprietary_codecs` on and still leave `ffmpeg_branding` as `"Chromium"`.

**Comment by PF4Public** [comment]
> turn both `use_system_ffmpeg` and `proprietary_codecs`

Yes



> leave `ffmpeg_branding` as `"Chromium"`

Not sure about that. It is not a big deal to put Chrome there though.

**Comment by TCH68k** [comment]
Not a big deal, if it's just a label, yes. But is it just a label? Will not it affect my profile being Chromium? Will not it bring other changes, like disabling some codecs, or enabling DRM?

If it's really just a label, then i will set it, better safe than sorry.

**Comment by TCH68k** [comment]
Also, is there a way to prevent the building requiring at least 80 GB (!) free disk space?

**Comment by PF4Public** [comment]
> But is it just a label? Will not it affect my profile being Chromium? Will not it bring other changes, like disabling some codecs, or enabling DRM?

Do your own research to be certain! For example `proprietary_codecs` tells the browser that it is OK to use codecs _subject to licensing_, even though it might be actually using _free implementation_ from ffmpeg.



> Also, is there a way to prevent the building requiring at least 80 GB (!) free disk space?

I cannot confirm this number. You should verify this information, it might be wrong.

**Comment by TCH68k** [comment]
> Do your own research to be certain!

I don't even know where and how to start. That's why i ask the people who ought to know these answers...

> I cannot confirm this number. You should verify this information, it might be wrong.

I confirm it for you. When i built Ungoogled Chromium 106, the build directory went over 75 GB. It did not reach 80 GB, but almost. I had to restart twice or thrice, because i've ran out of disk space during compiling.

**Comment by PF4Public** [comment]
> I confirm it for you. When i built Ungoogled Chromium 106, the build directory went over 75 GB. It did not reach 80 GB, but almost. I had to restart twice or thrice, because i've ran out of disk space during compiling.

You might have enabled debugging features.

**Comment by TCH68k** [comment]
Seems to be half true. Debugging was the problem, but i did not enabled it. I used this `flags.gn`:
https://raw.githubusercontent.com/Eloston/ungoogled-chromium/106.0.5249.119-1/flags.gn
And added the following lines:
```
use_gnome_keyring=false
use_pulseaudio=false
is_official_build=true
symbol_level=0
```
I thought setting `symbol_level` to zero will disable debug, but it seems, that is not necessarily true:
https://www.chromium.org/developers/gn-build-configuration/
It seems it will still produce some symbols, if `is_debug` is not set to `false`, because the default value for `is_debug` is `true`.

Why the `flags.gn` provided by Ungoogled Chromium does not sets it to `false`?

**Comment by PF4Public** [comment]
> Why the `flags.gn` provided by Ungoogled Chromium does not sets it to `false`?

Because it should be set in platform repository: https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/1dad51506ad483fa1a16ce6d8efc446bb460ed74/debian/rules#L57

**Comment by rany2** [comment]
@PF4Public I could confirm this, when I had to package 105.0.5195.52 for Flatpak I needed to disable `enable_mse_mpeg2ts_stream_parser` for the free/non-proprietary build.

**Comment by rany2** [comment]
Anyway https://source.chromium.org/search?q=enable_mse_mpeg2ts_stream_parser&sq=&ss=chromium confirms that `use_proprietary_codecs` needs to be enabled for  `enable_mse_mpeg2ts_stream_parser` to take effect.

**Comment by TCH68k** [comment]
@PF4Public:
> Because it should be set in platform repository: https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/1dad51506ad483fa1a16ce6d8efc446bb460ed74/debian/rules#L57

Oh, i did not know that, sorry. Anyway, thanks for the idea of disabling debug and that link, i'll have to add more flags.

**Comment by PF4Public** [comment]
@Ahrotahn @networkException Maybe we should move `enable_mse_mpeg2ts_stream_parser` into platform repositories then?

**Comment by TCH68k** [comment]
@PF4Public:
I would like to report, that no, it was not the debug symbols which ate over 70 GB. It was the `.git` and `third_party` directories:
http://oscomp.hu/depot/not_the_debug.png

**Comment by TCH68k** [comment]
After everything is cloned, fetched and set, the `.git` directory can be deleted, right? I assume it is not needed for the build.

**Comment by TCH68k** [comment]
I got this warning:
```
The variable "use_system_ffmpeg" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <out_dir>"

The build continued as if that argument was unspecified.
```
This is Ungoogled Chromium 115.
