### ISSUE TITLE
Unable to build with no ozone, but X11 only?

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2420]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

115.0.5790.99

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Setting use_ozone to false causes build failure.

### How to Reproduce?

1. Put `use_ozone=false` into `flags.gn`.
2. Build.

### Actual behaviour

Error message:
```
ERROR at //ui/platform_window/common/BUILD.gn:8:1: Assertion failed.
assert(use_ozone)
^-----
See //ui/aura/BUILD.gn:260:15: which caused the file to be included.
    deps += [ "//ui/platform_window/common" ]
              ^----------------------------
```

### Expected behaviour

Build without ozone, using X11 only, without a middle layer.

### Relevant log output

```sh
ERROR at //ui/platform_window/common/BUILD.gn:8:1: Assertion failed.
assert(use_ozone)
^-----
See //ui/aura/BUILD.gn:260:15: which caused the file to be included.
    deps += [ "//ui/platform_window/common" ]
              ^----------------------------
ninja: Entering directory `out/Release'
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by PF4Public** [comment]
> Build without ozone, using X11 only, without a middle layer.

Not possible.
