### ISSUE TITLE
Download location changes with consecutive downloads

### ISSUE THREAD

**Issue by BptGrm** [ungoogled-software/ungoogled-chromium#2427]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

115.0.5790.98

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Whenever I download several files in a row, after I specify the download location for the first file, every subsequent download location prompt opens on what I assume is a temporary location.

### How to Reproduce?

Download several files in a row with "Ask for location every time" option enabled.

### Actual behaviour

Whenever I download several files in a row, after I specify the download location for the first file, every subsequent download location prompt opens on what I assume is a temporary location :

![255166874-41d2b742-161a-4647-8036-40ceb92bb18f](https://github.com/ungoogled-software/ungoogled-chromium/assets/83828302/894abfde-c7d7-4fb1-aa71-4e178734cc71)

This location still displays the files in the previously selected folder (i.e. at least the first downloaded file), but clicking "Download" doesn't seem to do anything, and I then have to navigate to the correct folder again.

This only seems to happen when saving to a different drive/partition than home.

### Expected behaviour

The download prompt should open on the last download location.

### Additional context

Reproduced in both Ubuntu 22.04 LTS and Zorin OS 16 (based on Ubuntu LTS 20.04 LTS).
Cross-posted from the [Flatpak GitHub](https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/123) because I'm not sure this was the right place to ask.

**Comment by PF4Public** [comment]
I'll close this issue since it was reported upstream.

**Comment by BptGrm** [comment]
Could you point to the upstream issue ? I couldn't find anything related to that specific bug. Thanks !

**Comment by PF4Public** [comment]
I meant that it must be a Flatpak issue, therefore it is sufficient that issue reported there. Sorry for ambiguous wording.

**Comment by BptGrm** [comment]
I see, thanks for the clarification !
