### ISSUE TITLE
proxy autoconfig option is ignored.

### ISSUE THREAD

**Issue by qtlin** [ungoogled-software/ungoogled-chromium#2433]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

Version 114.0.5735.198 (Official Build) Fedora Project (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

--proxy-pac-url=http://wpad/wpad.dat is ignored.

### How to Reproduce?

1. verify via `curl http://wpad/wpad.dat` that proxy autoconfig data is valid.
2. launch `/var/lib/flatpak/app/com.github.Eloston.UngoogledChromium/current/active/export/bin/com.github.Eloston.UngoogledChromium --proxy-pac-url=http://wpad/wpad.dat`
3. open `http://ip4.me` or any other similar site that displays IP address

### Actual behaviour

Shows actual IP address.

### Expected behaviour

Shows proxy IP address.

### Additional context

Repeat same steps using `/usr/bin/chromium-browser --proxy-pac-url=http://wpad/wpad.dat` and observe that proxy IP is returned.

**Comment by networkException** [comment]
Is this relevant to your issue? https://superuser.com/questions/1405499/chrome-72-seems-to-no-longer-accept-proxy-pac-url

**Comment by rany2** [comment]
> ### Installed
> 
> Flatpak

This might be the reason why. What DE are you using?

**Comment by qtlin** [comment]
> This might be the reason why. What DE are you using?

What is **DE**? I didn't find anything besides Flatpak available.

**Comment by qtlin** [comment]
I just tried Portable Linux build and proxy works as intended.

**Comment by networkException** [comment]
in that case you should report it in the [flatpak repository](https://github.com/flathub/com.github.Eloston.UngoogledChromium)
