### ISSUE TITLE
Installed Web Apps Missing Flavicon Shortcuts

### ISSUE THREAD

**Issue by plzhelpmevoid** [ungoogled-software/ungoogled-chromium#2435]
### OS/Platform

Fedora and CentOS

### Installed

OS/Platform's package manager

### Version

115.0.5790.98

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

See title

### How to Reproduce?

1. Go to any web app (ex. crypt.ee)
2. Click the installation icon that appears on the right side of the address bar.
3. Close newly installed web app.
4. Search for app.

### Actual behaviour

You will see that the icon for the app is the default gears icon rather than the app's (ex. crypt.ee) Flavicon.

### Expected behaviour

App icon should be the app's flavicon.

### Additional context

Hope this is alright! I'm very new to github. Thanks!

**Comment by networkException** [comment]
Please try reproducing with different parameters as described in the checkboxes above. I'm not experiencing this issue myself
