### ISSUE TITLE
Make the AppImage updatable through AppImageUpdate or similar tools

### ISSUE THREAD

**Issue by f-mc2** [ungoogled-software/ungoogled-chromium#2438]
### Description

Make the AppImage updatable  through AppImageUpdate or similar tools.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I was not able to find a similar request in the issue tracker, but I apologize in advance if my search was not good enough. 

Essentially, I think it would be useful to be able to update the AppImage of ungoogled-chromium through something like [AppImageUpdate](https://appimage.github.io/AppImageUpdate/).

### Possible solutions

As far as I understand, the update feature may be enabled by the developers following [this guide](https://docs.appimage.org/packaging-guide/optional/updates.html).

**Comment by PF4Public** [comment]
We do not provide AppImage binaries, they are submitted by volunteers. As such we have very little control over them.
