### ISSUE TITLE
How export/duplicate profile with extensions on GNU/Linux? 

### ISSUE THREAD

**Issue by VXEAD** [ungoogled-software/ungoogled-chromium#2450]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

Version 115.0.5790.170

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Can export/duplicate profile with extensions on GNU/Linux

### How to Reproduce?

Im trying to found profile setting on flatpak folder but i cant/ 
help me please to export / dublicate it!

### Actual behaviour

Im trying to found profile setting on flatpak folder but i cant/ 
help me please to export / dublicate it!

### Expected behaviour

Im trying to found profile setting on flatpak folder but i cant/ 
help me please to export / dublicate it!

**Comment by PF4Public** [comment]
Please file this issue with the Flatpak repo: [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium)
