### ISSUE TITLE
Add openSUSE to list of distros

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [ungoogled-software/ungoogled-chromium#2457]
### Description

I've been maintaining ungoogled-chromium build for opensuse for some time now and would like to see it on distros list

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I've been maintaining ungoogled-chromium build for opensuse for some time now and would like to see it on distros list

### Possible solutions

Add openSUSE to distros list but i'm unsure if it should be in maintained builds or 3rd party binaries

### Additional context

https://build.opensuse.org/package/show/openSUSE:Factory/ungoogled-chromium
https://build.opensuse.org/package/show/network:chromium/ungoogled-chromium

(it's in standard repo on tumbleweed)

**Comment by PF4Public** [comment]
I'd say this qualifies as Third-party binaries

**Comment by Michal-Szczepaniak** [comment]
Lol this has been added in the maintained builds just… nobody closed this issue :D

Fixed by #5aa0f1d

**Comment by pallaswept** [comment]
Hi Michal,

Sadly, this was removed from Factory today... I am more than a little confused by this. Do you know what's happening?

**Comment by Michal-Szczepaniak** [comment]
I mentioned it being removed from factory, hence this pull request, what's the issue?

**Comment by pallaswept** [comment]
> you haven't seen #2819

Ahh I'm sorry, I somehow missed that! Thanks for letting me know and especially, thanks for the package. I really appreciate all the effort you've put into maintaining this for us over time.
