### ISSUE TITLE
Appimage v.116 won't start: `loading shared libraries: libffi.so.8: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by Flashwalker** [ungoogled-software/ungoogled-chromium#2460]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

116

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Refuse to start

### How to Reproduce?

1. run `ungoogled-chromium_116.0.5845.96-1.1.AppImage`

### Actual behaviour

Won't start

### Expected behaviour

Start

### Relevant log output

```sh
$ ungoogled-chromium_116.0.5845.96-1.1.AppImage

/tmp/.mount_ungoog645Fc7/opt/google/chrome/chrome: error while loading shared libraries: libffi.so.8: cannot open shared object file: No such file or directory
```

### Additional context

ungoogled-chromium_112.0.5615.165-1.1.AppImage  
starts up fine

**Comment by PF4Public** [comment]
Please provide detailed information regarding your OS. `libffi.so.8` should be available in Debian stable. Also check whether you have `libffi8` installed.

**Comment by Flashwalker** [comment]
> Please provide detailed information regarding your OS. `libffi.so.8` should be available in Debian stable. Also check whether you have `libffi8` installed.

Oops, i forgot to specify the OS version.
It's Ubintu 20.04

**Comment by PF4Public** [comment]
> On 22.04 it works fine, but not on 20.04.
> There is no **libffi8** on 20.04, only **libffi7**

Which means it is not an issue of ungoogled-chromium 🤷🏻
