### ISSUE TITLE
I now have 3 chromium repos on my HD

### ISSUE THREAD

**Issue by LeOS-GSI** [ungoogled-software/ungoogled-chromium#2462]
I have build successful a chromium .deb 

now I'm trying to build the ungoogled version with your tutorial. But it is confusing me and I do have now 3 chromium repos on my HD. 
1. my existing one from my build
2. that one from your 'main' instructions
3. that one from distro specific instruction (Debian). But this tutorial was not working for me. the script fails with 'cstring' not found.

I have my existing repo
I have run gclient -sync for fresh soruces
but now I have inside my 'chromium' folder' this new 'build/src' folder with downloaded chromium sources. ??
--- WHY do I need double the chromium repos ??

Because of this folder structure, the command `/ungoogled-chromium/build/src$ gn args out/Default --fail-on-unused-args` fails with `ERROR at //.gn:5:1: Unable to load "/media/ich/exSSD31/ungoogled-chromium/build/src/build/dotfile_settings.gni".
import("//build/dotfile_settings.gni")
`
The file is not located in ungoogled-chromium/build/src/build/ 
it's located in ungoogled-chromium/build/src/

So what am I doing wrong that 1 have now in my ungoogled-chromium/src folder my with gclient sync downloaded sources and in ungoogled-chromium/build/src once more the chromium sources ??

EDIT: I have now tried to use my chromium/src folder as src folder in build folder. But then I can run Part 1. I'm getting errors, because some folders are existing

when trying it without Part 1, I get an error when trying prune command from PART2.

**Comment by PF4Public** [comment]
Please file the issue template. If your issue is related to folder structure, I'm afraid I'll have to close it with "wontfix"

**Comment by LeOS-GSI** [comment]
> Please file the issue template. If your issue is related to folder structure, I'm afraid I'll have to close it with "wontfix"Sorry, but that's stupid. It makes no difference when I copy paste it as ISSUE.

By the way, the command `./out/Default/gn gen out/Default --fail-on-unused-args` is also wrong. It needs to be ./out/Default/gn gen args out/Default --fail-on-unused-args

**Comment by PF4Public** [comment]
Not an issue of ungoogled-chromium.
