### ISSUE TITLE
Folder structure does not work for Linux build

### ISSUE THREAD

**Issue by LeOS-GSI** [ungoogled-software/ungoogled-chromium#2463]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

116.0.5845.97

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I have build successful a chromium .deb  now I'm trying to build the ungoogled version with your tutorial. But it is confusing me and I do have now 3 chromium repos on my HD.      my existing one from my build     that one from your 'main' instructions     that one from distro specific instruction (Debian). But this tutorial was not working for me. the script fails with 'cstring' not found.  I have my existing repo I have run gclient -sync for fresh soruces but now I have inside my 'chromium' folder' this new 'build/src' folder with downloaded chromium sources. ?? --- WHY do I need double the chromium repos ??  Because of this folder structure, the command /ungoogled-chromium/build/src$ gn args out/Default --fail-on-unused-args fails with ERROR at //.gn:5:1: Unable to load "/media/ich/exSSD31/ungoogled-chromium/build/src/build/dotfile_settings.gni". import("//build/dotfile_settings.gni")  The file is not located in ungoogled-chromium/build/src/build/ it's located in ungoogled-chromium/build/src/  So what am I doing wrong that 1 have now in my ungoogled-chromium/src folder my with gclient sync downloaded sources and in ungoogled-chromium/build/src once more the chromium sources ??  EDIT: I have now tried to use my chromium/src folder as src folder in build folder. But then I can run Part 1. I'm getting errors, because some folders are existing  when trying it without Part 1, I get an error when trying prune command from PART2.

### How to Reproduce?

try building ungoogled chromium and use the tutorial from your repo

### Actual behaviour

see above

### Expected behaviour

see above

**Comment by LeOS-GSI** [comment]
@PF4Public so, do you have now more informations or was it only wasted time for you and me ??

**Comment by PF4Public** [comment]
Not an issue of ungoogled-chromium.

**Comment by LeOS-GSI** [comment]
> Not an issue of ungoogled-chromium.

What the hell oft support is that here ? I have created this as uncategorized issue and you have written I have to create an really issue. And now you are closing it because it's not an ungoogled chromium issue.

As I have written, it's an problem/mistake I'm your tutorial. 

But it seems you are not interested to correct  mistakes and you won't help other users. 

Really great support !!!!!

**Comment by LeOS-GSI** [comment]
Is there any problem or user request which you are not closing ?
