### ISSUE TITLE
error when creating args

### ISSUE THREAD

**Issue by LeOS-GSI** [ungoogled-software/ungoogled-chromium#2464]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

116.0.5845.97

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I have tried both versions, creating all files in src with gclient sync and also with your part 12 from your tutuorial. But I'm getting thiwe error behind.   Rust is is installed and working fine. I'm build Android GSI, apks and I have build successful a Chromium version. Never have gotten this error. By the way, your command './out/Default/gn gen out/Default --fail-on-unused-args' is not working. I have to use 'gn args out/Default'

### How to Reproduce?

try building with your tutorial

### Actual behaviour

??????????ß

### Expected behaviour

??????

### Relevant log output

```sh
ich@leos:/media/ich/exSSD31/ungoogled-chromium/build/src$ gn args out/Default
Waiting for editor on "/media/ich/exSSD31/ungoogled-chromium/build/src/out/Default/args.gn"...
Generating files...
ERROR at //build/config/rust.gni:132:24: Script returned non-zero exit code.
      rustc_revision = exec_script("//tools/rust/update_rust.py",
                       ^----------
Current dir: /media/ich/exSSD31/ungoogled-chromium/build/src/out/Default/
Command: python3 /media/ich/exSSD31/ungoogled-chromium/build/src/tools/rust/update_rust.py --print-package-version
Returned 1 and printed out:

The expected Rust version is 006a26c0b546abc0fbef59a773639582b641e500-11-llvmorg-17-init-12166-g7586aeab but the actual version is 006a26c0b546abc0fbef59a773639582b641e500-11-llvmorg-17-init-16420-g0c545a44
Did you run "gclient sync"?

See //BUILD.gn:17:1: whence it was imported.
import("//build/config/rust.gni")
^-------------------------------
ich@leos:/media/ich/exSSD31/ungoogled-chromium/build/src$
```

### Additional context

./.

**Comment by PF4Public** [comment]
See https://github.com/ungoogled-software/ungoogled-chromium/pull/2445#issue-1837899526

**Comment by networkException** [comment]
> It's probably best to build with enable_rust=false for now since they have been hardcoding paths based on their own toolchain setup. You can attempt to adjust the values in build/config/clang/BUILD.gn to your system's paths for the builtins if you want to attempt to get that set up.
