### ISSUE TITLE
WASM (WebAssembly) not working

### ISSUE THREAD

**Issue by Ruslan0Dev** [ungoogled-software/ungoogled-chromium#2466]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

116.0.5845.97

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

WASM support error

### How to Reproduce?

Visit regex101.com 

### Actual behaviour

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/23433847/760653f8-b2c4-4d32-8dda-e614b65dec2b)

### Expected behaviour

I expect WASM to work as before. (old builds ungoogled-chromium). How to solve this?

### Relevant log output

```sh
on other sites in the console:
ReferenceError: WebAssembly is not defined
```

**Comment by PF4Public** [comment]
@h4ckee Do you have JIT enabled or disabled in website settings panel?
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/4aa8a264-d360-4e25-b956-ccf38509d352)

**Comment by Ruslan0Dev** [comment]
@PF4Public Thanks! It really helped!
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/23433847/48226a79-ce5e-4889-bc8f-7ad2245158d2)

**Comment by Ruslan0Dev** [comment]
> Please note that you are not using ungoogled-chromium binaries.
> 
> We do not provide support for third-party binaries and I would not recommend downloading and installing them.

i use that launcher-downloader-updater:
https://github.com/henrypp/chrlauncher

**Comment by PF4Public** [comment]
Riiiight, Here is where confusion comes from https://github.com/henrypp/chrlauncher/blob/ed4285186d6365551c50e2b4a561ea4e205ad304/bin/chrlauncher.ini#L71-L74:
```
# ungoogled-chromium
#	Unofficial builds without Google integration and enhanced privacy (based on Eloston project)
#	"github.com/macchrome/winchrome/releases/" (32/64 bit)
#	"github.com/Eloston/ungoogled-chromium"
```
