### ISSUE TITLE
Dialogs are either crash the browser, or simply do not appear

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2473]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

108.0.5359.125

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Any kind of file dialog is impossible to reach. Triggered dialogs, like input file or trying to open an URL which downloads a file are simply not working, while Ctrl+S crashesh the browser with segmentation fault.

### How to Reproduce?

1. Build Ungoogled Chromium with these flags:
```
build_with_tflite_lib=false
chrome_pgo_phase=0
clang_use_chrome_plugins=false
disable_fieldtrial_testing_config=true
enable_hangout_services_extension=false
enable_js_type_check=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_widevine=true
exclude_unwind_tables=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
safe_browsing_mode=0
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_unofficial_version_number=false

is_official_build=true
is_chrome_branded=false
is_chrome_for_testing=false
is_chrome_for_testing_branded=false

is_clang=true
is_component_build=false
optimize_webui=true

is_debug=false
symbol_level=0
blink_symbol_level=0
v8_symbol_level=0
v8_enable_backtrace=false
enable_iterator_debugging=false
blink_enable_generated_code_formatting=false

dcheck_always_on=false
is_cfi=false
use_thin_lto=false
angle_build_tests=false
build_dawn_tests=false
build_libsrtp_tests=false
enable_assistant_integration_tests=false
enable_downstream_media_tests=false
enable_nocompile_tests=false
enable_perfetto_integration_tests=false
enable_perfetto_unittests=false
enable_printing_unittests=false
enable_soda_integration_tests=false
force_enable_fieldtrial_testing_config=false
internal_gles2_conform_tests=false
internal_khronos_glcts_tests=false
rtc_include_tests=false
skia_enable_skshaper_tests=false
tint_build_unittests=false
use_base_test_suite=false
use_rts=false
safe_browsing_mode=0

use_gnome_keyring=false
use_pulseaudio=false
link_pulseaudio=false
use_alsa=true
use_cups=true
use_goma=false
use_kerberos=false
use_gio=true
use_sysroot=false
enable_vr=false
use_bluez=true
use_system_libffi=true

enable_ffmpeg_video_decoders=true
media_use_ffmpeg=true
proprietary_codecs=true
ffmpeg_branding="Chrome"
use_webaudio_ffmpeg=true
use_webaudio_pffft=false
enable_dav1d_decoder=false
rtc_include_dav1d_in_internal_decoder_factory=false
enable_av1_decoder=true
enable_libaom=true
use_libgav1_parser=true
use_vaapi=true
use_vaapi_x11=true

ozone_auto_platforms=false
ozone_platform="x11"
ozone_platform_cast=false
ozone_platform_drm=false
ozone_platform_flatland=false
ozone_platform_gbm=false
ozone_platform_headless=false
ozone_platform_scenic=false
ozone_platform_wayland=false
ozone_platform_x11=true
use_ozone=true

use_gtk=false
use_aura=true
use_qt=false
```
2. Try to Ctrl+S a webpage or up/download a file.

### Actual behaviour

No dialogs, or crash.

### Expected behaviour

A file dialog should appear

### Relevant log output

```sh
There are no error messages in the console, except for 'Segmentation fault'.
```

**Comment by PF4Public** [comment]
What makes you think it is ungoogled-chromium issue?

**Comment by TCH68k** [comment]
You say it is a vanilla-chromium issue?

**Comment by PF4Public** [comment]
Please try building vanilla chromium with your flags and reproducing the issue.

**Comment by TCH68k** [comment]
I built 113 and still no dialogs. How can i make the sources vanilla again and then just compile what needed, without restarting it from scratch? By looking for `*.orig` files and renaming them back? Will that work?

I do not want to start it again. My machine is building for days now and it boiled itself and my flat too.

**Comment by TCH68k** [comment]
It seems, i was wrong: if i prepend `LD_LIBRARY_PATH=/opt/gtk3/lib/ ` to the `chrome` command line, then GTK3 activates and the dialogs starts to work. But without it, with Aura, no dialogs. It seems, that if i want to use GTK3 or Qt5, then some kind of hybrid Chromium is made, which has both Aura and either GTK3 or Qt5.

But Qt5 cannot be activated with ` --enable-features=AllowQt` appended to the `chrome` command line. Perhaps a different `LD_LIBRARY_PATH` needed?

**Comment by TCH68k** [comment]
No, it needed GTK3, see #2421.

**Comment by PF4Public** [comment]
I assume it is not an issue with ungoogled-chromium

**Comment by TCH68k** [comment]
I've reported it to them: https://bugs.chromium.org/p/chromium/issues/detail?id=1475740

As exptected, no answer. See what i meant?

**Comment by PF4Public** [comment]
> As exptected, no answer. See what i meant?

I wouldn't say that it is _expected_ to receive immediate reply for an issue filed on Friday ;)

> Thanks for the tips and the patience.

Glad I could help

**Comment by TCH68k** [comment]
Friday? Where is the coding spirit? But jokes aside, any reply would do it, like _"we need logs"_, or whatever. I did not expected a _solution_, i expected a _reply_, but **_any_** kind of reply would do it, even ones which takes 30 secs to write.

I have the feeling, that they will close it one day, without reply. They might fix the issue meanwhile, but won't reply. But i may be wrong.
