### ISSUE TITLE
Clear data on exit flag doesn't work anymore

### ISSUE THREAD

**Issue by calhix** [ungoogled-software/ungoogled-chromium#2474]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

116.0.5845.96

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Flag doesn't work anymore

### How to Reproduce?

Enable #clear-data-on-exit, go to a few websites, close Ungoogled Chromium, open it back up, browsing history shows multiple items that aren't deleted.

### Actual behaviour

Browsing history is saved

### Expected behaviour

Browsing history is cleared upon exit

### Additional context

Not sure how long it's been going on but stopped working somewhat recently.

**Comment by PF4Public** [comment]
Please follow https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/259 since it was first.
