### ISSUE TITLE
Websites like Snapdrop and Sharedrop doesn't work!!

### ISSUE THREAD

**Issue by worrye** [ungoogled-software/ungoogled-chromium#2479]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

 116.0.5845.140 

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [x] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When i try to share files from my phone to my laptop using above menntioned websites. It doesn't work. It doesn't ask me to accept the file and i can't downlaod it. However works on other chromium/chrome browsers

### How to Reproduce?

1. Go to "https;//www.sharedrop.io" with two devices or just open two tabs of it
2. Then click on the icon of available devices
3. Choose a file to send and click open
4. Click send button on pop up menu
5. Then you can see from other device/tab the website doesn't give you pop up menu to accept it

### Actual behaviour

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/107336879/3c344cdf-59d7-437b-92ff-20f9b7f050aa)
there is just the little beeping side of the icon (for infinite time)

### Expected behaviour

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/107336879/9db68f3d-80d0-4f4e-a6e4-ed4f65644b2f)
here, you can see pop up menu to accept the file (done in vanilla chromium)

**Comment by Nifury** [comment]
I think it's because WebRTC is disabled by default. 
Can be re-enabled via chrome://flags/#webrtc-ip-handling-policy, and set the value to default. 

Might be worth mentioning this on the first run page.

**Comment by worrye** [comment]
Thanks @Nifury it worked like a charm! I guess that should be added on the first run page tooo!!
