### ISSUE TITLE
Which UGC is the last which runs on windows 7 64-bit?

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2480]
### Description

The latest pre-built binaries (https://ungoogled-software.github.io/ungoogled-chromium-binaries/) are not working.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

-

### Possible solutions

-

**Comment by tomasz1986** [comment]
It's no different than regular Chromium, so the answer is https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-and-windows-server-2012-and-2012-r2-in-early-2023.

**Comment by jstkdng** [comment]
switch to a linux distro and use latest ugc there

**Comment by TCH68k** [comment]
@tomasz1986: Thank you, so it is 109.

@jstkdng: I use Debian (Devuan) and latest (116) UGC. How it is related to my question?

**Comment by Drake53** [comment]
Is it possible to stop the 'update to windows 10' message from showing every time you open the browser?
If not, which is the latest version that does not show this? I tried 108 but this version also shows the message.
