### ISSUE TITLE
Impossible to install extensions

### ISSUE THREAD

**Issue by TCH68k** [ungoogled-software/ungoogled-chromium#2481]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Compiled from source

### Version

116.0.5845.111

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Extension mime handling is unavailable, so it is impossible to install extensions.

### How to Reproduce?

1. Go to chrome://flags/#extension-mime-request-handling
2. OR run UGC with the flag --extension-mime-request-handling=install-always

### Actual behaviour

The mime request handling is disappeared from the flags and the passed flag has no effect.

### Expected behaviour

Install the CRX.

**Comment by tomasz1986** [comment]
It's still there for me:

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/5626656/750e310f-abcf-47cb-b558-cfe722d0d74e)

**Comment by TCH68k** [comment]
http://oscomp.hu/depot/notforme.png

**Comment by tomasz1986** [comment]
Yeah, but I'm using the official binaries for Windows, so I'd say it's likely something in your self-compiled build. Can you test any of the contributed Linux binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries and see whether the problem persists there as well? By "any" I mean either "Linux AppImage 64-bit" or "Portable Linux 64-bit" because only these two are at the v116 version right now.

**Comment by TCH68k** [comment]
I can't. They are compiled with GTK3 at system/package level and GTK3 is exiled from my system at system/package level; i only have it in an isolated directory which i pass to Chromium at compiling and running.

I built it with these flags though:
```
build_with_tflite_lib=false
chrome_pgo_phase=0
clang_use_chrome_plugins=false
disable_fieldtrial_testing_config=true
enable_hangout_services_extension=false
enable_js_type_check=false
enable_mdns=false
enable_mse_mpeg2ts_stream_parser=true
enable_nacl=false
enable_reading_list=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_widevine=true
exclude_unwind_tables=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
safe_browsing_mode=0
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_unofficial_version_number=false

is_official_build=true
is_chrome_branded=false
is_chrome_for_testing=false
is_chrome_for_testing_branded=false

is_clang=true
is_component_build=false
optimize_webui=true

is_debug=false
symbol_level=0
blink_symbol_level=0
v8_symbol_level=0
v8_enable_backtrace=false
enable_iterator_debugging=false
blink_enable_generated_code_formatting=false

dcheck_always_on=false
is_cfi=false
use_thin_lto=false
angle_build_tests=false
build_dawn_tests=false
build_libsrtp_tests=false
enable_assistant_integration_tests=false
enable_downstream_media_tests=false
enable_nocompile_tests=false
enable_perfetto_integration_tests=false
enable_perfetto_unittests=false
enable_printing_unittests=false
enable_soda_integration_tests=false
force_enable_fieldtrial_testing_config=false
internal_gles2_conform_tests=false
internal_khronos_glcts_tests=false
rtc_include_tests=false
skia_enable_skshaper_tests=false
tint_build_unittests=false
use_base_test_suite=false
use_rts=false
safe_browsing_mode=0

use_gnome_keyring=false
use_pulseaudio=false
link_pulseaudio=false
use_alsa=true
use_cups=true
use_goma=false
use_kerberos=false
use_gio=true
use_sysroot=false
enable_vr=false
use_bluez=true
use_system_libffi=true

enable_ffmpeg_video_decoders=true
media_use_ffmpeg=true
proprietary_codecs=true
ffmpeg_branding="Chrome"
use_webaudio_ffmpeg=true
use_webaudio_pffft=false
enable_dav1d_decoder=false
rtc_include_dav1d_in_internal_decoder_factory=false
enable_av1_decoder=true
enable_libaom=true
use_libgav1_parser=true
use_vaapi=true
use_vaapi_x11=true

ozone_auto_platforms=false
ozone_platform="x11"
ozone_platform_cast=false
ozone_platform_drm=false
ozone_platform_flatland=false
ozone_platform_gbm=false
ozone_platform_headless=false
ozone_platform_scenic=false
ozone_platform_wayland=false
ozone_platform_x11=true
use_ozone=true

use_gtk=true
use_aura=true
use_qt=false
```

**Comment by PF4Public** [comment]
Have you forgotten to apply `patches/extra/ungoogled-chromium/add-flag-to-configure-extension-downloading.patch`?

**Comment by TCH68k** [comment]
If it is in the ungoogled-chromium repository, then no; i clone the repo and systematically apply all patches:
```
git clone https://github.com/Eloston/ungoogled-chromium/
cd ungoogled-chromium
git checkout "$CHROME_VERSION""-1"
cp flags.gn ../flags.gn.bak
cd ..
find ungoogled-chromium/patches/ -name '*.patch' -exec mv {} ./ \;
rm -rf ungoogled-chromium
for PATCH in *.patch;
do
	patch -p1 -f < "$PATCH";
done
rm *.patch
```

**Comment by TCH68k** [comment]
Now hold on for a moment. If there is a python script for applying the patches, then why did you ask if i forgot to apply a patch?
Also, does this mean, that the reason this flag is missing, that google took it out from Chromium and it is patched back in UGC?

Actually i already "solved" it: i can download the CRX, unpack it and then load it unpacked. But that is rather a workaround.
