### ISSUE TITLE
When chromium is started directly without chrlauncher Chromite icon shows

### ISSUE THREAD

**Issue by Rexadev** [ungoogled-software/ungoogled-chromium#2486]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

Version 116.0.5845.141 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Chromite icon shows

### How to Reproduce?

1.  Find chrome.exe and double click on it 
2.  Chromite icons is shown
3.  Open Chromium using chrlauncher .
4. Chromium lancher is shown

### Actual behaviour

Chromite icons is shown

### Expected behaviour

4. Chromium launcher should be shown

### Additional context

Marmaduke Windows x64 Portable

**Comment by tomasz1986** [comment]
> Marmaduke Windows x64 Portable

Chrlauncher and 3rd party builds like this one aren't supported here. If you want to receive support for Ungoogled Chromium, you need to use the official builds from https://github.com/ungoogled-software/ungoogled-chromium-windows/releases.

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.
If you're seeking support report this issue to where you've obtained the binary.
