### ISSUE TITLE
`notification.onlick` event not work.

### ISSUE THREAD

**Issue by Axotot1** [ungoogled-software/ungoogled-chromium#2488]
### OS/Platform

Windows 10 22H2 (10.0.19045.3324)

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

116.0.5845.141（Official Build, ungoogled-chromium） （64 bits）

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

notification.onclick never be called

### How to Reproduce?

1. Open any page, then press F12
2. Go to "Console", then input
`Notification.requestPermission();`
3. After get Permisson, input
`new Notification("aaa").onclick = (() => console.log("good"));`
3. Then there will be a notification appears in the lower-right corner of the screen.
4. Click it

### Actual behaviour

nothing happend.

### Expected behaviour

Console should print `good`.

### Additional context

* I get Ungoogled-Chromium from chrlauncher.
* I didn't test on vanilla Chromium.
*  it could be reproduced in ungoogled-chromium with a new and empty profile using --user-data-dir command.

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.
If you're seeking support report this issue to where you've obtained the binary.

**Comment by Axotot1** [comment]
> We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged. If you're seeking support report this issue to where you've obtained the binary.

Ok.
I've just downloaded from GitHub release and reproduced the bug yet.

**Comment by PF4Public** [comment]
@Nifury @teeminus Could you reproduce this bug on Windows?
I cannot reproduce it on Linux.

**Comment by Axotot1** [comment]
Update:
The latest Vanilla Chromium version 118.0.5988.0（64 bits） I have tested also can be reproduced.
![2023_09_03_23-44-15](https://github.com/ungoogled-software/ungoogled-chromium/assets/99773418/b843bea4-e682-46f0-a661-c8db289c6c62)

**Comment by PF4Public** [comment]
Which makes it a Chromium issue. And Chromium on Windows specifically. 🤷🏻

**Comment by Axotot1** [comment]
> Which makes it a Chromium issue. And Chromium on Windows specifically. 🤷🏻

Ok, thanks.

**Comment by Axotot1** [comment]
For some reason, I can not access Google Services.
Anybody could help me make an issue on [Chromium Bugs Track list](https://bugs.chromium.org/p/chromium/issues/list)? Please!

**Comment by PF4Public** [comment]
@Axotot1 I couldn't reproduce this issue in Wine as well. Could be something wrong with your Windows installation.

https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/9c5ef07a-214e-452d-80d5-c3328193eb5b

**Comment by Axotot1** [comment]
> @Axotot1 I couldn't reproduce this issue in Wine as well. Could be something wrong with your Windows installation.
> 
>  screen.mp4

The emulated Notification (My *Chrome* also pop out this) could be worked at all.

**Comment by Nifury** [comment]
Cannot reproduce with the native notification.

https://github.com/ungoogled-software/ungoogled-chromium/assets/7867461/3e44cbb1-51f1-4bf8-b075-0a8190fe9f61

**Comment by Axotot1** [comment]
Thanks
I think maybe my registration was broken.
