### ISSUE TITLE
New versions don't show at brew.sh

### ISSUE THREAD

**Issue by mxsbrg** [ungoogled-software/ungoogled-chromium#2498]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

115

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

New versions don't show at brew.sh

### How to Reproduce?

1. Go to brew.sh
2. Type eloston-chromium in the search box
3. You will see "Current version: [115.0.5790.170-1.1,1691361202]"
4. In reality ungoogled-chromium has already been updated to v116 2 times.
5. https://github.com/Homebrew/homebrew-cask/blob/d3fc6d93b693a2d5a5f93c14ea8a8fa9163c24f9/Casks/e/eloston-chromium.rb needs updating.

### Actual behaviour

New versions don't appear.

### Expected behaviour

To be able to download new versions of the app.

**Comment by PF4Public** [comment]
Please use search before filling a bug
https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/119#issue-1837885892
https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/122
https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/124
