### ISSUE TITLE
Browser's viewport is not utilised properly

### ISSUE THREAD

**Issue by xd003** [ungoogled-software/ungoogled-chromium#2499]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

116.0.5845.141-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

The elements on a webpage don't utilise the the whole viewport and appear sort of zoomed out

### How to Reproduce?

I am not really sure if its something that happens on other websites too but its definitely very much apparent on YouTube. Just open YouTube and play any video

### Actual behaviour

For instance, on youtube there is screen space being wasted on both the left and right side like there's some sort of margin. It doesn't seem to happen on Chrome or even chromium based browser like Brave for instance

### Expected behaviour

I am attaching a screenshot to better explain the issue

Chrome/Brave
![IMG_20230908_232837_131](https://github.com/ungoogled-software/ungoogled-chromium/assets/26503185/2ee49caa-b2cf-479b-90e2-f6e3f29d85a6)

Ungoogled Chromium
![IMG_20230908_232841_964](https://github.com/ungoogled-software/ungoogled-chromium/assets/26503185/8bb52f50-b709-4f5a-b8be-9e8595c5cb24)

**Comment by PF4Public** [comment]
Have you tried reproducing this issue in ungoogled-chromium with a new and empty profile using --user-data-dir command line argument?

**Comment by networkException** [comment]
Please make sure (using the developer tools) that both viewport sizes have the same dimensions and that you use a site that doesn't do A-B-Testing like YouTube does and you have the same state in both browsers (eg. you're logged in)

**Comment by xd003** [comment]
I can no longer reproduce this issue. I guess it was some A-B Testing by YouTube, wasn't really aware about this thing. Sorry for bothering
