### ISSUE TITLE
When launched by clicking the icons, Chrome unexpectedly closes. 

### ISSUE THREAD

**Issue by azarok** [ungoogled-software/ungoogled-chromium#2501]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

116.0.5845.179

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When launched by clicking the desktop icons, Chrome unexpectedly closes. 

### How to Reproduce?

Simply click the ungoogled-chromium icon, and the app will close after a few seconds. If I run `flatpak run com.github.Eloston` in the terminal, the app doesn't crash.

### Actual behaviour

As per above
_Simply click the ungoogled-chromium icon, and the app will close after a few seconds. If I run `flatpak run com.github.Eloston` in the terminal, the app doesn't crash._

### Expected behaviour

As per above
_Simply click the ungoogled-chromium icon, and the app will close after a few seconds. If I run `flatpak run com.github.Eloston` in the terminal, the app doesn't crash._

In order to investigate the crash, it would be good if I could obtain some app logs.

**Comment by PF4Public** [comment]
Please file this issue with the Flatpak repo: [flathub/com.github.Eloston.UngoogledChromium](https://github.com/flathub/com.github.Eloston.UngoogledChromium)
