### ISSUE TITLE
Latest version of Ungoogled Chromium not working in Windows 7

### ISSUE THREAD

**Issue by shahwaliullah** [ungoogled-software/ungoogled-chromium#2507]
### Description

I am getting errors when i run ungoogled chromium i get errors. missing fies. but no issues in Windows 10

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

but latest version of supremium browser which is based on chromium works in Windows 7.

please look at this link:

https://github.com/win32ss/supermium

### Possible solutions

but latest version of supremium browser which is based on chromium works in Windows 7.

please look at this link:

https://github.com/win32ss/supermium

**Comment by networkException** [comment]
We are not planning to support platforms dropped by upstream.
