### ISSUE TITLE
WebRTC connection fails

### ISSUE THREAD

**Issue by sonigeez** [ungoogled-software/ungoogled-chromium#2516]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

117.0.5938.62

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Webrtc connection fails to connect

### How to Reproduce?

1. Install Ungoogled Chromium by `brew install --cask eloston-chromium`
2. Try connecting with [this webrtc](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) example 
   - click on start
   - click on call

### Actual behaviour

It didnt get connect.

### Expected behaviour

It should get connected

### Relevant log output
<img width="638" alt="Screenshot 2023-09-22 at 1 16 54 PM" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/114856815/46c6546e-14a5-4f86-bdf9-0c30857ec179">

**Comment by PF4Public** [comment]
> 2\. Try connecting with any webrtc connection

Please provide more info on how to reproduce this issue.

**Comment by sonigeez** [comment]
> > 2. Try connecting with any webrtc connection
> 
> Please provide more info on how to reproduce this issue.

Hey thanks for response, i have updated the issue let me know if you need more information.

**Comment by PF4Public** [comment]
> Maybe we should mention this on the first run page.

Or in FAQ?

**Comment by PF4Public** [comment]
FAQ updated.
