### ISSUE TITLE
Unable to use Skiff service

### ISSUE THREAD

**Issue by FrostyHoneyJuicy** [ungoogled-software/ungoogled-chromium#2531]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

117.0.5938.114

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Ungoogle Chromium cannot create Skiff accounts and log into existing Skiff accounts

### How to Reproduce?

To log into Skiff:
1. Go to https://app.skiff.com/
2. Type your existing email and password.
3. Click on the "Log in" button.
4. The website says: "It looks like there's a temporary connectivity issue. Please try again in a couple of minutes. On iOS, try temporarily disabling Lockdown Mode."

To create an account:
1. Go to https://app.skiff.com/
2. Click on the "Sign up" text.
3. Type any name for the email.
4. Click on the "Next" button.
5. Type any password twice.
6. Click on the "Next" button.
7. The website says: "Could not create account. Contact support@skiff.org for support."

### Actual behaviour

It seems like Ungoogle Chromium cannot allow me to send any data to the Skiff servers. It cannot allow me to create an account and log in with my existing account. 

### Expected behaviour

Compared to other browsers (like LibreWolf, Brave, Firefox and even Chrome), creating a Skiff account and logging in to the existing Skiff account is not an issue. Ungoogled-chromium should allow me to do that.

### Additional context

To install ungoogled-chromium, I went to this website first:
https://chromium.woolyss.com/

Then I clicked on the "Installer" by Marmadude.

Also, I did contact the Skiff support team first, but they have no idea why this is the issue.

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.

Please make sure first that you can reproduce this issue with contributor binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

Alternatively you may report this issue to where you've obtained the binary from.
