### ISSUE TITLE
automatically downloading images from discord's "open in browser" feature

### ISSUE THREAD

**Issue by BR5RK** [ungoogled-software/ungoogled-chromium#2535]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

115.0.5790.99

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

automatically downloading images from discord's "open in browser" feature

### How to Reproduce?

1. open discord
2. click on any posted image
3. click "open in browser"
4. image is automatically downloaded by the browser every time it's opened from discord

### Actual behaviour

image is automatically downloaded by the browser every time it's opened from discord

### Expected behaviour

preferably, not to automatically download images. just display them.

**Comment by PF4Public** [comment]
Is it a bug of ungoogled-chromium?

**Comment by BR5RK** [comment]
> Is it a bug of ungoogled-chromium?

almost certainly. the issue has persisted even after reformatting my entire operating system (it's been a long while). i don't see what else it could be seeing as it doesn't seem to be a discord circumstance.

**Comment by PF4Public** [comment]
Please try reproducing this issue in Chromium. I very much doubt it being an issue of ungoogled-chromium.
