### ISSUE TITLE
[Feature] Enable ECH by default

### ISSUE THREAD

**Issue by istiak101** [ungoogled-software/ungoogled-chromium#2540]
chrome://flags/#encrypted-client-hello

https://blog.cloudflare.com/announcing-encrypted-client-hello/
https://blog.cloudflare.com/encrypted-client-hello/
https://tls-ech.dev/
brave/brave-browser#1851
bromite#167

**Comment by networkException** [comment]
As per https://chromestatus.com/feature/6196703843581952 chromium stable will likely ship ECH in one of the next major releases.

I don't think there's anything from the ungoogled-chromium perspective speaking against this feature, as such it will become available as soon as we update to that chromium stable release.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
