### ISSUE TITLE
GitHub Actions: New version script does not exit on error

### ISSUE THREAD

**Issue by rany2** [ungoogled-software/ungoogled-chromium#2544]
Currently, it was decided that `jq -re` and `set -e` will be set to in order to exit on error. However, this does not work in subshells.

For example, you can try the following:

`exits_with_success.sh`:

```shell
#!/bin/bash
noop() { :;}
set -euo pipefail
noop $(false)
exit 0
```

In a shell,

```
$ bash exits_with_success.sh; echo Return value: $?
Return value: 0
```

**Comment by PF4Public** [comment]
@rany2 Do you have any solutions in mind for this one?

**Comment by rany2** [comment]
@PF4Public I'll give a potential solution a shot soonish, I have something in mind
