### ISSUE TITLE
Ungoogled Chromium 118.0.5993.70 segfaulting with --fingerprinting-canvas-measuretext-noise

### ISSUE THREAD

**Issue by bsdice** [ungoogled-software/ungoogled-chromium#2553]
### OS/Platform

Arch Linux

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

118.0.5993.70

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Using --fingerprinting-canvas-measuretext-noise in chromium-flags.conf will produce segfault at specific URL

### How to Reproduce?

On Arch, all updates as of 2023-10-14. X11, i3. With chromium-flags.conf:
```
--enable-features=VaapiVideoDecodeLinuxGL
--disable-features=UserAgentClientHint
--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
--extension-mime-request-handling=always-prompt-for-install
--fingerprinting-canvas-image-data-noise
--fingerprinting-canvas-measuretext-noise
--fingerprinting-client-rects-noise
```

If you go to https://www.nginx.com/blog/http-2-rapid-reset-attack-impacting-f5-nginx-products/ a website dealing with a recent security vulnerability, you will get a segfault.

Bug could exist for longer, I just updated to 118 and happened to hit the bug with the website mentioned.

No difference with all extensions disabled.

When I remove --fingerprinting-canvas-measuretext-noise tab stays alive.

### Actual behaviour

Tab shuts down with an "Ah, snap, SIGSEGV".

### Expected behaviour

No segfault ;-)

### Relevant log output

```sh
Oct 14 00:03:57 x kernel: chromium[176452]: segfault at 20 ip 0000562d74fcfcf4 sp 00007fffd245ff90 error 4 cpu 1 in chromium[562d6a6fd000+c109000] likely on CPU 1 (core 1, socket 0)
Oct 14 00:03:57 x kernel: Code: 8d 55 af 48 8d 4d a8 4c 8d 45 a4 4c 89 e7 4c 89 fe 49 89 d9 e8 5d 23 6a fe 66 41 81 4c 24 fc 01 00 80 3d 12 9c 1e 02 00 74 19 <49> 8b 46 20 48 8b 40 08 f2 0f 10 80 38 06 00 00 4c 89 e7 67 e8 73
```

### Additional context

Using the package from https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/$arch by @networkException

**Comment by networkException** [comment]
This is a known issue and will be fixed by #2552

**Comment by bsdice** [comment]
@networkException You really are on top of your game! Should have also checked open pull requests and not only open issues. Thank you for taking the time to reply, very much appreciated. And thank you for maintaining this. :-)

Closing as duplicate.

**Comment by bsdice** [comment]
Already worked on in https://github.com/ungoogled-software/ungoogled-chromium/pull/2552
