### ISSUE TITLE
I can't use voice search

### ISSUE THREAD

**Issue by kevinlucasilva** [ungoogled-software/ungoogled-chromium#2554]
### OS/Platform

GNU Guix

### Installed

OS/Platform's package manager

### Version

118.0.5993.70

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Every time I click on the voice button it appears as if I have no internet, which is not the case.

### How to Reproduce?

1. Go to google.com or translate.google.com;
2. Click on the voice search button;
3. An error message appears saying "no internet" or "can't connect to network".

### Actual behaviour

Every time I click on the voice button it appears as if I have no internet, which is not the case.

### Expected behaviour

This affects a site I use which is Duolingo (duolingo.com). Some lessons require me to speak into the microphone to try to repeat the sound, but when I click the record button the microphone does not open to speak and considers the sound to be wrong.

This also happens when I try to search by voice on google.com or translate.google.com. I would like to be able to use it on these sites as well.

### Additional context

I use Arch Linux and Ungoogled Chromium comes from the Chaotic repository.

Here is a reproduction of the error (GIF) on google.com and translate.google.com:
https://imgur.com/a/80XSRCi

I didn't reproduce the error on Duolingo because these lessons I commented on are random.

**Comment by networkException** [comment]
Are you using Guix or Arch now? Also, are there any errors in the console? Do you have third party cookies allowed on the sites you mentioned?
