### ISSUE TITLE
Gmail/Youtube signed out every time I close

### ISSUE THREAD

**Issue by mdf77** [ungoogled-software/ungoogled-chromium#2556]
### OS/Platform

Windows

### Installed

OS/Platform's package manager

### Version

Version 117.0.5938.150 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Every time I close the browser, I am signed out of Gmail and Youtube, but nothing else

### How to Reproduce?

Sign in to a Gmail account
Close the browser

### Actual behaviour

I sign in to Gmail/Youtube, and even with the setting to not clear cookies on close, it still signs me out of them, but not any other websites

### Expected behaviour

I shouldn't be signed out of Gmail/Youtube with the setting "Clear cookies and site data when you close all windows" off.

**Comment by PF4Public** [comment]
How did you install ungoogled-chromium?

**Comment by mdf77** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by PF4Public** [comment]
@teeminus @Nifury Is this issue reproducible for you?

**Comment by teeminus** [comment]
I don't have a google account, sorry.

**Comment by mdf77** [comment]
i tried adding a custom behavior in the cookies settings that [*.]google.com can always use cookies but it didnt help

**Comment by mdf77** [comment]
well i just tried it again and its working as expected now, ill make another issue if it happens again.
