### ISSUE TITLE
Where cookie files stored?

### ISSUE THREAD

**Issue by RandomDataScientist** [ungoogled-software/ungoogled-chromium#2564]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

118.0.5993.70 (Official Build, ungoogled-chromium)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Not a bug but more a question, where cookie files stored in portable version, tried to find info but nothing there.

### How to Reproduce?

Use ungoogled chromium portable.

### Actual behaviour

Can't find cookie files in portable version

### Expected behaviour

Find cookie files I guess.

### Relevant log output

```sh
[1018/185308.384:ERROR:crashpad_client_win.cc(805)] not connected
[1018/185342.350:ERROR:crashpad_client_win.cc(805)] not connected
[1018/190443.584:ERROR:crashpad_client_win.cc(805)] not connected
[1018/191949.753:ERROR:crashpad_client_win.cc(805)] not connected
[1018/195012.281:ERROR:crashpad_client_win.cc(805)] not connected
[1018/195118.430:ERROR:crashpad_client_win.cc(805)] not connected
[1019/113728.074:ERROR:crashpad_client_win.cc(805)] not connected
```

### Additional context

Using ungoogled chromium portable (unpacked ofc) setting such as delete cookie files each time i leave ungoogled chromium is off, gonna be happy if someone answers because I can't find location of cookie files.

**Comment by PF4Public** [comment]
Which steps have you attempted to find the answer yourself and what didn't work out?

**Comment by RandomDataScientist** [comment]
Tried to look in docs where portable version keep cookie files, and googling, also trying to look in issues, nothing.

**Comment by RandomDataScientist** [comment]
> Which steps have you attempted to find the answer yourself and what didn't work out?

Tried to look in docs where portable version keep cookie files, and googling, also trying to look in issues, nothing.

**Comment by RandomDataScientist** [comment]
But looks like cookies still saved.

**Comment by RandomDataScientist** [comment]
Nope, not here, looks like I found its in C:\Users\%name%\AppData\Local\Chromium\User Data
