### ISSUE TITLE
Reintroduce of the recently deleted important option "Energy Saver" EDIT : it seems energy saver is present in official version of Ungoogled Chromium so my request become : make the "energy saver" option permanently available even when plugged in without battery

### ISSUE THREAD

**Issue by trimechee** [ungoogled-software/ungoogled-chromium#2567]
### Description

Option of "Energy Saver" is deleted and we hope Ungoogled-Chromium will re-enable this option 

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hello, Thank you for the new amazing and fast version of Ungoogled Chromium :) 💯 🥇 

I have request please : in last version of Chromium v118.0.5993.106-r1192594 - Ungoogled, Ungoogled-Chromium has deleted mysteriously and surprisingly the important option of "Energy Saver" which freezes the processes not necessary in the background which makes it possible to release resources especially when our RAM and CPU power is limited, we hope Ungoogled-Chromium will reintroduce this capital option again in the source code of the browser and we also hope for this option of Energy Saver will be present and activated permanently Even when Plugged in and not only activated when we use the battery because it will help the Lapptops  taht are weak old, thank you very much ! 

https://support.google.com/chrome/answer/12929150?visit_id=638227751357191071-2548025678&p=chrome_memory_saver&rd=1#memory_saver&zippy=%2Cturn-memory-saver-on-or-off%2Cturn-energy-saver-on-or-off 

### Possible solutions

Look at the old source code of preceding versions of UNGOOGLED-CHROMIUM to re-order this erased option !

https://support.google.com/chrome/answer/12929150?visit_id=638227751357191071-2548025678&p=chrome_memory_saver&rd=1#memory_saver&zippy=%2Cturn-memory-saver-on-or-off%2Cturn-energy-saver-on-or-off

**Comment by PF4Public** [comment]
> Chromium v118.0.5993.106-r1192594 - Ungoogled

We don't have that version.

**Comment by trimechee** [comment]
@PF4Public I use the the known famous version of woolyss, Ungoogled Chromium for windows  made by Mr Marmaduke  @macchrome : 


https://github.com/macchrome/winchrome/releases/tag/v118.5993.106-M118.0.5993.106-r1192594-Win64 

May be Mr @Rusenche can help us to confirm this problem and and the enigmatic erasure of this capital option !

**Comment by tomasz1986** [comment]
@trimechee Those versions are not supported and not recommended here. I can only confirm that Energy Saver is present in the official binaries at https://github.com/ungoogled-software/ungoogled-chromium-windows/releases.

**Comment by trimechee** [comment]
Thank you @tomasz1986 for yout help  :)

I didn't know there is official version of Ungoogled Chromium ! because i read this and i was thinkink third binaries may be risky....

so I  change my request : make the energy saver option permanently available even when plugged in without battery , thank you !


"If your operating system is not listed above, you can also try to [Download binaries from here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)

NOTE: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily [reproducible](https://reproducible-builds.org/), authenticity cannot be guaranteed; In other words, there is always a non-zero probability that these binaries may have been tampered with. In the unlikely event that this has happened to you, please [report it in a new issue](https://github.com/ungoogled-software/ungoogled-chromium#contributing-reporting-contacting).

These binaries are known as contributor binaries."

**Comment by trimechee** [comment]
@PF4Public @tomasz1986 I just checked in the latest version of Google Chrome in the performance section, there is option "memory saver" but there is no longer the energy saver option,  energy saver has been removed and surely the next version of Ungoogled Chromium will no longer have the energy saver option  and we hope that Ungoogled Chromium will keep this option in its future versions even plugged in without battery, thank you :)

**Comment by Rusenche** [comment]
@trimechee, I agree with you, but your issue/topic should be created in the right place - here it is: https://github.com/macchrome/winchrome/issues :}

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.

Please make sure first that you can reproduce this issue with contributor binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

Alternatively you may report this issue to where you've obtained the binary from.

**Comment by trimechee** [comment]
@PF4Public Ok, i understand, thank you :) i was thiniking all Ungoogled Chromium binaries are the same ! 

I will wait patiently for the next version of Ungoogled Chromium which will surely imitate Google Chrome and will remove the energy saver option then I will talk about this subject again in sha Allah, thank you :)

**Comment by PF4Public** [comment]
> then I will talk about this subject again

That would be reasonable. We cannot act on events, which haven't happened yet.

**Comment by trimechee** [comment]
Yes you have right 👍 but i hope you wil re open this issue again for the future version of unggoeld chromium, and i change the title  enable save energy to make the "energy saver" option permanently available even when plugged in without battery, because the current version of Ungoogled Chroumium doesn't allow to enable save energy when plugged in , so Mr @PF4Public ,  it seems logical and reasonable to re-open the issue again because I changed the title of the issue, or should I make a new issue hoping not to be accused of posting the same issue because it's 2 issues entirely different ?
