### ISSUE TITLE
Extension Management: Migration

### ISSUE THREAD

**Issue by Pantyhose-X** [ungoogled-software/ungoogled-chromium#2573]
### Description

Batch process all extensions

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

chrome.google.com does not have certain extensions, and chrome.google.com won't let extensions that don't have privacy issues through. Not all of the very best extensions are in chrome.google.com.  for example [AdNauseam](https://github.com/dhowe/AdNauseam)

### Possible solutions

1. ungoogled-software\User Data\Default\Extensions # Install the extension by copying and pasting the folder, Known Issues Extensions folder won't install by copying and pasting and Extensions folder is emptied after opening the browser.

2. Packing or loading and unpacking at once All extended features

**Comment by networkException** [comment]
I don't understand this issue, what would you like ungoogled-chromium to do?

**Comment by Pantyhose-X** [comment]
> I don't understand this issue, what would you like ungoogled-chromium to do?

Drag and drop multiple extension folders at once to install
