### ISSUE TITLE
1 Core high cpu usage 

### ISSUE THREAD

**Issue by Pavel-Kons** [ungoogled-software/ungoogled-chromium#2577]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 118.0.5993.70 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

1 Core high cpu usage very often. Especially if use full screen on youtube.

### How to Reproduce?

1 Open any youtube video. (example https://www.youtube.com/watch?v=VMzuJWmh_hk)
2 Press f to full screen and back
3 you see high cpu usage for single core

### Actual behaviour

High cpu usage

### Expected behaviour

Use more gpu instead of cpu

### Additional context

 ![485](https://github.com/ungoogled-software/ungoogled-chromium/assets/94371663/7673bfd9-20dd-4874-a643-d69820146b80)

**Comment by PF4Public** [comment]
I doubt it being an issue off ungoogled-chromium. Could you reproduce this issue in vanilla Chromium?

**Comment by Pavel-Kons** [comment]
I tried chromium browser, and it has same issue.

**Comment by Pavel-Kons** [comment]
This bug in any version of chrome. Ungoogled chromium, chromium, google chrome.
