### ISSUE TITLE
Proprietary codecs  H.265/HEVC  (AAC, H.264/MP4) 

### ISSUE THREAD

**Issue by trimechee** [ungoogled-software/ungoogled-chromium#2582]
### Description

Support of proprietary codecs H.265/HEVC (AAC, H.264/MP4) 

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hello, I would like to know please if our beloved Ungoogled-Chromium natively supports proprietary codecs like H.265/HEVC (AAC, H.264/MP4) ?

### Possible solutions

Support natively proprietary codecs H.265/HEVC (AAC, H.264/MP4)

**Comment by PF4Public** [comment]
Please [use search first](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+HEVC).

**Comment by trimechee** [comment]
I'm not technically competent, I read but didn't really good understand, I just want to know, so it seems Ungoogled-Chromium doesn't have these codecs....
