### ISSUE TITLE
Help me command line build Chromium on windows

### ISSUE THREAD

**Issue by hungpmtin44** [ungoogled-software/ungoogled-chromium#2583]
### Description

I am building Chromium on windows, but got error on some device

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

Command line i am using:
```
gn gen out/Official --args="is_official_build=true is_debug=false target_cpu=\"x86\" enable_nacl=false proprietary_codecs = true ffmpeg_branding = \"Chrome\""
ninja -C out\Official chrome
```
What is best command line to build Chromium to make it like Chrome?
Thanks

### Possible solutions

Change command line build

**Comment by PF4Public** [comment]
Please add more information for us to better understand what your issue is.
