### ISSUE TITLE
Include a "Share/Open URL with Ungoogled Chromium" option for Android's cross-app sharing UI.

### ISSUE THREAD

**Issue by JTDimino** [ungoogled-software/ungoogled-chromium#2585]
### Description

Add an icon/button for Android's general cross-app sharing UI to enable opening URLs from other Android apps and browsers.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

As it currently stands, I find myself unable to open/share a URL in Ungoogled Chromium using the Android cross-app "Share" feature in present in other Android apps and browsers; instead, I have to copy and paste the URL into Ungoogled Chromium manually. Adding cross-app sharing functionality would be very useful and convenient.

### Possible solutions

Integrate Ungoogled Chromium into the Android cross-app sharing system.

**Comment by networkException** [comment]
We do not offer builds for Android anymore. Any ungoogled-chromium App on Android is likely extremely outdated and highly vulnerable!
