### ISSUE TITLE
Deal with screen_ai service

### ISSUE THREAD

**Issue by kkocdko** [ungoogled-software/ungoogled-chromium#2587]
### The problem

The `screen_ai` service is annoy and it always download then extract to `~/.config/chromium/screen_ai` directory.

However I didn't find any feature flags on the source code, but only build-time flags.

https://source.chromium.org/chromium/chromium/src/+/main:components/services/screen_ai/

### Possible solutions

Maybe add a command line switch / feature flag to disable it? Or contribute to upstream?

**Comment by PF4Public** [comment]
You'll have to provide more information for us to understand what the issue actually is. For example I don't have such folder at all.

**Comment by kkocdko** [comment]
Sorry that I mixed up the profile path of my own unmodified chromium and this ungoogled one. This one acturally doesn't have this problem because the replacing of Google's domains.

However I still glad to describe more: The `screen_ai` service in chromium is added for accessability functions like in time screen reader and AI based video captions.

IMO Like other annoy chromium AI functions added by Google in recent years, it eats resources and useless for most of users even blinds because they use other more powerful screen readers.

**Comment by kkocdko** [comment]
```
$ tree screen_ai/
screen_ai/
└── 120.0
    ├── aksara
    │   ├── aksara_page_layout_analysis_rpn_gro.binarypb
    │   └── aksara_page_layout_analysis_ti_rpn_gro.binarypb
    ├── files_list_main_content_extraction.txt
    ├── files_list_ocr.txt
    ├── gocr
    │   ├── gocr_models
    │   │   └── line_recognition_mobile_convnext320
    │   │       ├── Latn_ctc
    │   │       │   └── optical
    │   │       │       ├── assets.extra
    │   │       │       │   └── LabelMap.pb
    │   │       │       └── model.fb
    │   │       ├── Latn_ctc_cpu.binarypb
    │   │       └── tflite_langid.tflite
    │   └── layout
    │       ├── cluster_sort_custom_ops
    │       │   └── model.tflite
    │       └── line_splitting_custom_ops
    │           └── model.tflite
    ├── libchromescreenai.so
    ├── manifest.fingerprint
    ├── manifest.json
    ├── _metadata
    │   └── verified_contents.json
    ├── screen2x_config.pbtxt
    ├── screen2x_model.tflite
    ├── taser
    │   ├── detector
    │   │   ├── region_proposal_text_detector_tflite_vertical_mbv2_v1.bincfg
    │   │   └── rpn_text_detector_mobile_space_to_depth_quantized_mbv2_v1.tflite
    │   ├── rpn_text_detection_tflite_mobile_mbv2.binarypb
    │   ├── segmenter
    │   │   ├── tflite_script_detector_0.3.bincfg
    │   │   ├── tflite_script_detector_0.3.conv_model
    │   │   └── tflite_script_detector_0.3.lstm_model
    │   └── taser_script_identification_tflite_mobile.binarypb
    ├── taser_tflite_gocrlatinconvnext320_mbv2_scriptid_aksara_layout_gro_mobile_engine.binarypb
    ├── taser_tflite_gocrlatinconvnext320_mbv2_scriptid_aksara_layout_gro_mobile_engine_ti.binarypb
    ├── taser_tflite_gocrlatinconvnext320_mbv2_scriptid_aksara_layout_gro_mobile_recognizer.binarypb
    ├── taser_tflite_gocrlatinconvnext320_mbv2_scriptid_aksara_layout_gro_mobile_runner.binarypb
    └── taser_tflite_gocrlatinconvnext320_mbv2_scriptid_aksara_layout_gro_mobile_runner_ti.binarypb

16 directories, 28 files

$ du -s screen_ai/
65520	screen_ai/
```

**Comment by PF4Public** [comment]
> IMO Like other annoy chromium AI functions added by Google in recent years, it eats resources and useless for most of users even blinds because they use other more powerful screen readers.

This must be implemented with the help of tflite library, which we disable in ungoogled-chromium.
