### ISSUE TITLE
Needs a setting or way to enable main menu bar

### ISSUE THREAD

**Issue by ThomasFreedman** [ungoogled-software/ungoogled-chromium#2589]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

Version 118.0.5993.117 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I can find no info anywhere on how to enable the top menu bar

### How to Reproduce?

New installation has no menu bar by default, and I can't find a way to enable it. Not in docs or chrome://flags etc.

### Actual behaviour

No info on how to enable, not obvious if it can be enabled.

### Expected behaviour

ability to show top menu bar

### Relevant log output

```sh
N/A
```

### Additional context

N/A

**Comment by touba-denrael** [comment]
the only function that is not reachable through the existing menu(s) might be the file opening one (ctrl+o).

the "missing" menu bar might be caused by the (supposed) design philosophy of the chromium user interface (do not sacrifice viewing space for things not strictly needed).

**Comment by ThomasFreedman** [comment]
The file open is the main thing I use that menu for!

-------------------------------------------------------------------------
1) This private E-mail including but not limited to any / all attachment(s), are lawfully protected in any public jurisdiction subject to 1a.
2) Nunc pro tunc "Now for Then" (retroactive): All Rights Reserved (Without Prejudice(2a)), Non Assumpsit(2b), and Without the United States(2c)
1a) Electronic Communications Privacy Act, 18 U.S.C. § 2510-2521
2a) Without Prejudice UCC 1-308, UCC 1-306.6, in other words: All Rights Reserved
2b) Non Assumpsit "Did not undertake" (compulsory contracts)
2c) United States as defined by 26 USC § 7701
2c § 7701.9) Legalese: “The United States government is a foreign corporation with respect to a state" (20 C.J.S. Corporations §1785)
2c § 7701.10) Legalese: "include" in Latin: "expressio unius est exclusio alterius" or "to express or include one thing implies the exclusion of the other." Black's Law Dictionary (8th, 9th ed. 2009)
3) The color of the text above designates political jurisdiction: red-private non-statutory, flesh and blood, man / woman, blue-administrative, admiralty law, corporate jurisdiction. These are also pen ink colors and are significant on legal documents. Underlined text are links to further information.

**Comment by touba-denrael** [comment]
> file open is the main thing

every [nearly every?] operating system uses the ctrl+o key combination for opening files in every [nearly every?] application.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
