### ISSUE TITLE
No option to clear cookie when exit

### ISSUE THREAD

**Issue by NightBright199** [ungoogled-software/ungoogled-chromium#2590]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

OS/Platform's package manager

### Version

119.0.6045.105

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

No option to clear cookies when exit

### How to Reproduce?

Install via Discover in KDE

### Actual behaviour

No option to clear cookies when exit

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/70122416/6dc2c3ea-25d6-4ef8-ac79-7da2b0b8bbf9)

Everytime I close the browser It will always delete cookie

### Expected behaviour

An option to clear cookies when exit

### Additional context

Using all the other cookies option doesn't work
Disabling Do Not Track doesn't work
Resetting Browser doesn't work

**Comment by touba-denrael** [comment]
here is hoping this will solve your problem: setting chrome://flags/#clear-data-on-exit [clears all browsing data on exit] as "enabled".

**Comment by NightBright199** [comment]
didn't work at all

**Comment by PF4Public** [comment]
Please clarify what does "Install via Discover in KDE" mean? Is it using deb package? Is it using binaries? Which?

**Comment by NightBright199** [comment]
flatpak

**Comment by PF4Public** [comment]
@rany2 Is this issue reproducible for you?

**Comment by maskimfr** [comment]
Hello
Same issue on arch linux with 3 different sources :
  - [https://aur.archlinux.org/packages/ungoogled-chromium](https://aur.archlinux.org/packages/ungoogled-chromium)
  - [https://aur.archlinux.org/packages/ungoogled-chromium-bin](https://aur.archlinux.org/packages/ungoogled-chromium-bin)
  - flatpak

**Comment by touba-denrael** [comment]
> didn't work at all

sorry [blushes]

**Comment by NightBright199** [comment]
it's oki :)

**Comment by berkley4** [comment]
Some of the old cookie functionality can be found via clicking: Privacy and security > Site settings > Additional content settings > On-device site data.

Bookmarking chrome://settings/content/siteData is probably easier.

**Comment by Ahrotahn** [comment]
An upstream change as part of their third party cookie deprecation is the cause.  I have a fix ready but I'll wait until a bit later today to make a PR in case they make a point release.

**Comment by thcrt** [comment]
> here is hoping this will solve your problem: set the flag chrome://flags/#clear-data-on-exit [clears all browsing data on exit] as "enabled".

This would _enable_ this functionality, when @NightBright199 wants to _disable_ it. The issue title is worded unclearly. 

> Bookmarking chrome://settings/content/siteData is probably easier.

Also experiencing this on Arch. I can confirm that @berkley4's solution works. 

> sorry [blushes]

[wonders why we're roleplaying on an issue tracker] fair enough i guess

**Comment by Krabbenhoft** [comment]
Had the same problem, thanks for fixing it.
