### ISSUE TITLE
Gentoo build issue for 119.0.6045.105 (visual_search.mojom.h)

### ISSUE THREAD

**Issue by parazyd** [ungoogled-software/ungoogled-chromium#2591]
### OS/Platform

Gentoo

### Installed

Compiled from source

### Version

119.0.6045.105

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

The build fails due to an ungenerated header

### How to Reproduce?

1. Patched ffmpeg to expose the necessary function
2. Emerge:
```
USE="X -bluetooth -cfi clang -convert-dict -gtk4 -hevc -headless -enable-driver -nvidia official optimize-thinlto optimize-webui -override-data-dir pax-kernel pgo proprietary-codecs -pulseaudio qt5 qt6 -screencast -system-abseil-cpp system-av1 system-brotli system-crc32c system-double-conversion system-ffmpeg system-harfbuzz system-icu system-jsoncpp system-libevent system-libusb system-libvpx system-openh264 system-openjpeg system-png -system-re2 system-snappy system-woff2 system-zstd thinlto -uazo-bromite -vaapy -wayland -widevine emerge ungoogled-chromium
```

### Actual behaviour

The build fails with the following:

```
In file included from ../../chrome/browser/ui/webui/chrome_untrusted_web_ui_configs_de
sktop.cc:14:
In file included from ../../chrome/browser/ui/webui/side_panel/companion/companion_sid
e_panel_untrusted_ui.h:10:
In file included from ../../chrome/browser/ui/webui/side_panel/companion/companion_pag
e_handler.h:15:
In file included from ../../chrome/browser/companion/visual_search/visual_search_class
ifier_host.h:12:
../../chrome/browser/companion/visual_search/visual_search_suggestions_service.h:10:10
: fatal error: 'chrome/common/companion/visual_search.mojom.h' file not found
   10 | #include "chrome/common/companion/visual_search.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Expected behaviour

I had expected compilation to be successful.

**Comment by PF4Public** [comment]
Full build log, please.

**Comment by PF4Public** [comment]
This looks like a race condition in chromium sources unrelated to ungoogled-chromium patches. Perhaps it was exacerbated due to the fact that you're building in steps because of `pax-kernel`. You could try `FEATURES=keepwork NINJAOPTS="-j16 -k0" emerge ungoogled-chromium` _twice_.

> The build.log is 252 MB so I can't upload it to Github.

You may pack it.

**Comment by parazyd** [comment]
[build.log.txt.gz](https://github.com/ungoogled-software/ungoogled-chromium/files/13278656/build.log.txt.gz)

**Comment by PF4Public** [comment]
Have you attempted building twice?

**Comment by parazyd** [comment]
Just doing so now, will update here when finished.

**Comment by parazyd** [comment]
It succeeded with `FEATURES=keepwork NINJAOPTS="-j16 -k0" emerge ungoogled-chromium` twice.

**Comment by PF4Public** [comment]
So it was indeed a race condition. If that happens again you could use a user patch to fix this locally.
