### ISSUE TITLE
Cannot Download & Install Extensions From the Google Webstore: "Installation currently unavailable"

### ISSUE THREAD

**Issue by Bj007pro** [ungoogled-software/ungoogled-chromium#2605]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 119.0.6045.105 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [x] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Google Webstore: Installation currently unavailable

### How to Reproduce?

1, Go to Google's Webstore.
2. Click on any Chrome extension. 

### Actual behaviour

Cannot download & install Chrome/Chromium extensions from the Google webstore due to error.

### Expected behaviour

To be able to download & install Chrome/Chromium extensions from the Google webstore because this web browser is a Chromium-based web browser.

### Additional context

I literally downloaded Ungoogled 3 days ago for a little more info,

**Comment by touba-denrael** [comment]
possible reading material: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore

**Comment by h-e-l-o** [comment]
This must be something new, I do have the chromium-web-store extension activated and was always able to instlal extensions from the web store.
