### ISSUE TITLE
Youtube app trouble

### ISSUE THREAD

**Issue by Youlooklikescoobydoo** [ungoogled-software/ungoogled-chromium#2613]
Sorry if this is a silly issue, I accidentally clicked on "Install" while there was a popup on the Youtube home page asking if I wanted to install the Youtube app (I was a little tired and my body reacted before my mind could) and now I don't know how to uninstall the app from my PC.

Surely this can be fixed quickly but I couldn't find a solution within the features I searched into.

**Comment by tomasz1986** [comment]
Please check https://support.google.com/chrome/answer/9658361 and specifically the "Uninstall" section.

**Comment by Youlooklikescoobydoo** [comment]
Ok, so for some reason that Uninstall option wouldn't appear and had to go for the manual way. I think that should be one thing to change sometime later.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
