### ISSUE TITLE
iCloud Passwords extension error - cannot retrieve OS version

### ISSUE THREAD

**Issue by corentinartaud** [ungoogled-software/ungoogled-chromium#2621]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

118.0.5993.117

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

iCloud Passwords extension cannot retrieve OS version.

### How to Reproduce?

1. Make sure you have macOS Sonoma installed.
2. Install iCloud Passwords from https://chromewebstore.google.com/detail/pejdijmoenmkgeppbflobdenhhabjlaj
3. (Optional) Pin extension for easy access
4. Click on extension. Warning: ``This extension requires macOS Sonoma to be installed.``

### Actual behaviour

When you click on the extension, the following error appears even though the correct macOS version is installed. Sometimes, you can see the image attached in ``Expected behavior``briefly, but it quickly reverts back to the warning.

<img width="379" alt="Screenshot 2023-12-01 at 17 15 31" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/26491992/e810c988-2a38-47a5-ab1a-a11d3b9c5610">

### Expected behaviour

When you click on the extension, the following should be shown (with macOS Sonoma installed), and a pop-up from macOS should showcase the verification code.

<img width="378" alt="Screenshot 2023-12-01 at 17 46 03" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/26491992/44b84e1a-a6d3-4395-8604-e2cd4a5b9bbe">

### Additional context

Installed through ``brew install --cask eloston-chromium``

**Comment by spasquesi19** [comment]
I'm having the same issue. Any luck?

**Comment by grndis** [comment]
Same here. Is there any way to tweak it?

**Comment by PF4Public** [comment]
See the solution in https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/144#issuecomment-1913176798
