### ISSUE TITLE
Media playback

### ISSUE THREAD

**Issue by GaryElshaw** [ungoogled-software/ungoogled-chromium#2637]
### OS/Platform

Arch Linux

### Installed

Flatpak

### Version

Version 120.0.6099.109 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Video media will not play on Twitter

### How to Reproduce?

Go to Twitter.com
Press play on any video content

### Actual behaviour

Reloading page has no effect, and after a while, ungoogled-chromium will ask to close the page or the media play button when clicked does nothing

### Expected behaviour

Media playback will start when clicked

### Additional context

This is new behaviour i've not seen in previous versions. And no system changes between versions of ungoogled-chromium.

![Screenshot from 2023-12-15 12-55-54](https://github.com/ungoogled-software/ungoogled-chromium/assets/69029666/9fa512a5-f04a-4e4b-a321-3de9f8da5cae)

**Comment by networkException** [comment]
I can reproduce this, but only on flatpak it seems (the nix build displays videos just fine)

**Comment by networkException** [comment]
@rany2 any idea what this could be?

**Comment by GaryElshaw** [comment]
Thanks for confirming @networkException

**Comment by rany2** [comment]
@GaryElshaw Wait a few hours for https://github.com/flathub/com.github.Eloston.UngoogledChromium/pull/153 to make it to Flathub, after build it takes a few hours for it to be distributed.

**Comment by GaryElshaw** [comment]
Many thanks @rany2.

**Comment by GaryElshaw** [comment]
Updated and working great, thanks again @rany2.
