### ISSUE TITLE
Command line option to disable "Clear cookies and site data when you close all windows"

### ISSUE THREAD

**Issue by yunfachi** [ungoogled-software/ungoogled-chromium#2638]
### Description

Option to disable "Clear cookies and site data when you close all windows"

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Makes it possible to disable this setting through options. This will be useful when using --app

### Possible solutions

Option to disable it

### Alternatives

Patch to disable [prefs-only-keep-cookies-until-exit.patch](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/iridium-browser/prefs-only-keep-cookies-until-exit.patch)

**Comment by PF4Public** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-do-i-have-to-login-to-websites-every-time-i-open-ungoogled-chromium

**Comment by yunfachi** [comment]
> https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-do-i-have-to-login-to-websites-every-time-i-open-ungoogled-chromium

how can I turn it off using the options? I need this because I'm using ungoogled-chromium with --app

**Comment by PF4Public** [comment]
> how can I turn it off using the options?

As you would usually do this.

**Comment by yunfachi** [comment]
> As you would usually do this.

I created this pr because there is no such thing in ungoogled-chromium

**Comment by touba-denrael** [comment]
> how can I turn it off using the options? I need this because I'm using ungoogled-chromium with --app

chrome://settings/cookies takes one to this screen:
![ugc_screenshot_2023-12-15_13-04-50](https://github.com/ungoogled-software/ungoogled-chromium/assets/141708363/c253e5f8-31f3-4782-acc7-a46685b3c85a)
where you can unselect the setting.

**Comment by yunfachi** [comment]
> where one can unselect the setting.

I mean command line options

**Comment by yunfachi** [comment]
> If you turn it off in the options screen, it will also be turned off when you launch Chromium "with --app" next time. This setting is saved to your Chromium profile.

I'm using ungoogled-chrome in app (or kiosk) mode. this means that I don't want to force users to change this setting manually, I want a command line option for this

**Comment by PF4Public** [comment]
> I'm using ungoogled-chrome in app (or kiosk) mode. this means that I don't want to force users to change this setting manually, I want a command line option for this

Your options are:
* Submit PR with this option exposed via commandline for a review
* Patch ungoogled-chromium locally while building to change the default
* Use another browser, which has this enabled by default
