### ISSUE TITLE
Hide side panel advertisement in the bookmarks folder

### ISSUE THREAD

**Issue by opzch** [ungoogled-software/ungoogled-chromium#2644]
### Description

Remove annoying feature advertisement

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Chromium sometimes displays awful blue banners advertising tab groups, password manager, and other features, but at least they appear only on new profiles and can be dismissed. Someone not happy with this decided to shove the side panel trash instead of the bookmark bar more aggressively by placing this item on top of the "Other bookmarks" folder:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/99139463/51a3ffab-4620-47a2-bf2d-b38f3026a8f5)

It just stays there permanently, as if the side panel icon is not enough.

If there's a flag for disabling the side panel icon (#hide-sidepanel-button), there also should be one for hiding other ways to open it. The #power-bookmarks-side-panel allowed it, but has expired.

### Possible solutions

Reintroduce expired "Power Bookmarks side panel" flag.

or

Introduce a flag for disabling all advertisements like this (I'm pretty sure they will not stop and will add only more similar garbage).

### Alternatives

Staying on an old version, removing all items from the "Other bookmarks" folder or refusing to use bookmarks.

### Additional context

A search for "Power Bookmarks Side Panel" or "Open Side Panel to see All Bookmarks" will show that many people are frustrated by these changes and want a way to remove this shortcut.

**Comment by BOY0038v2** [comment]
same problem, still no solution in version 120.0.6099.129-1
