### ISSUE TITLE
Any version of the installer closes after few seconds on Windows x64

### ISSUE THREAD

**Issue by marcello-pietrobon** [ungoogled-software/ungoogled-chromium#2663]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

ungoogled-chromium_120.0.6099.199-1.1_installer_x64.exe

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

the installer closes after few seconds

### How to Reproduce?

doubleclick on the installer

### Actual behaviour

you see a blue dot for few seconds
the installer closes with no message of any kind, not even in the windows' events log

### Expected behaviour

I'm expecting the installer to give at least a message informing why is not able to run or at least that it found an issue.

### Relevant log output

```sh
Couldn't find any log related to the issue
```

### Additional context

I've tried the installer on two computers running windows 10 pro 22h2 and the behavior is identical. In both I was able to install chromium one month ago, but now now and I wonder why, In one of them the OS itself is a quite clean install with almost nothing installed in it (only total commander, everything, and notepad++) and after that it was shut down and never used. There's no antivirus except Windows Defender but nothing has been set or done on it.

I wonder if there's any way to find out why the installer closes.

**Comment by marcello-pietrobon** [comment]
P.S. I've tried also many previous versions of the installers to no avail.

**Comment by PF4Public** [comment]
Duplicate of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/160?
