### ISSUE TITLE
domain "twitch.tv" not fully supported

### ISSUE THREAD

**Issue by Dounial** [ungoogled-software/ungoogled-chromium#2676]
### Description

This is a feature request/bug report - the login on the domain twitch.tv is not supported, it seems to not recognize ungoogled chromium as a chromium-browser, with the usual chromium the log-in works

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

This is a feature request/bug report - the login on the domain twitch.tv is not supported, it seems to not recognize ungoogled chromium as a chromium-browser, with the usual chromium the log-in works

### Possible solutions

A implementation/fix or trying to contact twitch.tv and trying to find a solution together

**Comment by Dounial** [comment]
Sorry - here are inromations I haop can be usesul:
The error-message is this while tryinto log onto twitch;

**Comment by rmdhnreza** [comment]
I believe this is an error, what @Dounial meant was.

![5ac749fbeec93607fc28d666be85e73a](https://github.com/ungoogled-software/ungoogled-chromium/assets/23427492/3ff07c42-04cd-4f87-891d-27247a7d0b88)

---

But, I experienced on other browsers also, such as: Brave, Google Chrome & Firefox, sometimes clearing cache & cookie solved the problem sometimes not.

Try disabling all your extensions, if still can't log in, login with another browser and export cookies.

**Comment by Dounial** [comment]
> I believe this is an error, what @Dounial meant was.
> 
> ![5ac749fbeec93607fc28d666be85e73a](https://private-user-images.githubusercontent.com/23427492/298317294-3ff07c42-04cd-4f87-891d-27247a7d0b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDM1NzYsIm5iZiI6MTcwNTgwMzI3NiwicGF0aCI6Ii8yMzQyNzQ5Mi8yOTgzMTcyOTQtM2ZmMDdjNDItMDRjZC00Zjg3LTg5MWQtMjcyNDdhN2QwYjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAyMTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YmM1MTEwODE3ZTQ4MDFhMTg4OGVkNjMxNWUyOGU1MTVkNmNlNTM4YmJmNDQwOGY5MjhiNzIxZTQxODgzZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrjD7hC_0_IciEsGu_uOfDEbgFfEaB87uWuyPtzq_pc)
> 
> But, I experienced on other browsers also, such as: Brave, Google Chrome & Firefox, sometimes clearing cache & cookie solved the problem sometimes not.
> 
> Try disabling all your extensions, if still can't log in, login with another browser and export cookies.

Tnank you, I believed it was a ungoogled-chroium-problem only
