### ISSUE TITLE
WebGLRenderer error: can't load websites like thunderproxies.com 

### ISSUE THREAD

**Issue by philinp** [ungoogled-software/ungoogled-chromium#2677]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

120.0.6099.238

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

can't load thunderproxies.com

### How to Reproduce?

1. go to thunderproxies.com
2. it should load normally, but it's not

### Actual behaviour

thunderproxies.com is not loading.
console shows error: 
function xe(e) { console.error("THREE.WebGLRenderer: A WebGL context could not be created. Reason: ", e.statusMessage)
 

### Expected behaviour

thunderproxies.com loading ok

**Comment by PF4Public** [comment]
Why would a proxy service need WebGL? Is it fingerprinting its customers? I highly doubt it is an issue of ungoogled-chromium, ask their support.

**Comment by philinp** [comment]
i don't know. but i found about 5 more websites that have the same issue.
