### ISSUE TITLE
Default light theme and preinstalled uBlock Origin

### ISSUE THREAD

**Issue by torontal7** [ungoogled-software/ungoogled-chromium#2680]
### Description

Set light theme (both for normal and incognito mode) and install  uBlock Origin by default

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Yesterday I downloaded ungoogled-chromium_120.0.6099.129-1.1.AppImage. After starting it, I learned that it uses dark theme (both for normal and incognito mode) and there is no possiblity to change to light. Well, I do not want to destroy my eyes, and of course there are other people in the same situation.
I looked at issues and found
https://github.com/ungoogled-software/ungoogled-chromium/issues/1928
and tried the "solution", setting
`chrome://flags/#enable-incognito-themes`
to enabled and also
`chrome://flags/#enable-force-dark`
to disabled and then restart but nothing changed: the browser is still in dark mode and in settings no possibility to change to light.

The other problem: Nowdays practically without uBlock Origin you cannot use the internet: 100% CPU load, annoying ads, time waste, you cannot see the real content, etc.

### Possible solutions

Set light theme by default both for normal and incognito mode. And in incognito mode that dark new tab page must be replaced with a light one, too.

Install uBlock Origin by default for every ungoogled-chromium release. And of course enabled also in incognito mode by default.

### Alternatives

To not use Chromium at all...

### Additional context

No idea, what to write here...

**Comment by PF4Public** [comment]
Please select the proper issue template and fill all fields.

**Comment by torontal7** [comment]
I do not understand: which template to select, why is this good? And what to fill? The "possible solution"? Do you think if I knew the solution would have created this issue...?

**Comment by torontal7** [comment]
> Please select the proper issue template and fill all fields.

The  issue template was OK, but now it is not. Can you explain why you removed the original label? What additional indo you need? I explained clearly what is the problem and also what would be the solution.
Take a look at this issue:
https://github.com/ungoogled-software/ungoogled-chromium/issues/2673
Here even less indo was provided but the labels were not removed and they understood the problem. What is in my description that you cannot understand?

**Comment by PF4Public** [comment]
* If that's an issue with light/dark theme, you should've chosen "Bug Report" template.
* "The other problem" ← you should not mix multiple issues into one report. Please decompose them into separate ones.
* "Install uBlock Origin by default" ← This has been discussed a lot, please use the search function to find more details
* "it uses dark theme (both for normal" ← this statement is false, see the screenshot below (please note that my usual installation is set to dark, but newly opened window with empty profile takes the light theme)

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/0b6cc452-c9b7-481e-a7d3-fbf655ea1498)

**Comment by torontal7** [comment]
> If that's an issue with light/dark theme, you should've chosen "Bug Report" template.

I assumed that intentionally was made so.

> "The other problem" ← you should not mix multiple issues into one report. Please decompose them into separate ones.

Yes, I know this rule but I thought 2 problems are not so much...

> "Install uBlock Origin by default" ← This has been discussed a lot, please use the search function to find more details

I did search but not found an issue with this sepicific request. I admit that it could be mentioned among others.
is:issue is:open uBlock Origin :
Disaster : discrimination huge bug with heavy ads and crypto mining
https://github.com/ungoogled-software/ungoogled-chromium/issues/2066
Add flag to hide installed extensions for websites
https://github.com/ungoogled-software/ungoogled-chromium/issues/2008
Is there any way to remove any Google related text in the browser?
https://github.com/ungoogled-software/ungoogled-chromium/issues/900
DNS-lookup(and https connect) of single-word searches done in omnibar is happening
https://github.com/ungoogled-software/ungoogled-chromium/issues/814
The future of content filtering (declarativeNetRequest, Manifest v3, and beyond)
https://github.com/ungoogled-software/ungoogled-chromium/issues/662

But what matters that it is not preinstalled. Unfortunately.

> "it uses dark theme (both for normal" ← this statement is false

Yes, I think understand now what happened. When I tried the appimage I used Legacy OS. And there everything was set to dark mode. It seems that they somehow managed that even an appimage would start with dark theme, even Chromium in "normal" mode. Now, I cannot test this since I am using Knoppix wich is a 32 bit OS. This would be an other problem: appimages are available only for 64 bit Linux (with a few exceptions). But I do not open an issue, it is a general problem, not only for this project...
And in incognito mode? Most of the time I use incognito, so if it cannot set to light, that is still a problem...
