### ISSUE TITLE
Remove Third party cookie consent feedback from the menu

### ISSUE THREAD

**Issue by opzch** [ungoogled-software/ungoogled-chromium#2682]
### Description

Remove "Send Feedback. Help us improve Chrome by telling us why you allowed third-party cookies"

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

When you need to allow third-party cookies for a certain site, Chromium adds a survey to the bottom of the menu, which is already too huge and ugly. Thankfully, it doesn't send anything.

Example site: https://alanhogan.github.io/web-experiments/3rd/third-party-cookies.html

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/99139463/934017d8-f94d-44c9-a652-eeb0e4d73a53)

As most of the garbage nobody asked for, it is of course also accompanied by a blue notification:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/99139463/e34ec53d-4a2a-43c7-8fb3-f814f1ea5453)

### Possible solutions

Include the survey in https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/remove-uneeded-ui.patch

### Additional context

Perhaps this should also be considered as an upstream issue since the survey is shown even if FeedbackSurveysEnabled, MetricsReportingEnabled, or UserFeedbackAllowed policies are set to Disabled.
But it is not functional in ungoogled version, so is worth removing anyway.

**Comment by PF4Public** [comment]
Since they're deprecating third-party cookies maybe they'll remove this upstream eventually?

**Comment by PF4Public** [comment]
> Do you think they will fully remove third-party cookies support and this menu?

Like I've already written: "eventually" :) But indeed it may not happen very soon.
