### ISSUE TITLE
iCloud Password Extesion

### ISSUE THREAD

**Issue by dbrewood** [ungoogled-software/ungoogled-chromium#2685]
### OS/Platform

macOS

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 122.0.6260.0 

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When the extension is clicked upon it fails saying macOS Sonoma is needed

### How to Reproduce?

Install the extension and try to authenticate it. You are informed you must be using macOS Sonoma and are asked to download it. 

### Actual behaviour

See above

### Expected behaviour

For it to prompt you with the 2FA Apple code.

**Comment by dbrewood** [comment]
Apologies for the typo in the title :)

**Comment by auniverseaway** [comment]
@dbrewood I see this is closed, were you able to resolve this? I'm having the same issue.

Thanks!

**Comment by auniverseaway** [comment]
NM. For others looking for the answer, it is here: https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/144#issuecomment-1913176798

**Comment by v-127** [comment]
> NM. For others looking for the answer, it is here: [ungoogled-software/ungoogled-chromium-macos#144 (comment)](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/144#issuecomment-1913176798)

But I tried that and it doesn't work...
