### ISSUE TITLE
Video Problems

### ISSUE THREAD

**Issue by nrcone0** [ungoogled-software/ungoogled-chromium#2686]
### OS/Platform

Windows

### Installed

Compiled from source

### Version

120.0.6099.234

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I cant play youtube videos

### How to Reproduce?

Just by opening a youtube video

### Actual behaviour

I click on any youtube videos and this pops up 
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/100088338/72a24fc3-ce2b-4834-82d1-4e4180c64b35)
And i tried clearing cookies disabling all extensions fully reinstalling switching accounts etc, does not work for me, i got all codecs isntalled.

### Expected behaviour

play the vid

**Comment by PF4Public** [comment]
Perhaps DevTools have something interesting in console.

**Comment by sebastianha** [comment]
Same here, using version 120.0.6099.224 on Linux.

I am getting 403 erros on /videoplayback?...

**Comment by PF4Public** [comment]
> I am getting 403 erros on /videoplayback?...

Server is not happy with you for some reason.

**Comment by sebastianha** [comment]
I know, but I do not know why. Works fine with firefox, but even with a fresh/empty ungoogled-chromium it does not work.

**Comment by PF4Public** [comment]
@nrcone0 @sebastianha Try latest available version.

**Comment by sebastianha** [comment]
I have to wait until it pops up in my repo, but should be in a few days.
I will test as soon as it's available.

**Comment by ChrTall** [comment]
I can confirm the problem on opensuse Tumbleweed, when trying to watch videos on youtube.
Firefox works fine though.
Console Log:
![Screenshot_20240301_190736](https://github.com/ungoogled-software/ungoogled-chromium/assets/55497425/cb2377db-6dba-42f9-92e6-5344b36f44b5)

**Comment by PF4Public** [comment]
Please try starting chromium with `--user-data-dir=/tmp/something`

**Comment by sebastianha** [comment]
I already tried this by deleting the config-dir. Same behaviour.

**Comment by PF4Public** [comment]
Look into the Media tab, perhaps there is something unusual:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/10319700/a31263e7-042e-4a21-b230-31d163eb04d5)

**Comment by ChrTall** [comment]
You are right Decoder and Encoder are missing on my system.
Even though it worked before and I did not remove anything.
OS: openSuse Tumbleweed.
codecs installed with: opi codecs
Firefox should also use shared system libraries and works.

![Screenshot_20240304_211345](https://github.com/ungoogled-software/ungoogled-chromium/assets/55497425/247397d1-6bed-4b7c-9c8e-0632704938bd)

**Comment by PF4Public** [comment]
Try starting it with `--disable-features=FFmpegAllowLists`

**Comment by sebastianha** [comment]
YES! Works for me!

**Comment by PF4Public** [comment]
I assume @Michal-Szczepaniak maintains the build for openSuse. @Michal-Szczepaniak please have a look at this issue. It may be triggered by using system-provided ffmpeg library.

**Comment by Michal-Szczepaniak** [comment]
Ye currently updates for opensuse are kinda halted until other maintainers update chromium as i basically just use the chromium build files and apply ungoogled patches.

Same issue exists in un-ungoogled chromium currently on opensuse

**Comment by ChrTall** [comment]
Workaround `--disable-features=FFmpegAllowLists` also works for me.
Chromium 121 should fix the issue and was released on Factory.
ungoogled-chromium 121 will probably also fix the issue.

**Comment by Michal-Szczepaniak** [comment]
chromium and ungoogled-chromium were just updated to 122 so that should fix all the issues

**Comment by cnleo** [comment]
Same here with Manjaro. Solution for Manjaro: Install `manjaro-pipewire` or reinstall them.

Maybe it is not necessary to install the optional jack(1) stuff, since jack2 is already there.

The magic will happen immediately (video was still in background) and without reboot.
