### ISSUE TITLE
Breaks when you add new extension

### ISSUE THREAD

**Issue by jasursadikov** [ungoogled-software/ungoogled-chromium#2692]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

Version 121.0.6167.85 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When I click on Add to Chromium button in a store, app starts to glitch

### How to Reproduce?

1. Open Google Chrome Web Store
2. Click "Add extension"
3. Enjoy glitches

### Actual behaviour

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/14846427/3168fe44-757a-4d63-94ce-8855065284de)

This is a screenshot of the way this thing looks.

### Expected behaviour

It should simply add an extension :)

**Comment by HenkPoley** [comment]
Not sure if related, but I'm seeing "Item currently unavailable. Please check the troubleshooting guide." when visiting any extension in the Chrome Web Store, for example this page: https://chromewebstore.google.com/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp

Maybe the Chromium Web Store needs an update, e.g.: https://github.com/NeverDecaf/chromium-web-store

**Comment by jasursadikov** [comment]
Well I guess the extension itself that I was trying to install is broken :)
