### ISSUE TITLE
Crash when a PDF tab is open

### ISSUE THREAD

**Issue by k-afonso** [ungoogled-software/ungoogled-chromium#2701]
### OS/Platform

macOS

### Installed

Compiled from source

### Version

121.0.6167.85

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Whenever I have a tab with a PDF file, the app crashes.

### How to Reproduce?

1. Open a normal ungoogled-chromium window with multiple tabs (Gmail, Wikipedia, etc)
2. Open a new tab with a PDF file ( I am currently reading this book -> https://dn790008.ca.archive.org/0/items/TheElementsOfComputingSystems_201408/The%20Elements%20of%20Computing%20Systems.pdf)
3. Open an incognito window with any other page (I open YouTube for music)
4. Use the computer normally but eventually allow the computer to sleep with the PDF file tab open (As if you were reading the PDF file and decided to take a break with the PDF tab on the screen)
5. When I log back in, ungoogled-chromium crashes (It might not crash on the very first try, but it crashes on the 2nd or 3rd)

### Actual behaviour

If I have multiple tabs open on both normal and incognito windows, and I have a tab with a PDF file and allow the computer to go to sleep (auto-lock) on the PDF tab, when I log back in ungoogled-chromium crashes. 

Screenshots:
<img width="1439" alt="Screenshot 2024-02-02 at 05 33 33" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/110848617/31e3b5d4-a659-4993-9bf4-6621f5eaf83a">
<img width="278" alt="Screenshot 2024-02-02 at 06 26 22" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/110848617/56f1cd96-db34-490e-b28a-abf1ec6e7e5b">

It has happened multiple times, and I can't understand why.

### Expected behaviour

It shouldn't crash.

**Comment by k-afonso** [comment]
I couldn't do the step "I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using --user-data-dir command line argument and it could not be reproduced there" because I don't understand how to do the "--user-data-dir" part.

**Comment by PF4Public** [comment]
How did you install ungoogled chromium? I suspect a contradiction here: «Compiled from source» ←→ «I don't understand how to do the "--user-data-dir" part»

**Comment by k-afonso** [comment]
I think that I followed a tutorial on how to install ungoogled chromium. I don't remember what the steps were. I am not very tech-savvy, so I have no idea how to do the third step with the "--user-data-dir" part.

**Comment by PF4Public** [comment]
@Cubik65536 Do you encounter such crash on your system?

**Comment by Cubik65536** [comment]
> @Cubik65536 Do you encounter such crash on your system?

No

**Comment by Cubik65536** [comment]
Sorry I was in a rush, I haven’t experienced anything like this, but I will try to reproduce this later this week just following these instructions.

**Comment by Cubik65536** [comment]
By the way, @k-afonso can you update to the latest version of Ungoogled Chromium just to make sure this situation still exists? And please send a more detailed information (Mac Model, macOS version) about your device.

**Comment by k-afonso** [comment]
I updated to the latest version of Ungoogle Chromium and I repeated the situation. After I logged back in, I managed to still use Chromium for about 3 minutes until it crashed again. 

I took some screenshots of the crash report. I don't know if there is any sensible information in the report that I shouldn't share publicly. If you guys think that it is safe to share the full report here, I can make a .txt file and send it.

<img width="982" alt="Screenshot 2024-02-06 at 18 14 44" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/110848617/07086042-86b4-4cb3-bf3a-958ccc9a465a">
<img width="981" alt="Screenshot 2024-02-06 at 18 14 59" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/110848617/269020c8-5c16-455b-b329-3518447f167c">

**Comment by Cubik65536** [comment]
Sadly I can't duplicate this issue on my side following these steps:

1. Open some webpages.
2. Open the PDF
3. Open an incognito window.
4. Wait till the Mac sleeps.
5. Wake the Mac.

**Comment by PF4Public** [comment]
Could there be any significant differences between architectures? @k-afonso seems to be using arm.

**Comment by Cubik65536** [comment]
> Could there be any significant differences between architectures? @k-afonso seems to be using arm.

I am testing on an ARM machin.

**Comment by k-afonso** [comment]
@Cubik65536 is the computer going to sleep with the PDF page on the screen? As if you were reading and decided to take a break. Sometimes it doesn’t crash right away once you log back in. It can take 1-3 minutes of normal browser use. I can send the full crash report if you guys think that it is safe and it might be useful.

**Comment by Cubik65536** [comment]
I have the PDF opened… You can send the crash report (it usually doesn’t contain any sensitive info), but I doubt if it will really help in our case (where we basically just add patches to another software).

**Comment by k-afonso** [comment]
Crash report: 
[Report.txt](https://github.com/ungoogled-software/ungoogled-chromium/files/14217602/Report.txt)

**Comment by Cubik65536** [comment]
Yeah I can say it's not very useful...

I'll try to duplicate it again and if it's still not working then I don't know what can we do in a short term...

It might even be a device specific issue, which will be hard to diagnose.

**Comment by k-afonso** [comment]
Okay, I understand.
Thank you guys for trying to help.

**Comment by k-afonso** [comment]
@PF4Public Hi, I tried reproducing the bug several times and I couldn't. I guess it's fixed in this later version. 
Thank you guys for your great help!

**Comment by k-afonso** [comment]
The bug seems to be fixed in the most recent version 122.0.6261.111-1. 
If anyone experiences the same (or a similar) bug, try updating to the most recent version available.
