### ISSUE TITLE
Add swisscows.com search engine

### ISSUE THREAD

**Issue by DeivAstra** [ungoogled-software/ungoogled-chromium#2712]
### Description

No tracking, Anonymous Family-friendly search engine

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hello,
My suggestion is add Swisscows search engine to list of search engines.
[https://swisscows.com/](https://swisscows.com)

From wikipedia:
Swisscows is a [web search engine](https://en.wikipedia.org/wiki/Web_search_engine) launched in 2014, a project of Hulbee AG, a company based in [Egnach, Switzerland](https://en.wikipedia.org/wiki/Egnach,_Switzerland).[[1]](https://en.wikipedia.org/wiki/Swisscows#cite_note-1)[[2]](https://en.wikipedia.org/wiki/Swisscows#cite_note-2) It uses [semantic data recognition](https://en.wikipedia.org/wiki/Semantic_search) that gives faster answers to queries and claims to not store users' data.[[3]](https://en.wikipedia.org/wiki/Swisscows#cite_note-:1-3)[[4]](https://en.wikipedia.org/wiki/Swisscows#cite_note-4)[[5]](https://en.wikipedia.org/wiki/Swisscows#cite_note-5) Swisscows also deems itself [family-friendly](https://en.wikipedia.org/wiki/Family-friendly), with explicit results entirely omitted.[[3]](https://en.wikipedia.org/wiki/Swisscows#cite_note-:1-3)[[6]](https://en.wikipedia.org/wiki/Swisscows#cite_note-6)[[7]](https://en.wikipedia.org/wiki/Swisscows#cite_note-:0-7) The engine's servers are based in underground [data centers](https://en.wikipedia.org/wiki/Data_center) under the [Swiss Alps](https://en.wikipedia.org/wiki/Swiss_Alps), and geographically outside of [EU](https://en.wikipedia.org/wiki/European_Union) and [US](https://en.wikipedia.org/wiki/United_States).[[8]](https://en.wikipedia.org/wiki/Swisscows#cite_note-8)

[https://en.wikipedia.org/wiki/Swisscows](https://en.wikipedia.org/wiki/Swisscows)

### Possible solutions

URL with %s in place of query:
`https://swisscows.com/en/web?query=%s`

**Comment by PF4Public** [comment]
>How does the anonymous search engine Swisscows earn its money?
>These ads appear exclusively based on your own search query, which is submitted to Bing.

**Comment by touba-denrael** [comment]
is the page chrome://settings/searchEngines for adding one's own choice[s] of search engine[s] not sufficient any more?

**Comment by DeivAstra** [comment]
> is the page chrome://settings/searchEngines for adding one's own choice[s] of search engine[s] not sufficient any more?

No, I do so always, also you can install a swisscows.com browser extension.
swisscows is just another search engine, I had suggest just a new default option.

**Comment by DeivAstra** [comment]
> > How does the anonymous search engine Swisscows earn its money?
> > These ads appear exclusively based on your own search query, which is submitted to Bing.

I don't know what about you mean. How swisscows anonymous or secure it's not a topic of this issue.
Thanks.

**Comment by PF4Public** [comment]
> I don't know what about you mean.

I'll close this issue as this search engine's monetisation strategy does not apparently (as I mentioned) strictly align with its goals. Anyone willing to have it nonetheless has the opportunity to add it into their own profile.
