### ISSUE TITLE
Google Meets: Cannot share entire screen.

### ISSUE THREAD

**Issue by Hannsek** [ungoogled-software/ungoogled-chromium#2715]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

Version 121.0.6167.160 (Official Build, ungoogled-chromium) (arm64)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Cannot share entire screen in google meets even though all permissions are allowed. Sharing any chromium tab or window is without any problem.

### How to Reproduce?

1. Go to meets.google.com and start a meet.
2. click on "share screen"
3. Chromium would tell you it doesn't have permission: 
<img width="463" alt="image" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/57008159/ab0b0c67-7814-4f9e-87ff-410e9325b987"> even it is allowed: 
<img width="467" alt="image" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/57008159/c3ab2ace-9ae8-4609-9f14-8d56bfd903c2">

4. deny it and go to "entire screen" tab
<img width="587" alt="image" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/57008159/05c2bdcd-c733-4295-b374-fd5c3b61e0ef">
5. click "share" and see the error

### Actual behaviour

Cannot share entire screen.

### Expected behaviour

Sharing entire screen should be possible

### Additional context

[Workaround](https://github.com/ungoogled-software/ungoogled-chromium/issues/601#issuecomment-1923712800) worked until now. After updating to 121.0.6167.160 it doesn't work. However, it changes the error message to _You can't share your screen. If you want to share a screen, you need to grant permissions._

**Comment by PF4Public** [comment]
@Cubik65536 Were you be able to reproduce this issue?

**Comment by Cubik65536** [comment]
> @Cubik65536 Were you be able to reproduce this issue?

I am a bit busy these days (doing a hackathon), I will investigate it later.

**Comment by Cubik65536** [comment]
@Hannsek Can you try to remove Chromium completely from the permission settings and go through the sharing process again to see if it works? Allow it when it prompts you to.

**Comment by Hannsek** [comment]
@Cubik65536 I did and it works now. Thanks.
