### ISSUE TITLE
Site information dialog always show full URL instead of only domain (like Chrome)

### ISSUE THREAD

**Issue by kkocdko** [ungoogled-software/ungoogled-chromium#2721]
### OS/Platform and Version

Portable Linux 121.0.6167.184 https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### How to Reproduce?

Picture 1: Official Google Chrome.

Picture 2: Ungoogled Chromium. Both address bar "Always show full URLs" on/off.

Picture 3: Ungoogled Chromium with a very long URL. The under entries will be **out of screen and unable to access anymore**.

![Screenshot_2024-02-19_00-55-59](https://github.com/ungoogled-software/ungoogled-chromium/assets/31189892/7c924a70-978a-40ed-ae25-056e7760575d)

### Expected behaviour

Like Official Google Chrome.

**Comment by PF4Public** [comment]
@kkocdko Have you attempted to reproduce this issue in the latest available version? Is this still an issue?

**Comment by kkocdko** [comment]
@PF4Public Yes, this is still an issue.

Chromium 128 (google build) - Ungoogled Chromium 125

```
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1315554%2Fchrome-win.zip?generation=1718425628787761&alt=media

https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/125.0.6422.141-1.1/ungoogled-chromium_125.0.6422.141-1.1_windows_x64.zip

```

![screenshot-new](https://github.com/ungoogled-software/ungoogled-chromium/assets/31189892/86f92c0a-ecda-4fa9-933d-08c8986bfd08)

**Comment by PF4Public** [comment]
I suspect `patches/extra/ungoogled-chromium/disable-formatting-in-omnibox.patch` might influence this. 

@Ahrotahn @networkException @teeminus @clickot @rany2 Is it important for us to fix this?

**Comment by networkException** [comment]
I don't really mind this to be honest

**Comment by Ahrotahn** [comment]
That's something that I have been meaning to take a look at when I get some time.  There were other issues where people wanted to be able to disable the full url in the locationbar and both problems could be solved by handling the changes in that patch differently.  It doesn't bother me either, which is why I haven't gotten around to looking into this yet.  I'll try to keep it in mind next time I get some free time to work on it.

**Comment by teeminus** [comment]
> I don't really mind this to be honest

Same...
