### ISSUE TITLE
Black line over the topbar of web apps

### ISSUE THREAD

**Issue by Radical4ever** [ungoogled-software/ungoogled-chromium#2722]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

121.0.6167.184 

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

A black line over the top bar of web apps

### How to Reproduce?

1. make a webapp
2. open it
3. black line is shown most of the time except when you put the window on fullscreen
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/d692a314-cc7f-493a-bfe7-3215dc5cbabd)

### Actual behaviour

when you run the app that black line  is shown on the topbar

### Expected behaviour

it should not, it must be transparent so the top bar and the body of the app look like an actual one

### Additional context

Its strange how sometimes open the app again the line disappears but when i make the window size bigger the line goes back

**Comment by PF4Public** [comment]
Which flags have you changed in your profile from the default?

**Comment by Radical4ever** [comment]
All of these haha:
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/e03a24bd-30fc-4f53-8bff-d17663142d07)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/8769c8b2-1f49-445c-8324-bda7ed652bb1)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/750f2fae-844c-4b79-8523-a9651cfeaaa8)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/c00dedaf-fce9-45d3-8ae2-b40d8e765d53)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/e06238c8-403c-4ef9-8f5b-fca0c134d3cd)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/54648938-688f-4a29-a0cc-acaab1a37551)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/26c68859-4f62-4c9a-bcde-a7bb17fb9cfb)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/bbd98271-62cd-451e-95c3-c88f47d02e85)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/944c14fb-ab86-4a54-a9ae-6c070f90c672)
![imagen](https://github.com/ungoogled-software/ungoogled-chromium/assets/83252104/22078f81-0b6d-4959-aa26-64626e75d988)

**Comment by PF4Public** [comment]
Well, I guess, you know what to do :) Revert them to default one-by-one until you find the one that breaks everything :))))) You can also at the same time add more into empty profile until it also breaks.

**Comment by Radical4ever** [comment]
> Well, I guess, you know what to do :) Revert them to default one-by-one until you find the one that breaks everything :))))) You can also at the same time add more into empty profile up to the point when it also breaks.

Ok so i got it quickly the flag that causes that black line is "Chrome Refresh 2023"

**Comment by Radical4ever** [comment]
now the real question is how to keep the option enabled and dont have that bug on the webapps?

**Comment by PF4Public** [comment]
Have you searched Chromium bugtracker? Maybe there is something useful or a workaround at least.

**Comment by Radical4ever** [comment]
> Have you searched Chromium bugtracker? Maybe there is something useful or a workaround at least.

there's no actual fix to this, only disabling the new design fixes this, google forums dont say much usefull rather than the basic reinstall chrome, but its something totally related with the new design.
