### ISSUE TITLE
YouTube Full Screen Issue

### ISSUE THREAD

**Issue by KornineQ** [ungoogled-software/ungoogled-chromium#2725]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

121.0.6167.184

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

YouTube FullScreen fullscreens only on page not on screen

### How to Reproduce?

**1**. Go to https://youtube.com
**2.** Click any video
**3.** Try to fullscreen

### Actual behaviour

YouTube FullScreen fullscreens only on page not on screen
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/84327578/c5c0481a-b86e-4c5e-a7ab-0f0ad94acfb7)

### Expected behaviour

It should fullscreen on entire screen not page

**Comment by tomasz1986** [comment]
Have you tested using a clean profile, or at least in incognito mode with all extensions disabled? I've got a feeling that it may be a case of an extension interfering.
