### ISSUE TITLE
I can type everywhere?

### ISSUE THREAD

**Issue by KornineQ** [ungoogled-software/ungoogled-chromium#2728]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

121.0.6167.184

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I can type everywhere

### How to Reproduce?

1. Click on any text

### Actual behaviour

![image](https://files.catbox.moe/r7kpx8.gif)

### Expected behaviour

It didn't should to type me.
I tried also others browser's and they don't have that issue
![Image](https://files.catbox.moe/x3jsds.gif)

**Comment by berkley4** [comment]
It looks like you've accidentally turned on caret browsing. Try toggling it off by pressing the F7 key.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
