### ISSUE TITLE
missing security feature: ocsp for checking website certs

### ISSUE THREAD

**Issue by pony-montana** [ungoogled-software/ungoogled-chromium#2729]
### Description

add ocsp feature behind a flag

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I undestand the scope of this project and the no-phone-home privacy that it achieves. 
I also read the point about why safe browsing features are removed.
What I ask here is: is the security impact of not querying ocsp justified by the "privacy/transaparency" obtained?

I think that ocsp is different from safe browsing: ocsp is not an arbitrary trusted whitelist controlled by one entity; at least in theory, is a standardized specification with multi-party partecipant. It is still centralized over a small set of entity (and I think that the built-in implementation in chromium heavily query over google servers). But it's still a feature part of the open-web, and it's a protocol that describes a vendor-agnostic way to enanche a security aspect of a web-browser.

What about still build-in this feature in the browser and permit to enable it with a flag?
What are your positions about ocsp features?

### Possible solutions

.

**Comment by PF4Public** [comment]
Duplicate of #2719
