### ISSUE TITLE
Google Search Engine

### ISSUE THREAD

**Issue by goodair220917** [ungoogled-software/ungoogled-chromium#2730]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

122.0.6261.57 (Official Build, ungoogled-chromium) (64 Bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Unable to use Google search engine

### How to Reproduce?

1. Add Google (www.google.com) in settings search engine tab
2. Open a new tab, type anything then search

### Actual behaviour

It goes to "http://0.0.0.123/" when I typed 123 to test.
It goes to "http://test/" when I typed "test" to test it.

### Expected behaviour

It goes to something like "https://www.google.com/search?q=123" when I search 123 for testing

**Comment by PF4Public** [comment]
Actual behaviour is correct. Try changing your search engine in `chrome://settings/search`

**Comment by tomasz1986** [comment]
> 1. Add Google ([www.google.com](http://www.google.com)) in settings search engine tab

"www.google.com" is not enough, you need to add it like this:

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/5626656/89cb0dfa-d040-433c-984b-45df6278c940)

and then set as default (if that's what you want, of course).

**Comment by goodair220917** [comment]
It worked, thx!
