### ISSUE TITLE
Passwords gone after update to Chromium 122.0.6261.94

### ISSUE THREAD

**Issue by Zanzibari** [ungoogled-software/ungoogled-chromium#2739]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

122.0.6261.94

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Every time I close ungoogled-chromium, restart lost all passwords

### How to Reproduce?

1. Import password.csv
2. Close ungoogled-chromium
3. Open ungoogled-chromium
4. No passwords

### Actual behaviour

1. Import password.csv
2. Close ungoogled-chromium
3. Open ungoogled-chromium
4. No passwords

### Expected behaviour

keeping passwords

### Additional context

KDE Neon

**Comment by PF4Public** [comment]
@rany2 Something broken in Flatpak?

**Comment by ungoogled1** [comment]
Perhaps your distro has recently updated to KDE/plasma-6 and you need to add "org.kde.kwalletd6" to the qbus session whitelist (using the kde settings app, or flatseal whatever).

**Comment by Zanzibari** [comment]
Thank you! Issue was solved by recent update :-)
