### ISSUE TITLE
Add 'V8 optimization' setting to per-site privacy-security control.

### ISSUE THREAD

**Issue by Rexadev** [ungoogled-software/ungoogled-chromium#2741]
### Description

Add 'V8 optimization' setting to per-site privacy-security control.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Some sites need JIT

### Possible solutions

Add 'V8 optimization' setting to per-site privacy-security control.

### Additional context

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/241950a6-be01-4b6c-8715-d311547b36e7)

**Comment by touba-denrael** [comment]
v122.0.6261.94 [debian bookworm, portable linux version] shows this possibility:
![ungoogled_chromium_v8_optimiser_screenshot_2024-03-03_07-37-00](https://github.com/ungoogled-software/ungoogled-chromium/assets/141708363/6100cbb8-5303-488d-867b-799589913f81)

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by Rexadev** [comment]
> I hope your question(-s) has(-ve) been answered, otherwise please let us know.
> Closing this issue for now.

No I asking you to add the option to allow site to use V8 optimization from top left

**Comment by PF4Public** [comment]
> No I asking you to add the option to allow site to use V8 optimization from top left

If you or anyone else would be willing to submit a PR, we'd love to review it.

**Comment by Rexadev** [comment]
@PF4Public Add a need contributor tag instead of closing the issue please

**Comment by PF4Public** [comment]
> @PF4Public Add a need contributor tag instead of closing the issue please

It would make no difference, they keep piling up without being addressed: https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+label%3A%22help+wanted%22+
