### ISSUE TITLE
Can NOT switch between Dark mode and Light Mode , need this setting in theme

### ISSUE THREAD

**Issue by Stephenzero** [ungoogled-software/ungoogled-chromium#2743]
**Can NOT switch between Dark mode and Light Mode , need this setting in theme**

**Comment by Stephenzero** [comment]
Can NOT switch between Dark mode and Light Mode , need this setting in theme

**Comment by Stephenzero** [comment]
**because I cannot switch from Dark mode to light Mode**

**Comment by PF4Public** [comment]
Please fill in the issue template so that we could better understand your issue.

**Comment by Stephenzero** [comment]
![d5e8a2469e4ae5785a18e00f7c83d031](https://github.com/ungoogled-software/ungoogled-chromium/assets/34346299/9a82aac3-27b4-4796-a76c-d00d5792e529)

**Comment by Stephenzero** [comment]
see the picture above, the google chrome could click this icon, and switch from themes 

how to do this in ungoogled chrome ? guess you cannot do that

**Comment by touba-denrael** [comment]
on the page `chrome://settings/appearance` one might be able to choose from the different "mode" settings:
![ungoogled_chromium_screenshot_2024-03-04_11-02-43](https://github.com/ungoogled-software/ungoogled-chromium/assets/141708363/2f88eff3-0d79-48bb-aaf9-2e67ddd0c0dd)

**Comment by tomasz1986** [comment]
The page doesn't look like that on Windows (which the person in question seems to be using):

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/5626656/361599d1-b7c0-4eea-b36d-e7ff06b53738)

There are some theme-related settings in `chrome://settings/manageProfile` though:

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/5626656/b7318851-88cd-4c3f-98e3-17ec12c7ba0f)

**Comment by Stephenzero** [comment]
thank you everyone ,  
thanks for your kindly answer,
best wishes

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
