### ISSUE TITLE
Netflix doesn't play

### ISSUE THREAD

**Issue by MatteBucc1991** [ungoogled-software/ungoogled-chromium#2749]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

122.0.6261.115

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Movie on Netflix doesn't play

### How to Reproduce?

1) Go to Netflix
2) Choose a movie
3) Click on play

### Actual behaviour

When i go to Netflix and i choose a movie, it doesn't play but if i change browser i can see the same video. Maybe is it a problem with Widevine?

### Expected behaviour

I have the possibility to see any video on Netflix. Component Widevine is installed in the browser. After i have done the test.

**Comment by PF4Public** [comment]
It would've been great if you glanced through [existing issues](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+netflix) first.
