### ISSUE TITLE
Breaks tests

### ISSUE THREAD

**Issue by apprehensions** [ungoogled-software/ungoogled-chromium#2761]
### OS/Platform

My actual OS is not present in the bug report template.

### Installed

OS/Platform's package manager

### Version

122.0.6261.128

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When applying ungoogled-chromium's patchset to a chromium source, it breaks tests

### How to Reproduce?

1. Fetch Chromium and relevant ungoogled patchset for versions 122.0.6261.128
2. Run `<ninja_out>/bld/base_unittests --test-launcher-bot-mode`

### Actual behaviour

Tests fail.

### Expected behaviour

Tests complete without needing a ignore list.

### Relevant log output

```sh
[6895/6895] All/StatisticsRecorderStarvationTest.StatisticsRecorderNoStarvation/5 (5435 ms)
Retrying 5 tests (retry #0)
[0319/190338.859744:INFO:test_launcher.cc(1192)] Starting [FileUtilTest.PreReadFile_Executable]
[0319/190338.882295:INFO:test_launcher.cc(1192)] Starting [ReadOnlyFileUtilTest.ContentsEqual]
[ RUN      ] FileUtilTest.PreReadFile_Executable
../../base/files/file_util_unittest.cc:4558: Failure
Value of: PreReadFile(test_exe, true)
  Actual: false
Expected: true
[  FAILED  ] FileUtilTest.PreReadFile_Executable (0 ms)
[6896/6900] FileUtilTest.PreReadFile_Executable (0 ms)
[0319/190338.904986:INFO:test_launcher.cc(1192)] Starting [StringUtilTest.MatchPatternTest]
[ RUN      ] ReadOnlyFileUtilTest.ContentsEqual
../../base/files/file_util_unittest.cc:2746: Failure
Value of: ContentsEqual(binary_file, binary_file_same)
  Actual: false
Expected: true
[  FAILED  ] ReadOnlyFileUtilTest.ContentsEqual (0 ms)
[6897/6900] ReadOnlyFileUtilTest.ContentsEqual (0 ms)
[0319/190338.927542:INFO:test_launcher.cc(1192)] Starting [AlternateBucketDistribution/PartitionAllocThreadCacheTest.Bookkeeping/0]
[ RUN      ] StringUtilTest.MatchPatternTest
../../base/strings/pattern_unittest.cc:12: Failure
Value of: MatchPattern("www.9oo91e.qjz9zk", "*.com")
  Actual: false
Expected: true
../../base/strings/pattern_unittest.cc:40: Failure
Value of: MatchPattern(u"www.9oo91e.qjz9zk", u"*.com")
  Actual: false
Expected: true
[  FAILED  ] StringUtilTest.MatchPatternTest (0 ms)
[6898/6900] StringUtilTest.MatchPatternTest (0 ms)
[0319/190338.950140:INFO:test_launcher.cc(1192)] Starting [AlternateBucketDistribution/PartitionAllocThreadCacheTest.Bookkeeping/1]
[6899/6900] AlternateBucketDistribution/PartitionAllocThreadCacheTest.Bookkeeping/0 (0 ms)
[6900/6900] AlternateBucketDistribution/PartitionAllocThreadCacheTest.Bookkeeping/1 (0 ms)
3 tests failed:
    FileUtilTest.PreReadFile_Executable (../../base/files/file_util_unittest.cc:4548)
    ReadOnlyFileUtilTest.ContentsEqual (../../base/files/file_util_unittest.cc:2704)
    StringUtilTest.MatchPatternTest (../../base/strings/pattern_unittest.cc:11)
Tests took 36 seconds.
>>> ERROR: ungoogled-chromium: check failed
>>> ungoogled-chromium: Uninstalling dependencies...
```

### Additional context

I am using Alpine, and building from source.

**Comment by networkException** [comment]
Whats your goal with this? Do you want to see if ungoogled still passes all tests to catch us introducing bugs?

I guess we can adjust domain substitution to ignore tests

**Comment by PF4Public** [comment]
> to not require the need for ignoring tests that ungoogled-chromium breaks, making it easier for people to build ungoogled-chromium (i waited foo hours just to see it fail due to tests) using their package managers

Those two goals are mutually exclusive. As per building instructions for ungoogled-chromium one isn't supposed to run tests. If you're using ungoogled-chromium patches within your _other_ workflow, you're expected to adapt it, say exclude tests for example.

Not breaking tests is admittedly a noble goal. It might however have impact on maintainability of ungoogled-chromium.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by apprehensions** [comment]
I'm not sure it was answered. Tests help gurantee the behavior of Chromium, and the ungoogled-chromium patchset introducing unexpected behavior is unwanted.

Unless there is a specific reason for the behavior to change (such as documentation on why it changed), this shouldn't be closed, as it is a bug, not a question.

**Comment by PF4Public** [comment]
> this shouldn't be closed, as it is a bug

We try to keep those bugs open, upon which we can act somehow. I doubt this one being a priority at this time unfortunately.

**Comment by apprehensions** [comment]
> I doubt this one being a priority at this time unfortunately.

Doesn't this imply maybe one day it can be looked into?

> We try to keep those bugs open

If this bug is unsolvable, or out of scope, then i will agree in that it should be closed.

**Comment by PF4Public** [comment]
@apprehensions I admit testing is important and I'm not implying it being out of scope, it is that no one looked into it yet. Also it might be a non-trivial undertaking considering the amount of changes ungoogled-chromium brings into the code.
