### ISSUE TITLE
Request to add a Hide Experiments Button flag

### ISSUE THREAD

**Issue by calhix** [ungoogled-software/ungoogled-chromium#2767]
### Description

A flag to disable experiments button

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

It would be nice to get rid of the experiments button as well, just like there is a flag to hide sidepanel, profile/avatar, etc.

### Possible solutions

Add flag to disable experiments button

**Comment by touba-denrael** [comment]
if you mean the chrome labs button at `chrome://flags/#chrome-labs`, you can choose the `disable` setting.

**Comment by calhix** [comment]
Ah, missed that, thanks!

-------- Original Message --------

**Comment by lufog** [comment]
They removed this flag -_-

**Comment by lmigfernandes** [comment]
Hey, I'm here for the same reason… they removed the flag.

**Comment by PF4Public** [comment]
> they removed the flag

So is it good or bad? Is it important? Why did you comment on that?

**Comment by dmitrydikun** [comment]
It is bad and important because I have a useless button in my UI that I cannot hide, and this button is always visible even though I will never use it.

**Comment by PF4Public** [comment]
This might be (again) fixed in https://github.com/ungoogled-software/ungoogled-chromium/pull/3143. Please give it a try.
