### ISSUE TITLE
Xbox Cloud broken

### ISSUE THREAD

**Issue by BananaAcid** [ungoogled-software/ungoogled-chromium#2770]
### OS/Platform

Arch Linux

### Installed

Flatpak

### Version

122.0.6261.128

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Xbox Cloud Games do not start, after the rocket loading screen

### How to Reproduce?

1. go to Xbox cloud: https://www.xbox.com/en-us/play
2. login
3. Start any game
4. Wait until the loading/connection animation is done (rockt screen)
5. crash back to dashboard
6. JS error: „Error: WebRtcStream: Connect. GameStreamError:Failed to connect to game stream.“

### Actual behaviour

The game stream does not connect. WebRTC API seems to have a problem.

### Expected behaviour

It should connect to the game stream and let me play the game, as in chromium/chrome. 

DevTools show a JS error: „Error: WebRtcStream: Connect. GameStreamError:Failed to connect to game stream.“

**Comment by PF4Public** [comment]
Have you attempted fixing it [as suggested in FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-fix-webrtc)?

**Comment by BananaAcid** [comment]
@PF4Public  After trying reading „How do I fix WebRTC?“ and setting it to default, it started working again. It was quite a surprise it would not work after updating uc. I talked to others, and we we were convinced, webrtc got broken in this build.

I understand it is not a bug, but rather has become a hidden feature to be able to stream game services.

So really thanks for the info. 

Maybe put the info more prominent for us SteamDeck and XBOX Cloud users to find? Or an information popup in the browser on using webrtc?

**Comment by PF4Public** [comment]
> webrtc got broken in this build

Some [may say that it got _fixed_](https://github.com/ungoogled-software/ungoogled-chromium/pull/2359#:~:text=to%20disable%20non%2Dproxied%20UDP%20by%20default) instead :)

>Maybe put the info more prominent for us SteamDeck and XBOX Cloud users to find? Or an information popup in the browser on using webrtc?

`chrome://ungoogled-first-run/` already has a link to FAQ. Adding anything extra to it might make it less readable. More so if one needs to explain the connection between streaming games and webrtc.

**Comment by BananaAcid** [comment]
@PF4Public another note, the `chrome://ungoogled-first-run/` did not reappear on update for me. I might ahve seen this 2 years ago, but since it all worked back then, I propably totally forgot about it. This should probably open up on updates as well.

**Comment by tomasz1986** [comment]
> This should probably open up on updates as well.

That would be extremely annoying though.

**Comment by PF4Public** [comment]
> > This should probably open up on updates as well.
> 
> That would be extremely annoying though.

Absolutely! I advocated against that.

>might ahve seen this 2 years ago

We have it [slightly less than a year](https://github.com/ungoogled-software/ungoogled-chromium/pull/2314) by now. And indeed it might've never appeared on your system if you kept your profile for that long, sorry.
