### ISSUE TITLE
protable userdata broken since ver 122, some website can't stay logged in across browser restart with (disable-encryption) (disable-machine-id) flags

### ISSUE THREAD

**Issue by Brbrbr1995** [ungoogled-software/ungoogled-chromium#2773]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

122 and 123

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

protable userdata broken since ver 122

### How to Reproduce?

1  clean install 122 or 123
2  start exe with --disable-encryption --disable-machine-id
3  goto flag and enable  --disable-encryption --disable-machine-id flags
4  restart browser and login to some website, for example reddit twitter youtube 9gag 
5  restart browser ,reopen websites, 9gag is still logged in, while the other 3 are logged out

### Actual behaviour

5  restart browser ,reopen websites, 9gag is still logged in, while the other 3 are logged out

### Expected behaviour

all websites should stay logged in like before version122

**Comment by Nifury** [comment]
Odd. There was a PR in the Windows repo that fixed this problem, but it was somehow deleted.

**Comment by Brbrbr1995** [comment]
😕
