### ISSUE TITLE
Blank/White Screen for browsing and all settings menus [Flatpak]

### ISSUE THREAD

**Issue by pflanzenandi** [ungoogled-software/ungoogled-chromium#2775]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

123.0.6312.58

Unable to use this Browser any more. Is this bug known already?
Tried un- and reinstalling. Tried changing to light mode system wide.

**Comment by kjyv** [comment]
Why was this closed? I have the same issue when installing with homebrew on macOS

**Comment by pflanzenandi** [comment]
Uninstall
Delete following folder: /home/var/com.github.Eloston.UngoogledChromium
Reinstall

**Comment by kjyv** [comment]
Well ok, deleting the complete config works but that also deletes all config and open tabs. But just deleting some caches and the LocalState file also worked.
