### ISSUE TITLE
error code sigsegv

### ISSUE THREAD

**Issue by Devious3901** [ungoogled-software/ungoogled-chromium#2784]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

Version 123.0.6312.86 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

error code sigsegv after flatpak update

### How to Reproduce?

This happened after the flatpak update

### Actual behaviour

Check screenshot https://imgur.com/a/JmFnKYa

### Expected behaviour

Hi, two days ago I updated all the apps to flashpak, and I got this problem that pops up in ungoogled chrome, how to fix it, before that it was not there, that is, before the update of the flashpak version.

**Comment by PF4Public** [comment]
@rany2 Have you encountered such issue?

**Comment by rany2** [comment]
Nope, I don't have a clue about this. Sorry

**Comment by rany2** [comment]
@PF4Public The only thing I could think of is that the flatpak was updated and he didn't exit UGC and relaunch.
