### ISSUE TITLE
Direct-write from Advanced Chrome (browser.taokaizen.com)

### ISSUE THREAD

**Issue by wallofbytes** [ungoogled-software/ungoogled-chromium#279]
Is it possible to add removed in original chromium [option](http://browser.taokaizen.com/chrome-directwrite/) to enable/disable direct-write and/or [apply font patch](http://browser.taokaizen.com/download/patch.txt) from Advanced Chromium?

**Comment by Eloston** [comment]
Although it would be nice to include the entire patch, it seems to touch a lot of code that could break between version updates. I don't want to spend that much time updating features that aren't the main focus of ungoogled-chromium.

Is there a separate font patch? I can only see one patch that includes everything.

**Comment by wallofbytes** [comment]
It would be great! I don't know about separate patches, sorry, I am not a programmer, but I think, it's possible to extract font fixing functionality from this patch. I am wrong? In this case you can contact to the creator of this patch to ask a patch that specifically adds font-fixing functionality.

**Comment by Eloston** [comment]
I don't want to sift through all of the changes to extract out the font changes since it's a really large patch. The developer should probably be contacted after Windows support is added back into ungoogled-chromium, though.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
