### ISSUE TITLE
Workaround/fix for Chromium issue #41007340

### ISSUE THREAD

**Issue by AgentSmith0** [ungoogled-software/ungoogled-chromium#2791]
### OS/Platform

Arch Linux

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

123.0.6312.105

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

navigator.onLine returns true when VMware network adapters exist

### How to Reproduce?

1. Launch some VM software (e.g. Oracle VM, waydroid, anbox, etc.)
2. Read navigator.onLine in console
3. See navigator.onLine gives false positives

### Actual behaviour

navigator.onLine returns false positives

### Expected behaviour

navigator.onLine returns the correct online status of the system, even when VM software is running.

Since there is no work going on in the Chromium repository to fix this issue (https://issues.chromium.org/issues/41007340), is it possible to implement some workaround or fix inside ungoogled-chromium?

### Additional context

Chromium issue: https://issues.chromium.org/issues/41007340

**Comment by PF4Public** [comment]
I doubt we could and should fix this particular issue if Chromium developers are not very eager in fixing it.

I'll leave it open for some time just to gather more opinions.
