### ISSUE TITLE
UG command name

### ISSUE THREAD

**Issue by DutchPete** [ungoogled-software/ungoogled-chromium#2792]
I have installed Ungoogled Chromium flatpak in Ubuntu, and I want to set up a customized keyboard shortcut to open a specific webpage.

I need the command name, and there is this folder: `.var/app/com.github.Eloston.UngoogledChromium` but that is not the command nae, in any case it does not work.

I have scoured the internet but not been able to find it.
Please advise.

**Comment by rany2** [comment]
Command should be `flatpak run com.github.Eloston.UngoogledChromium <url here>` but it will change in a bit to a new app ID.

**Comment by DutchPete** [comment]
@rany2 Many thanks for your help, that works fine 👍

How can I keep informed as to the new ID?

**Comment by DutchPete** [comment]
@rany2 OK, that's great and the new ID is already known.
Thanks for keeping the app going after the original dev pulled out, without any notification it seems.

**Comment by rany2** [comment]
@DutchPete I'm not sure what you mean, I've maintained the Flatpak from the start.

**Comment by DutchPete** [comment]
@rany2 I was referring to this comment on [this page](https://github.com/flathub/flathub/pull/5098:)

> The original developer is no longer actively online and is unlikely to respond

So, it seems I misunderstood, for which I apologize, and certainly did not mean to offend you if I did.
Yes, this issue can be closed now.
