### ISSUE TITLE
Cant add a new search engine, nor modify default search engines

### ISSUE THREAD

**Issue by jvne2134** [ungoogled-software/ungoogled-chromium#2793]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

123.0.6312.105 (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Fresh UC install, no extensions, i cant add a new search engine, nor can i click on the "make default" button 

### How to Reproduce?

1. Go settings
2. go to search engine
3. click on add
4. fill details (Name: Google, Shortcut: google, URL: google.com, suggestions: google.com)
5. click add
6. click 3 dots on newly created entry
7. make default option is greyed out
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/97559343/1e7537fd-e2c7-4c82-9c9a-36a13a480a57)

optional
1. Edit one of the default search engines
2. Relevant options are greyed out
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/97559343/1ceaed5f-6cfa-42c6-8931-2b0e87ab1e41)

### Actual behaviour

I can't add a custom search engine

### Expected behaviour

I should be able to at least click on the button "make default" to make this search engine default

**Comment by tomasz1986** [comment]
Can you share a screenshot of what this part looks for you?

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/5626656/b8b57f69-37f7-4956-94aa-f844fdbdc994)

Judging from what you wrote above, it seems that your URL is wrong (incomplete).

**Comment by jvne2134** [comment]
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/97559343/9eb8913c-91c4-4b3a-a21c-6a4669deb752)

im gonna try copy your settings, thank you :3

**Comment by PF4Public** [comment]
So, did it work in the end?

**Comment by jvne2134** [comment]
it worked, thank you :hug:

**Comment by PF4Public** [comment]
@jvne2134 I'd like to note that you shouldn't be using `http`, use `https` instead.
