### ISSUE TITLE
Ungoogled Arc Browser

### ISSUE THREAD

**Issue by drkhero** [ungoogled-software/ungoogled-chromium#2794]
### Description

Arc browser but without the spyware.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Would you guys ever consider making an "Ungoogled Arc Browser" ?

Basically, Arc Browser, but with all the spyware features removed just like for Ungoogled Chromium.

### Possible solutions

Remove all spyware features from Arc Browser, and all telemetry.

**Comment by networkException** [comment]
How would anyone do that, the source code is not available, is it?

Anyone is free to start a project removing all the spyware from some spyware (thats my opinion of any proprietary browser) but I don't many (if any) people who work on ungoogled-chromium currently would be interested

**Comment by drkhero** [comment]
> How would anyone do that, the source code is not available, is it?
> 
> Anyone is free to start a project removing all the spyware from some spyware (thats my opinion of any proprietary browser) but I don't many (if any) people who work on ungoogled-chromium currently would be interested

I understand the source code is not available but guys could decompile it ?

**Comment by jstkdng** [comment]
just block all the domains bro
