### ISSUE TITLE
Restore Debian repo for installing from apt

### ISSUE THREAD

**Issue by hankster112** [ungoogled-software/ungoogled-chromium#2812]
### Description

Add a repo for installing UG from a repository with apt

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Until version 100 there was a repo that provided builds which could be easily updated with my other Debian packages when running apt. Around that time the PGP key expired and was never renewed, so it's been stuck on v100 ever since (which has a known security vulnerability and was quickly updated to 101 for other platforms). 

### Possible solutions

Publish builds that can be installed from an apt repo, or update the key from the previous one if it still exists.

### Alternatives

Right now using AppImages works OK, but it's very tedious to check the site for a new update, then to download it, remove the old AppImage, install the new AppImage, then set the default browser to the new AppImage.

### Additional context

Is there a specific reason why .deb builds stopped being published? Or did the repo maintainer just leave and nobody ever setup a new one?

**Comment by PF4Public** [comment]
> Is there a specific reason why .deb builds stopped being published? Or did the repo maintainer just leave and nobody ever setup a new one?

https://github.com/ungoogled-software/ungoogled-chromium-debian is not very active at the moment. You may find this PR of interest: https://github.com/ungoogled-software/ungoogled-chromium-debian/pull/328

I'll close this issue as a repository being unmaintained is not an "issue" we can readily address.
