### ISSUE TITLE
Missing important option in settings that used to exist in earlier versions

### ISSUE THREAD

**Issue by milanvidakovic** [ungoogled-software/ungoogled-chromium#2825]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

124.0.6367.60-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Missing "Clear cookies and site data when you close all windows When on, you'll also be signed out of Chromium"

### How to Reproduce?

1. Go to Settings, Privacy and Security, Third Party Cookies
2. There is no option "Clear cookies and site data when you close all windows
When on, you'll also be signed out of Chromium" that used to be.

This option is missing from 120.x.x.x versions.

### Actual behaviour

The missing option is quite important, since it clears all the cookies we don't want to have.

### Expected behaviour

The "Clear cookies and site data when you close all windows When on, you'll also be signed out of Chromium" option should be included again.

**Comment by eduardoeae** [comment]
You can access it [here](chrome://settings/content/siteData)
AFAIK there is no way to access this from the menus.

**Comment by Nifury** [comment]
Interesting, I didn't notice that. 
You need to expand the menu to find site data. 
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/7867461/bada876c-5adb-4424-abf6-05b63aa218ed)

**Comment by milanvidakovic** [comment]
Thanks to all, closing the issue.
