### ISSUE TITLE
New updated patch of Cromite browser Add new patch of Cromite browser to make possible to enable energy battery saver feature even when plugged in

### ISSUE THREAD

**Issue by trimechee** [ungoogled-software/ungoogled-chromium#2839]
### OS/Platform

Windows

### Installed

Compiled from source

### Version

124.0.6367.91-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Hello, It seems that Cromite Browser in the last update has achieved the sensational extraordinary great feat of making the "energy battery saver" option active by default even when plugged in even without battery on a desktop computer in order to preserve our battery and energy and the ecology and avoid fan noisy and expensive electricity bill.... 
 We hope our beloved Ungoogled-Chromium browser will be able to implement this option even when plugged in because this battery saver option is disabled when plugged in Ungoogled- Chromium browser, thank you so much :)  build/patches/WIN-enable-HighEfficiencyMode-by-default.patch  uazo/cromite@0dc5d37  https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/performance_manager/user_tuning/battery_saver_mode_manager.cc  https://chromium-review.googlesource.com/c/chromium/src/+/5046375  https://issues.chromium.org/issues/40158973  https://bugs.chromium.org/p/chromium/issues/detail?id=1153154&no_tracker_redirect=1

### How to Reproduce?

Go to chrome://settings/performance

### Actual behaviour

Battery saver is disbaled when plugged in and impossible to enable it 

### Expected behaviour

Enabled battery saver when plugged in

**Comment by PF4Public** [comment]
I'm afraid we cannot use Cromite patches just yet.

**Comment by PF4Public** [comment]
> copyright

Yes, we haven't worked out those kind of things.

**Comment by PF4Public** [comment]
> Cromite will allow other developers using his code

It is not the issue I was mentioning. We haven't worked out the best way for including other code with different license into ungoogled-chromium. Until that no code borrowing, sorry.
