### ISSUE TITLE
ungoogled-chromium removed from latest Tumbleweed snapshots

### ISSUE THREAD

**Issue by ChrTall** [ungoogled-software/ungoogled-chromium#2840]
### OS/Platform

Portable Linux

### Installed

OS/Platform's package manager

### Version

latest

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

The packages was removed from the latest snapshot releases in Tumbleweed

### How to Reproduce?

sudo zypper se "ungoogled-chromium"

### Actual behaviour

Is not in the repository anymore and was replaced with the default chromium during an update.

### Expected behaviour

Was always in the the standard factory repository of openSuse Tumbleweed.

**Comment by PF4Public** [comment]
Please see https://github.com/ungoogled-software/ungoogled-chromium/pull/2819
