### ISSUE TITLE
is it acceptable to add windows specific patch to ungoogled chromium ?

### ISSUE THREAD

**Issue by cpuuntery** [ungoogled-software/ungoogled-chromium#2848]
### Description

disable emoji from chrome context menu

### The problem

emoji option in context menu is annoying 

### Possible solutions

The code responsible for emoji option in context menu is in this link

https://source.chromium.org/chromium/chromium/src/+/main:ui/base/emoji/emoji_panel_helper_win.cc

**Comment by PF4Public** [comment]
It is not very clear what you propose, please add more details.

**Comment by networkException** [comment]
> emoji option in context menu is annoying

Thats not an argument that would qualify for adding a removal patch. Not here (please take a look at the project goals) and not in the Windows platform repository.

**Comment by cpuuntery** [comment]
@networkException 
@PF4Public 

To me, the patch that I am requesting is no different from these two patches 

https://github.com/ungoogled-software/ungoogled-chromium/pull/1978

https://github.com/ungoogled-software/ungoogled-chromium/pull/1591

but i guess from your response, Linux take priority over windows when it comes to patching the source code

i know one or two things about c++ and I would more when happy to submit a pull request. 

But compiling chromium on i any platform is HELL. 
Last I heard, the source code is over 100GB, and you need Threadripper to compile the code under 3 hours

If you still do not agree with me, **feel free to close this issue because I don't care any more**

Best regards
