### ISSUE TITLE
New tab does not open next to current

### ISSUE THREAD

**Issue by worldor** [ungoogled-software/ungoogled-chromium#2853]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 120.0.6099.180

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

New tab does not open next to current

### How to Reproduce?

Clicking CTRL+T or the + button at the right of the tab bar

### Actual behaviour

New tab does not open next to current

### Expected behaviour

New tab opens next to current

**Comment by PF4Public** [comment]
Why would you expect new tab to open next to the current one? Does Chrome/Chromium do this?
