### ISSUE TITLE
Locking thread so fast is a bug ;-)

### ISSUE THREAD

**Issue by top-master** [ungoogled-software/ungoogled-chromium#2854]
Afraid of me answering, they instantly locked the thread, well, here is what you was afraid of:

I got a response at https://github.com/ungoogled-software/ungoogled-chromium/issues/2845#issuecomment-2106381505

Which was:
>"Support is not happening, making this a discussion has no value."

Interesting, just that I already siad something like "Support is not happening" before you, and even suggested an alternative, **but** then (s)he tried to make this a discussion about  "highly vulnerable software", without knowing that Windows never will be safe from goverment's eyes.

**Edit:** above makes only sense if you read previous thread.

**Comment by networkException** [comment]
I'm not interested in getting my time wasted by you.
