### ISSUE TITLE
Firebase Messaging does not works on Ungoogled Chromium

### ISSUE THREAD

**Issue by CypherPotato** [ungoogled-software/ungoogled-chromium#2867]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

122.0.6261.94

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Firebase Messaging does not works on Ungoogled Chromium

### How to Reproduce?

Details on tracking issue on Firebase repo: https://github.com/firebase/firebase-js-sdk/issues/8252

### Actual behaviour

The `getToken` method of the Firebase Messaging SDK does not works on Ungoogled Chromium but does works in other browsers.

### Expected behaviour

It should return an messaging token.

No additional extensions were enabled on this context.

**Comment by PF4Public** [comment]
Does it work in vanilla Chromium?

**Comment by CypherPotato** [comment]
@PF4Public not reproducible on vanilla chromium v127. 

I'm thinking that the bug happens because in ungoogled chromium, all texts that contain "google" are removed from the build binary, which means that the browser can't listen to the google push service.

**Comment by PF4Public** [comment]
Well, then it is a feature not a bug :)

I'll keep it open for some time to gather more opinions, but I doubt that fixing it aligns well the project goals.

**Comment by CypherPotato** [comment]
It's not a browser problem, but I've spent a few hours debugging the problem until I realized that the Unchromium Push Service address "didn't exist" :)

The opinion I can point to is not allowing sites to try to register service workers that listen for background notifications, or making it more explicit that "push messaging doesn't work in this browser. don't even try to integrate."

**Comment by networkException** [comment]
hm, thats probably not straight forward to implement.

I'd assume people would interpret "Removes all remaining background requests to any web services while building and running the browser" as also not having support for push, as that requires a connection thats kept alive in the background
