### ISSUE TITLE
Fingerpriting cpu cores and memory like popular Dolphin-Anty an anti detect browser does?

### ISSUE THREAD

**Issue by Jazzykhan** [ungoogled-software/ungoogled-chromium#2868]
### Description

Allow a method in flags to spoof memory and/or cpu for fingerprint spoofing

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

It only has canvas fingerprinting right now but still cpu cores and memory is real as per my computer.

### Possible solutions

Command line flags to spoof cpu and/or flags or any help how to do it?

**Comment by Arthur-Senior** [comment]
I have done already some Moks on Browser, I can upload my work. I am mocking everything from memory till GL-Fingerprint

**Comment by PF4Public** [comment]
> I have done already some Moks on Browser, I can upload my work. I am mocking everything from memory till GL-Fingerprint

May I inquire how do you achieve that?

**Comment by Arthur-Senior** [comment]
I took all the data to a config file and exchange parameters in the
functions inside. The V8 mechanism is taking parameters from classes I n
tbe middle, the work of the app is not disturbed, because it's not on
working level.

пт, 7 июн. 2024 г., 19:56 PF4Public ***@***.***>:

**Comment by PF4Public** [comment]
> I took all the data to a config file and exchange parameters in the functions inside. The V8 mechanism is taking parameters from classes I n tbe middle, the work of the app is not disturbed, because it's not on working level.

So you changed those parameters in a profile config file? Are those parameters not recalculated every time in runtime?

**Comment by Arthur-Senior** [comment]
I changed it in runtime, it is read once on load and given to a singleton
structure inside the chrome.dll. so, you can have n*instance with different
settings and it can moc even the system and browser type

пт, 7 июн. 2024 г., 20:33 PF4Public ***@***.***>:

**Comment by Arthur-Senior** [comment]
I can send you some screens, how it is doing with original system and my
system.


пт, 7 июн. 2024 г., 20:33 PF4Public ***@***.***>:

**Comment by Arthur-Senior** [comment]
I want to switch my system from Google chromium original to ungoogled
chrome. I build it on windows server, wishbof customer, but anyway. May be
you can help me. I cline the source and build it original with python
build.py, but if I try to rebuild the modified code, or just start ninja -C
....
It stacked on chrome-allowlist.txt
Can you tell me why I can't rebuild?

пт, 7 июн. 2024 г., 19:56 PF4Public ***@***.***>:

**Comment by PF4Public** [comment]
> I changed it in runtime, it is read once on load and given to a singleton
structure inside the chrome.dll. so, you can have n*instance with different
settings and it can moc even the system and browser type

I still don't get it how you do it. Could you explain it in more details?

PS: I've hidden your last message as it is unrelated here.

**Comment by Arthur-Senior** [comment]
I changed on example font_cache.cc and font_list_impl.cc to implement fonts
from my config file. When a function in V8 system checked if font is
present, it looks up in my list and say yes or not. the hole system, can
use all the fonts on system, in registry and wherever.


Can you please send me the utility missing for my problem please?

**Comment by Arthur-Senior** [comment]
I would like to join the project and make the mocking options for it, if
you like.

пт, 7 июн. 2024 г., 19:56 PF4Public ***@***.***>:

**Comment by PF4Public** [comment]
>I changed on example font_cache.cc and font_list_impl.cc to implement fonts
from my config file.

Do you have a repository with your changes anywhere?

**Comment by Arthur-Senior** [comment]
No, all offline. I can give some changes in files or single functions

сб, 8 июн. 2024 г., 13:59 PF4Public ***@***.***>:

**Comment by PF4Public** [comment]
It could be of interest if it was written solely by you (not copied from somewhere) and could be integrated seamlessly into ungoogled-chromium. For the latter it should ideally be exposing a flag for user-configuration.

**Comment by Arthur-Senior** [comment]
This can be done. It is to100% my own work and code. And yes, it can be
used with a user configuration. Currently. I am planning to rebuild it to
json from config file.

сб, 8 июн. 2024 г., 15:04 PF4Public ***@***.***>:

**Comment by Arthur-Senior** [comment]
Can you tell me, if I have an older officially googled chromium version
from original git. Already full patched with my mom's. Can I convert it to
ungoogled? Because the chromium original, even untouched is very slow.

сб, 8 июн. 2024 г., 15:07 Wjatscheslaw S. ***@***.***>:

**Comment by PF4Public** [comment]
> Can I convert it to ungoogled?

Probably yes, but you may run into patch-conflicts which you'll have to solve manually.

**Comment by Arthur-Senior** [comment]
Here 2 pics. one with files, which where patched for mocks. and another with example of patch.
![20240608_130113](https://github.com/ungoogled-software/ungoogled-chromium/assets/126072832/31c771ed-d3b0-4b6e-9d8e-d3d41b122606)
![20240608_130154](https://github.com/ungoogled-software/ungoogled-chromium/assets/126072832/8e482c53-1076-4df8-8c7e-059a027b708d)

**Comment by PF4Public** [comment]
@Arthur-Senior If you're willing to contribute new features to ungoogled-chromium you are always free to submit PR with your code. I would however advise you to open a separate issue to discuss the changes you're proposing. Providing the actual code/patches instead of screenshots would also help the discussion.

**Comment by Arthur-Senior** [comment]
I would like to help developing ungoogled-Browser, and mocking features i worked the complete last year on. With my knowladge what is to be done and your little help on things where i am stacked, Could be a good thing.

**Comment by Jazzykhan** [comment]
@Arthur-Senior  were you able to mock cpu cores and memory?
Thanks

**Comment by Arthur-Senior** [comment]
Yes it is possible.

пн, 10 июн. 2024 г., 23:47 Jahanzaib Khan ***@***.***>:

**Comment by Jazzykhan** [comment]
@networkException  so can we change cores now?

**Comment by Arthur-Senior** [comment]
What exactly do you want to do?

сб, 15 июн. 2024 г., 01:05 Jahanzaib Khan ***@***.***>:

**Comment by networkException** [comment]
no we match the behavior of firefox and always say there are two cores

**Comment by Arthur-Senior** [comment]
yes, i think it is possible. you can see what it is doing and collecting. find file fingerprint.cc in this file you can see what information it is collecting. but you have to patch far more than only this file

**Comment by Jazzykhan** [comment]
@networkException Sir, i think there should be a way to increase or decrease cpu cores with opening flags or somehting else.

**Comment by Arthur-Senior** [comment]
Surely there is a possibility.  I need to rewrite currently a function to
upgrade to newest File System API. Then I can handle your CPU problem.

вт, 18 июн. 2024 г., 00:13 Jahanzaib Khan ***@***.***>:
