### ISSUE TITLE
Google sign-in prompt shows up on some websites

### ISSUE THREAD

**Issue by Swarkin** [ungoogled-software/ungoogled-chromium#2869]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 122.0.6261.94 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Google sign-in prompt shows up on some websites.

### How to Reproduce?

Go to medium.com
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/102416174/8226c7b7-2b16-423a-8299-8a0d9fbda604)

### Actual behaviour

Google sign-in prompt shows up on some websites.

### Expected behaviour

I expected ungoogled-chromium to be ungoogled

### Additional context

Is this left in for a reason? The browser managed to extract my account info from presumably YouTube and now shows it in a small popup when websites support Google sign-in.

**Comment by Swarkin** [comment]
It is part of the interface, it sometimes even spawns outside of the browser's window area because of some incorrect position calculation and hovers above the browser contents itself

**Comment by Swarkin** [comment]
It even shows up when I delete the entire html document:
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/102416174/43c18ac8-d399-40d7-bcb1-0976c63d0447)
It is a native browser popup

**Comment by Swarkin** [comment]
Found the culprit and honestly surprised this isnt off by default or even removed entirely.
![WMLSszAkgS](https://github.com/ungoogled-software/ungoogled-chromium/assets/102416174/8feaa70d-1d32-49d8-bd41-2e019a60d649)

**Comment by PF4Public** [comment]
@networkException @Ahrotahn Is it worth flipping this setting by default?

**Comment by Ahrotahn** [comment]
With our changes the identity provider should return that the profile is not signed in.  Granted, we should probably add that section to the UI removal patch since it doesn't, or at least *shouldn't*, do anything.  

I tested with my local linux build as well as the windows builds for 122.0.6261.94-1 and 124.0.6367.207-1 from our binaries page and I'm not able to reproduce this.  

Are you using a third-party build?  Maybe they are not building with our sign-in changes.  
Are you using a profile that was used with another browser?  Maybe there is a variable that got set in the profile that we didn't expect to be changed.

**Comment by Ahrotahn** [comment]
@Rusenche The interface option for the setting existing wasn't in question.  Can you reproduce the Google sign-in dialog this issue is about?

**Comment by Swarkin** [comment]
@Ahrotahn 

> Are you using a third-party build?  Maybe they are not building with our sign-in changes.  

I am using the windows build from the builds website linked in the readme on version 122 as that is the last version without the UI refresh.

> Are you using a profile that was used with another browser? 

I only imported a bookmark html file and the browser was one of the first things I installed on a fresh windows ltsc install, so no other browsers were present.

**Comment by Ahrotahn** [comment]
I'll see what I can figure out.  It might be better to remove fedcm functionality alltogether.

**Comment by someplaceguy** [comment]
I'm still seeing running into this issue, see the screenshot below:

<img width="1728" height="392" alt="Image" src="https://github.com/user-attachments/assets/da234d08-75a3-46f6-872a-911a4ef340d8" />

**Comment by someplaceguy** [comment]
Starting ungoogled-chromium with `--disable-features=FedCm` seems to be a workaround for this issue.

**Comment by PF4Public** [comment]
@someplaceguy Which version are you using?

**Comment by someplaceguy** [comment]
@PF4Public When I posted that comment I was using version 143.0.7499.169-1, which was released on December 19th.

**Comment by sqikerz** [comment]
Seems like the issue still exists, this should be reopened.

**Comment by derpyjoystick** [comment]
> Seems like the issue still exists, this should be reopened.

Problem still persists as of 144.0.7559.96 (on macOS). Worse yet, it appears this PR removed the UI option in settings, so right now (at least in macOS), there is no option to enable or disable third party sign-ins: 

https://github.com/ungoogled-software/ungoogled-chromium/pull/2872

>There's also a change to remove the interface option in the UI removal patch. 

<img width="433" height="105" alt="Image" src="https://github.com/user-attachments/assets/4f63ec09-0022-4853-bc90-25dd8429d76b" />

**Comment by Swarkin** [comment]
Can confirm on 144.0.7559.109

<img width="428" height="277" alt="Image" src="https://github.com/user-attachments/assets/d4879ed3-ef54-453d-a9e8-642ee84ecc95" />

**Comment by sqikerz** [comment]
There was a fix published (available on 144.0.7559.132 and later), you'll just have to update your installation.
