### ISSUE TITLE
Running python3 build.py gives an error at the very end a file license.py is missing

### ISSUE THREAD

**Issue by Jazzykhan** [ungoogled-software/ungoogled-chromium#2871]
### OS/Platform

Windows

### Installed

Compiled from source

### Version

125.0

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Giving error on the end

### How to Reproduce?

Follow all steps and then run python3 build.py and wait for many many hours lol just to know there is an error 

![0deed6e8-008c-4a38-90e6-071649629df7](https://github.com/ungoogled-software/ungoogled-chromium/assets/31903098/14e885de-18f9-4332-b130-00e5b6f1b8d3)

### Actual behaviour

Error at the end

### Expected behaviour

No error

**Comment by Nifury** [comment]
These are more like warnings and don't affect your compilation. 

It's likely an upstream issue: https://issues.chromium.org/issues/333628466

**Comment by Jazzykhan** [comment]
But if i run package.py it gives error no mini installer found am i missing something?

![Uploading 6badce0b-a3d5-472f-b7ed-a84683854dd8.jpeg…]()

**Comment by Nifury** [comment]
You might have either run package.py twice (package.py deletes mini_installer.exe), or you compiled with the --ci flag which automatically runs package.py.

**Comment by Jazzykhan** [comment]
So now if i edit code and run build.py again it should not make all 61k files again right? But it is doing it again :(

**Comment by Nifury** [comment]
Well it depends on how you edit the code. The easiest way is to run `python3 build.py --ci`, and only the installer will be built.

**Comment by Jazzykhan** [comment]
and if want to build a portable version like files only how to build that and where it will be built ?

**Comment by Nifury** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-windows?tab=readme-ov-file#building-1

> A zip archive and an installer will be created under build.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
