### ISSUE TITLE
Enabled cookies, but won't stay signed into sites like YouTube

### ISSUE THREAD

**Issue by ZsoltHevesi** [ungoogled-software/ungoogled-chromium#2873]
I even added exceptions for google.com and youtube.com (I know, not the point of Ungoogled Chrome)
Older issues like this showed options in the settings which clearly stated keeping/deleting data like sign-ins, but those options don't exist for newer versions.
I assume cookies are the same as the way they're described in the settings, but enabling them still means I don't stay signed in?
What can I do?

To clarify I am using the Windows 10, 64-bit version

**Comment by touba-denrael** [comment]
under debian bookworm:

`chrome://flags/#clear-data-on-exit` should be on the default or disabled setting

`chrome://settings/clearBrowserData` basic tab: `cookies and other site data` should be unclicked, empty

`chrome://settings/clearBrowserData` advanced tab: `cookies and other site data` should be unclicked, empty

`chrome://settings/clearBrowserData` advanced tab: `site settings` should be unclicked, empty

these settings are working for me.

**Comment by ZsoltHevesi** [comment]
That seems to have done the trick for me.
The flags thing for clearing data was probably the main culprit but it seemed so hidden to me, thanks.
