### ISSUE TITLE
website shortcuts broken in Gnome on Fedora

### ISSUE THREAD

**Issue by smidm** [ungoogled-software/ungoogled-chromium#2883]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

Version 125.0.6422.112 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

website shortcuts don't appear in gnome applications

### How to Reproduce?

1. visit a website
2. menu - Save and share - Create shortcut
3. save shortcut
4. open Gnome overview
5. type shortcut name

### Actual behaviour

shortcut not present in the menu

### Expected behaviour

shortcut gets created

### Relevant log output

```sh
LaunchProcess: failed to execvp:
update-desktop-database

(the same log output is present with a fresh user profile that is not affected by the issue)
```

### Additional context

1. I can't reproduce the problem with a fresh profile.
2. All the shortcuts disappeared during flatpak update approximately month ago.
3. tested on Fedora 39 and 40

**Comment by networkException** [comment]
Something with the sandbox maybe? CC: @rany2

**Comment by rany2** [comment]
Maybe you need to manually edit the desktop files to point to the new app ID?

**Comment by rany2** [comment]
> Something with the sandbox maybe? CC: @rany2

It works fine in the a fresh profile, so I think that it might be migration related.
