### ISSUE TITLE
You can’t open the application “Chromium” because this application is not supported on this Mac.

### ISSUE THREAD

**Issue by Butterscotch96** [ungoogled-software/ungoogled-chromium#2898]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

125.0.6422.141

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I install from homebrew 

### How to Reproduce?

1. Install as instructed
2. Open the app

### Actual behaviour

The app doesn't open
<img width="270" alt="image" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/134971065/c86227c6-489c-4f31-a781-06fbfaea477b">

### Expected behaviour

The app opens

### Relevant log output

```sh
There is no log
```

### Additional context

![Screenshot 2024-06-02 at 8 44 33 PM](https://github.com/ungoogled-software/ungoogled-chromium/assets/134971065/f7370a6c-cdea-4a08-b0e6-7aabe70b914f)

**Comment by networkException** [comment]
Do you have a Mac with Apple Silicon (M1 - M3 chips currently), perhaps? In that case you need the arm64 and not the x86-64 version of the release you want to install

**Comment by Butterscotch96** [comment]
> Do you have a Mac with Apple Silicon (M1 - M3 chips currently), perhaps? In that case you need the arm64 and not the x86-64 version of the release you want to install

Yeah I'm on M1 but wouldn't it still run with Rosetta?

**Comment by Cubik65536** [comment]
> > Do you have a Mac with Apple Silicon (M1 - M3 chips currently), perhaps? In that case you need the arm64 and not the x86-64 version of the release you want to install
> 
> Yeah I'm on M1 but wouldn't it still run with Rosetta?

No, you should get the arm64 version of Ungoogled-Chromium.
