### ISSUE TITLE
Print.. is not working anymore

### ISSUE THREAD

**Issue by stepger** [ungoogled-software/ungoogled-chromium#2905]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

125.0.6422.141

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Print.. ( Ctrl + P ) "Print preview failed"

### How to Reproduce?

1. Ctrl + P
2. "Print preview failed"
Note: works on older/previous version

### Actual behaviour

"Print preview failed"

### Expected behaviour

Have a preview then print/save to .pdf

### Additional context

thanks

**Comment by Nifury** [comment]
Duplicates https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/353
