### ISSUE TITLE
How to build this for Apple Silicon?

### ISSUE THREAD

**Issue by MarcTremblay1981** [ungoogled-software/ungoogled-chromium#2907]
### OS/Platform

macOS

### Installed

Compiled from source

### Version

125.0

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Trying to build this for AARM from the instructions

### How to Reproduce?

I would like to try this browser, but the `brew install --cask eloston-chromium` command from the read me page resulted in an Intel binary instead of an AARM one.  Is there any way to build this for Apple Silicon? It's not 2020 anymore.

### Actual behaviour

It made an Intel binary which is incompatible with my Mac.

### Expected behaviour

I would have expected it to make an AARM binary which would be compatible with my Mac.

**Comment by smol-loli** [comment]
For MacOS builds see [this repo](https://github.com/ungoogled-software/ungoogled-chromium-macos). Also, there are pre-build MacOS binaries for both Intel and ARM available [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). Hope this helps

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by MarcTremblay1981** [comment]
Yes, thanks!
