### ISSUE TITLE
how do i update my chromium? first time using this browser sorry if this is a dumb question

### ISSUE THREAD

**Issue by ComfortableMilk4454** [ungoogled-software/ungoogled-chromium#2916]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

An error occurred. (Error code: 9) (Extra code: 0) Learn more Version 125.0.6422.141 (Official Build, ungoogled-chromium) (arm64)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

how do i update my chromium? first time using this browser sorry if this is a dumb question

### How to Reproduce?

go to chrome://settings/help & see that chromium is out to date

### Actual behaviour

error code 9

### Expected behaviour

some update button of some sort

**Comment by networkException** [comment]
There is no update button, you have to either manually download new releases or have homebrew manage the updates for you

**Comment by ComfortableMilk4454** [comment]
Oh I see, how do I have homebrew do it? Thanks for the response btw :)

**Comment by ComfortableMilk4454** [comment]
Also do you happen to know what error code 9 means?

**Comment by ComfortableMilk4454** [comment]
> Oh I see, how do I have homebrew do it? Thanks for the response btw :)

is the chromium 126 not for macos atm? looking at the repository the latest is 125. that would explain why homebrew installed 125 https://github.com/ungoogled-software/ungoogled-chromium-macos

**Comment by networkException** [comment]
> Oh I see, how do I have homebrew do it? Thanks for the response btw :)

Homebrew is a package manager specifically built for this purpose. Generally running `brew upgrade` every now and then is enough to keep everything up to date.

> Also do you happen to know what error code 9 means?

That issue affects all macOS users, doesn't break anything though. Its just a cosmetic bug: https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/145

> is the chromium 126 not for macos atm

No not yet, there have been issues with the build process for macOS. You can always check https://github.com/ungoogled-software/ungoogled-chromium-macos/releases for the latest release available on macOS (homebrew might take a bit longer longer to get the release from there as well)

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
