### ISSUE TITLE
Site data keep getting deleted after an update

### ISSUE THREAD

**Issue by mndctrlwpn** [ungoogled-software/ungoogled-chromium#2919]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

all

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

After running a flatpak update, ungoogled-chromium deletes all site data forcing you to log into everything again

### How to Reproduce?

1. Log into website on ungoogled chromium and check the box that says "keep me logged in"
2. Close window
3. Run "flatpak update" command in terminal
4. Open ungoogled chromium, no longer logged in

### Actual behaviour

Despite my settings set to "keep all cookies", every update seems to throw my cookies and site data out the window. This is frustrating, especially since I'm usually logged into many sites and cannot stand logging in all over again to all of them. Behaviour seems random; sometimes it happens and sometimes it doesn't, but the issue has persisted for months of updates now.

### Expected behaviour

I keep my cookies after an update.

**Comment by touba-denrael** [comment]
not perfectly sure if it is relevant because of the random behaviour you just described, but you might want to check if the `chrome://flags/#clear-data-on-exit` flag is on its default or disabled setting.

**Comment by mndctrlwpn** [comment]
It was indeed set to default, now disabled. Let's see if this helps. Might take some time to be sure.

That's strange, though. I've closed my browser many many times, is that not the same as exiting?

**Comment by touba-denrael** [comment]
the default setting [usually] should also be perfectly sufficient [my bad wording], the important thing is, it should not be set to `enabled`.

do not know much [or nearly enough] about using programs installed under flatpak, but my [low level] thinking is, the behaviour at closing the program should not be random, as your settings are stored in your home directory [outside of flatpak's reach].

you might also want to back up [or temporarily rename] your `.config/chromium` directory [or use the command line argument `--user-data-dir`] then try to run the program through the new empty profile created, testing if the behaviour persists after program closings.

**Comment by PF4Public** [comment]
@mndctrlwpn So, does it work properly now?

**Comment by mndctrlwpn** [comment]
> @mndctrlwpn So, does it work properly now?

Sadly no, meant to report on this again earlier. Behaviour is unchanged :(

**Comment by PF4Public** [comment]
@rany2 Sorry for pinging you, could we have yet another issue with flatpak?

**Comment by mndctrlwpn** [comment]
**Update:**
From what I can tell, this is **not** happening on my Arch system and only seems to happen on my Debian 12 (stable) system. Both use flatpak versions of ungoogled-chromium.
