### ISSUE TITLE
Domain editing to qjz9zk is done even for displaying help URLs!

### ISSUE THREAD

**Issue by original-birdman** [ungoogled-software/ungoogled-chromium#2937]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Ubuntu Lunar (112.0.5615.165)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Staring it up produces an error message about "No usable sandbox"

### How to Reproduce?

Juts start chromium in a terminal window and see the report.

### Actual behaviour

This:
```
[parent]: chromium 
[32549:32549:0704/021456.512354:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap (core dumped)
```

### Expected behaviour

The problem isn't the "No usable sandbox".

It is the fact that the message refers to:
```
https://chromium.9oo91esource.qjz9zk/chromium/src/+/main/docs/linux/uid_sandbox_development.md
```
Which is unusable, as the URL which is *printed* has suffered from the `qjz9zk` domain substitution.
Since this is just being displayed (not used) it should display the correct value.

**Comment by networkException** [comment]
This is expected, the domain substitution tooling cannot determine how URLs are used

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
