### ISSUE TITLE
Path for policies for flatpak

### ISSUE THREAD

**Issue by shellheim** [ungoogled-software/ungoogled-chromium#2939]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

126.0.6478.126

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

The poljcies path of `/etc/chromium/policies/managed/` doesn't work for flatpak.

### How to Reproduce?

1. Go to `/etc/chromium/policies/managed/` and make file called `policies.json`
2. Add any policy you want in that file
3. Go to `chrome://policy/` in the browser and see the value of the policy doesn't change. 

### Actual behaviour

The value of the policy in `/etc/chromium/policies/managed/policies.json` doesn't change.

### Expected behaviour

The value of the policy in `/etc/chromium/policies/managed/policies.json` changes as specified in the json file.

**Comment by shellheim** [comment]
Does anyone know where the policy path for the flatpak version is?

**Comment by rany2** [comment]
Example policy on flatpak: https://github.com/ungoogled-software/ungoogled-chromium-flatpak/tree/master/examples/policies/block-dinosaur-game

**Comment by shellheim** [comment]
That's the format I have my policy. That's not the problem, the problem is not knowing where to put the json file for flatpaks.

**Comment by shellheim** [comment]
Okay, I have no idea what that is nor does giving the flatpak permission to access `/etc/chromium/policies/managed/policies.json` work. But I'm gonna close the issue anyway because there's definitely a way but I am too dumb to get it.

**Comment by rany2** [comment]
You just build and install using flatpak-builder as you would with any flatpak.

**Comment by shellheim** [comment]
oh jesus christ why can't we just flick a switch like firefox. Thanks for the help man
