### ISSUE TITLE
Password manager not storing passwords

### ISSUE THREAD

**Issue by d3xtrx** [ungoogled-software/ungoogled-chromium#2941]
### OS/Platform

macOS

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

126.0.6478.126

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [X] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Passwords will not store in password manager

### How to Reproduce?

1: create password / attempt to import from csv
2: browse to chrome://password-manager/passwords
3: passwords are not listed

### Actual behaviour

Despite having a seemingly normal Login Data database, I cannot get chromium to save passwords nor can I import a passwords.csv or have it access the Login Data database. However, it seems cookies will retain login status. 

### Expected behaviour

Passwords normally appear in the interface.

### Relevant log output

```sh
N/A
```

### Additional context

I remember when upgrading chromium versions in the past (from release builds via homebrew) I would have to give access to the macos keychain, im assuming so it could read ~/Library/Application Support/Chromium/Default/Login Data. I noticed on this upgrade that prompt did not appear even after reinstall. Could this have to do with the new iCloud password feature? Login Data database is still populated with what seems to be the correct data however I have not attempted to decrypt the blobs. Running MacOS 14.5. 

Please let me know how I can assist in finding a solution to this. Thank you.

**Comment by Cubik65536** [comment]
Unfortunately, I, following these steps, cannot reproduce this issue.

Steps Followed:

1. Import passwords from a CSV.
2. Browse to `chrome://password-manager/passwords`

Everything is retained even after restarts.

> I noticed on this upgrade that prompt did not appear even after reinstall.

That prompt **should** reappear every time a new version is reinstalled, and I assume that this is where the problem comes from. I suggest that you find a way to do a complete fresh install and test again.

**Comment by d3xtrx** [comment]
Thanks for the response. 
Yeah most likely is a MacOS keychain issue or something. Weird though because I've been on 14.5 without modifying any settings for quite a while now and have had previous versions of chromium upgraded on 14.5 with no issue. I do not have time to troubleshoot further today but will report back when I find a solution in case someone else runs into this problem.

**Comment by easycat** [comment]
The issue I encountered is the same as the one you described.
130.0.6723.116（Official Build, ungoogled-chromium） (arm64)
OS: 15.1 (24B2083)
