### ISSUE TITLE
can't install on macOS, getting "Error: eloston-chromium: It seems the App source '/Applications/Chromium.app' is not there."

### ISSUE THREAD

**Issue by ComfortableMilk4454** [ungoogled-software/ungoogled-chromium#2943]
### OS/Platform

macOS

### Installed

OS/Platform's package manager

### Version

n/a, cuz cant install it lol

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

can't install on macOS, getting "Error: eloston-chromium: It seems the App source '/Applications/Chromium.app' is not there."

### How to Reproduce?

1. open terminal
2. paste `brew install --cask eloston-chromium`
3. press enter/return

### Actual behaviour

<img width="682" alt="image" src="https://github.com/ungoogled-software/ungoogled-chromium/assets/43555540/4999a279-e6cb-4bd7-9885-2dfc4c4b6171">

### Expected behaviour

for the browser to install

**Comment by networkException** [comment]
CC @Cubik65536

**Comment by Cubik65536** [comment]
Can you try to uninstall the app and reinstall it with the command? I cannot reproduce this issue on my end.

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/72877496/58271fca-38ae-4058-ad1d-08aaf51c4e5c)

**Comment by ComfortableMilk4454** [comment]
how do i uninstall it?

**Comment by Cubik65536** [comment]
`brew remove --cask eloston-chromium`

**Comment by ComfortableMilk4454** [comment]
uninstalling and reinstalling worked, ty!
