### ISSUE TITLE
Remove or neuter device profiling code in hangout_services/thunk.js

### ISSUE THREAD

**Issue by faisal** [ungoogled-software/ungoogled-chromium#2944]
### Description

Remove or neuter the private device profiling code in hangout_services/thunk.js, which is Google-specific at best but also possibly a privacy leak

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

From <https://simonwillison.net/2024/Jul/9/hangout_servicesthunkjs/>:

> It turns out Google Chrome (via Chromium) includes a default extension which makes extra services available to code running on the *.google.com domains - tweeted about today [by Luca Casonato](https://twitter.com/lcasdev/status/1810696257137959018), but the code has been there in the public repo [since October 2013](https://github.com/chromium/chromium/commit/422c736b82e7ee763c67109cde700db81ca7b443) as far as I can tell.
> 
> It looks like it's a way to let Google Hangouts (or presumably its modern predecessors) get additional information from the browser, including the current load on the user's CPU.

### Possible solutions

- Remove that code
- Add some level of noise to the answers

**Comment by kryptobolt200528** [comment]
The [flags.gn](https://github.com/ungoogled-software/ungoogled-chromium/blob/07e4bdd1da038c7a4423637e6e00ffdbe1695581/flags.gn) configuration file already seems to disable it.

**Comment by Nriver** [comment]
The feature was disabled 7 years ago, which is quite impressive. You can see the details in the code [here](https://github.com/ungoogled-software/ungoogled-chromium/blame/07e4bdd1da038c7a4423637e6e00ffdbe1695581/flags.gn#L5).

**Comment by rany2** [comment]
Actually at least 8 years ago, https://github.com/ungoogled-software/ungoogled-chromium/commit/4ec2494d218655d8770a9497c9de48c7d838b6ae#diff-419a299063c7e359df82dc3b04bf527820dfb7710976ff1332a5ad499c1392d5R14 :D
