### ISSUE TITLE
Remove Gemini

### ISSUE THREAD

**Issue by Suyun114** [ungoogled-software/ungoogled-chromium#2947]
### Description

Remove Gemini in such as search engine selections.

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

Google is promising to import Gemini into Chromium. Removing Gemini can make ungoogled-chromium more ungoogled.

### Possible solutions

Find all Gemini in source code and remove it.

**Comment by PF4Public** [comment]
> Google is promising

So is it already a problem or you're only anticipating it to be one? We cannot accept issues for things that _may_ occur in the future.

**Comment by Cubik65536** [comment]
Could you provide any source that says "Google is promising to import Gemini into Chromium."? I couldn't find anything other than "Gemini Now Integrated In Chrome" and similar stuff, and Chrome & Chromium are not the same thing.

**Comment by Cubik65536** [comment]
> > Google is promising
> 
> So is it already a problem or you're only anticipating it to be one? We cannot accept issues for things that _may_ occur in the future.

Chrome/Chromium has the feature of entering `@` in the address bar to talk to Gemini. I can confirm that UGC has this "feature", however as the Google-related address are substituted, this feature is de facto not working.

I personally wouldn't call this "not ungoogled enough" if the entry is just preserved, but maybe it is a good idea to completely remove related things.
