### ISSUE TITLE
Caret may be placed anywhere

### ISSUE THREAD

**Issue by jasursadikov** [ungoogled-software/ungoogled-chromium#2948]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

Version 126.0.6478.126 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I can place my caret anywhere, just click on any place in text and you can see the caret

### How to Reproduce?

1. Click next to text:
![image](https://github.com/user-attachments/assets/692b10c4-3847-451e-ae32-69565cc5ef8e)

### Actual behaviour

Caret could be placed anywhere user decides

### Expected behaviour

Should not have a caret anywhere else than text/input fields

**Comment by PF4Public** [comment]
What did you do prior to this happening?

**Comment by rany2** [comment]
Stupid question but did you enable caret mode by accident (i.e., does pressing F7 fix it)?

**Comment by jasursadikov** [comment]
@rany2 I had no idea that this kind of things exist! Thank you very much!
