### ISSUE TITLE
Secure DNS fails on .works domain

### ISSUE THREAD

**Issue by Nifury** [ungoogled-software/ungoogled-chromium#2962]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

127.0.6533.72

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

When Secure DNS is turned on, UG cannot resolve `.works` domain.

### How to Reproduce?

Turn on Secure DNS and set it to use anything other than OS default. 

`.works` domain then cannot be resolved and `ERR_NAME_NOT_RESOLVED` is returned. 

Example: https://howhttps.works/

Copied from: https://github.com/ungoogled-software/ungoogled-chromium/issues/2963

### Actual behaviour

-

### Expected behaviour

-

**Comment by PF4Public** [comment]
#Duplicate
