### ISSUE TITLE
Can't restore extensions

### ISSUE THREAD

**Issue by financiallyruined** [ungoogled-software/ungoogled-chromium#2968]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

126.0.6478.126-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Bookmarks, History and Settings are restored but extensions are not

### How to Reproduce?

1. Copy User Data from previous installation
2. Paste it in the User Data directory of the new installation

### Actual behaviour

Bookmarks, History and Settings are restored but extensions are not.

### Expected behaviour

Extensions are supposed to be restored like in the previous installation.

**Comment by tomasz1986** [comment]
You need to run the browser with `--disable-encryption --disable-machine-id`. As far as I am aware, you need to do this starting from the very first run in order to prevent the data from being encrypted and tied to the specific machine.

**Comment by financiallyruined** [comment]
Managed to get the extension working with all the configured settings and data intact by manual loading the unpacked extension in the Default/Extensions directory.
