### ISSUE TITLE
encrypted SNI support?

### ISSUE THREAD

**Issue by KweezyCode** [ungoogled-software/ungoogled-chromium#2973]
### Description

https://www.cloudflare.com/ru-ru/learning/ssl/what-is-encrypted-sni/

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

In Russia, some sites are blocked by SNI. Encrypted SNI helps bypass blocking

### Possible solutions

add support to chromium as in firefox

### Alternatives

firefox

**Comment by networkException** [comment]
This is fully dependent on upstream. A feature that complex and with real security and privacy implications is not well suited to be maintained here.

**Comment by networkException** [comment]
that wasn't on my radar, I assume not many servers support this yet

**Comment by rany2** [comment]
I think China blocks ESNI by downgrading the connection to TLS 1.2 somehow. Maybe they exported the technology to Russia :(

**Comment by dakusan** [comment]
I'm confused as to why this was closed. https://www.cloudflare.com/ssl/encrypted-sni/ still reports that encrypted SNI is not being used, but it's something that both Chrome and Brave have.

**Comment by PF4Public** [comment]
> I'm confused as to why this was closed. https://www.cloudflare.com/ssl/encrypted-sni/ still reports that encrypted SNI is not being used, but it's something that both Chrome and Brave have.

ungoogled-chromium on Linux:
![image](https://github.com/user-attachments/assets/45021fb5-939b-4936-ab7c-3f09ee550af0)

**Comment by dakusan** [comment]
Oh... huh... I'll see if I can't figure out why mine is showing as not secure sni. Thanks.

**Comment by KweezyCode** [comment]
> Wow wow wow, easy guys!
> 
> It is implemented in Chromium since like eternity: https://chromestatus.com/feature/6196703843581952. And is enabled by default. Just try it.
> 
> > In Russia, some sites are blocked by SNI. Encrypted SNI helps bypass blocking
> 
> Please note that it is very ISP-dependent, and mostly does not work. If you're trying to solve _this_ particular issue, you might get better luck with other solutions.

it is not enabled by default
![image](https://github.com/user-attachments/assets/469f620b-7723-4156-92c5-04891ded65c3)

**Comment by PF4Public** [comment]
Have you enabled DoH?

**Comment by KweezyCode** [comment]
> Have you enabled DoH?

i can't "enable" it in chromium, there is no such option

**Comment by PF4Public** [comment]
> i can't "enable" it in chromium, there is no such option

You must be kidding me, right?
https://support.google.com/chrome/answer/10468685?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cuse-a-secure-connection-to-look-up-a-sites-ip-address:~:text=Use%20a%20secure,custom%20service%20provider.

**Comment by KweezyCode** [comment]
> > i can't "enable" it in chromium, there is no such option
> 
> You must be kidding me, right? https://support.google.com/chrome/answer/10468685?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cuse-a-secure-connection-to-look-up-a-sites-ip-address:~:text=Use%20a%20secure,custom%20service%20provider.

topic is about encrypted client hello, not about DNS over HTTPS/TLS

**Comment by PF4Public** [comment]
> topic is about encrypted client hello, not about DNS over HTTPS/TLS

Indeed! And I already showed that it works by default as you can see here: https://github.com/ungoogled-software/ungoogled-chromium/issues/2973#issuecomment-2338782303

Have you tried to also check there?

I was trying to help you debug the website you linked, as it also shows "Using ECH" for me, but if that's not something you're willing to investigate, that's fine by me.

**Comment by KweezyCode** [comment]
> > topic is about encrypted client hello, not about DNS over HTTPS/TLS
> 
> Indeed! And I already showed that it works by default as you can see here: [#2973 (comment)](https://github.com/ungoogled-software/ungoogled-chromium/issues/2973#issuecomment-2338782303)
> 
> Have you tried to also check there?
> 
> I was trying to help you debug the website you linked, as it also shows "Using ECH" for me, but if that's not something you're willing to investigate, that's fine by me.

DNS over HTTPS is already enabled, but looks like it is chromium build issue. Just tried on mobile chromium and this site says ECH enabled for me, PC does not work. I will try to debug issue later

**Comment by dakusan** [comment]
I just noticed for me it's working now. Yay.
