### ISSUE TITLE
Implement flag to avoid blue bubble/s

### ISSUE THREAD

**Issue by thapabishwa** [ungoogled-software/ungoogled-chromium#2975]
### Description

Implement flag to avoid "user education" blue bubbles nudges (eg., "… give your browser a new look", Memory Saver)

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I'm always frustrated when "user education" blue bubbles nudges (eg., "… give your browser a new look", Memory Saver) show up.

### Possible solutions

Implement `--ash-no-nudges` like chrome upstream [documented here](https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md#commonly-unwanted-browser-features).

**Comment by PF4Public** [comment]
Is it not? https://github.com/ungoogled-software/ungoogled-chromium/blob/992a33ed3c0ebfc6afb62dca06436533424e1121/patches/extra/ungoogled-chromium/remove-uneeded-ui.patch#L32

**Comment by thapabishwa** [comment]
@opzch @PF4Public 

This is my user experience.
![image](https://github.com/user-attachments/assets/1b6fae18-0911-4fa3-a4fa-df19364dd3ca)

**Comment by thapabishwa** [comment]
@PF4Public @opzch 

This is my user experience at the moment.

![image](https://github.com/user-attachments/assets/666a9224-8658-4f9e-91ff-d649e5973bac)
