### ISSUE TITLE
On brower VPN implementatio (on start up)

### ISSUE THREAD

**Issue by elcepi** [ungoogled-software/ungoogled-chromium#2983]
### Description

Start an in browser VPN (on start up)

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Can we have an in browser VPN (for enhance privacy)?

### Possible solutions

Can we have an in browser VPN (for enhance privacy)?

### Alternatives

Using a system wide VPN

**Comment by rany2** [comment]
If you're on Flatpak, keep in mind that there is a bug that causes manually set proxies to not work properly. The issue also impacts those "VPN" extensions.

**Comment by elcepi** [comment]
@networkException it might be a silly question, but how do I install an extension.

**Comment by tomasz1986** [comment]
Please check https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore (or go straight to https://github.com/NeverDecaf/chromium-web-store if you want to install them directly from the Chrome Web Store).

**Comment by touba-denrael** [comment]
`chrome://ungoogled-first-run/` page, how-to section, install and update extensions part, describing the process, might also be helpful, pointing the same pages @tomasz1986 linked to.
