### ISSUE TITLE
set the policy to allow manifest v2 extensions by default

### ISSUE THREAD

**Issue by pcause** [ungoogled-software/ungoogled-chromium#2990]
### Description

set the policy ExtensionManifestV2Availability to a value of 2 to allow v2 extensions

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

google is getting rid of v2 extensions and this will block ublock origin and other important privacy software.  we need that back

### Possible solutions

set the value in your builds

**Comment by networkException** [comment]
already doing this https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/core/ungoogled-chromium/extensions-manifestv2.patch
