### ISSUE TITLE
Debian repo has very old chromium versions and unmaintained opensuse repo as well as binaries

### ISSUE THREAD

**Issue by philatelist1** [ungoogled-software/ungoogled-chromium#2998]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

112

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Old version of CHromium is present on Debian repo, will be unsafe for people who are unaware.

### How to Reproduce?

1. Go to https://github.com/ungoogled-software/ungoogled-chromium-debian
2. Notice that everything is outdated

### Actual behaviour

Shows outdated repos and binaries for everything.

### Expected behaviour

Expected for there to be links to the binaries of the official website

### Relevant log output

```sh
112.0.5615.165 (Official Build, ungoogled-chromium) running on Debian GNU/Linux (64-bit)
```

### Additional context

Sorry if this is irrelevant, new to github so thought I should contribute.
![112binaries](https://github.com/user-attachments/assets/7a25a236-837a-4794-bd29-c7008cd6cebf)
![OBSoldversion](https://github.com/user-attachments/assets/6d024584-89e7-4dca-ace3-24f8234ab6eb)

**Comment by PF4Public** [comment]
Even if it was an issue, we cannot do anything about that.

**Comment by philatelist1** [comment]
> Even if it was an issue, we cannot do anything about that.

Sorry, I don't know much about github so I just said it here, sorry for any inconvenience.
