### ISSUE TITLE
Inquiry About the Source of ungoogled-software.github.io

### ISSUE THREAD

**Issue by RBMLWizard** [ungoogled-software/ungoogled-chromium#3001]
### Description

Question About the ungoogled-software.github.io Website

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Hi,

First off, I want to thank the community for the amazing work on the ungoogled-software project. Your efforts are greatly appreciated!

I have a quick question: Is the website [ungoogled-software.github.io](https://ungoogled-software.github.io/) run by the official GitHub community for the ungoogled-software project, or is it managed by a different group or third-party site?

I just want to make sure I’m getting the software and information from the official and trusted source.

Thanks

### Possible solutions

.

**Comment by rany2** [comment]
https://github.com/ungoogled-software/ungoogled-software.github.io

**Comment by networkException** [comment]
github.io sites always match a github organization or user

**Comment by RBMLWizard** [comment]
Thank you for your replies. I performed a binary analysis, and it linked the executable to malicious IP so i wanted to double confirm since i am new to this github thing.

**Comment by PF4Public** [comment]
> it linked the executable to malicious IP

What led you to such conclusion? Which executable you mean specifically?

**Comment by RBMLWizard** [comment]
> > it linked the executable to malicious IP
> 
> What led you to such conclusion? Which executable you mean specifically?

Definitely false positive.
