### ISSUE TITLE
GTK theme doesn't follow OS GTK color scheme

### ISSUE THREAD

**Issue by bphd** [ungoogled-software/ungoogled-chromium#3002]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

Version 112.0.5615.165 (Official Build, ungoogled-chromium) (64 bits)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Don't switch to white or black when needed

### How to Reproduce?

Launch GNOME and UC, set GTK theme, switch between Default and Dark in GNOME

### Actual behaviour

All white

### Expected behaviour

Tab bar, address bar and bookmarks bar becoming black (Blink don't seems to have website color scheme managment like Gecko yet)

**Comment by networkException** [comment]
uhh how exactly did you install ungoogled-chromium? The version you are reporting is almost 1.5 years old and contains various zerodays!

**Comment by bphd** [comment]
> uhh how exactly did you install ungoogled-chromium? The version you are reporting is almost 1.5 years old and contains various zerodays!

Latest since UG stopped producing binaries



> GTK dark theme detection is broken in Chromium and wasn't ever fixed.

fix

**Comment by PF4Public** [comment]
> > GTK dark theme detection is broken in Chromium and wasn't ever fixed.
> 
> fix

[fix](https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium/files/chromium-128-gtk-fix-prefers-color-scheme-query.patch)

**Comment by bphd** [comment]
> > > GTK dark theme detection is broken in Chromium and wasn't ever fixed.
> > 
> > 
> > fix
> 
> [fix](https://github.com/PF4Public/gentoo-overlay/blob/master/www-client/ungoogled-chromium/files/chromium-128-gtk-fix-prefers-color-scheme-query.patch)

Upstream here
