### ISSUE TITLE
https://www.reddit.com/r/reddit/submit/ broken

### ISSUE THREAD

**Issue by bphd** [ungoogled-software/ungoogled-chromium#3003]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

latest

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

No form

### How to Reproduce?

https://www.reddit.com/r/reddit/submit/

### Actual behaviour

No form

### Expected behaviour

Form

**Comment by Ahrotahn** [comment]
Reddit admins are the only ones allowed to submit new posts to r/reddit

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by bphd** [comment]
> please specify the exact version number as advised by issue template please also try reproducing this issue with the empty profile as advised by issue template

112.0.5615.165-1



> Reddit admins are the only ones allowed to submit new posts to r/reddit

Only an example



> I hope your question(-s) has(-ve) been answered, otherwise please let us know. Closing this issue for now.

What answer has been produced?

**Comment by PF4Public** [comment]
> > please specify the exact version number as advised by issue template please also try reproducing this issue with the empty profile as advised by issue template
> 
> 112.0.5615.165-1

This version is not "latest", please try truly the latest version. Also please try reproducing this issue with empty profile.

**Comment by bphd** [comment]
> > > please specify the exact version number as advised by issue template please also try reproducing this issue with the empty profile as advised by issue template
> > 
> > 
> > 112.0.5615.165-1
> 
> This version is not "latest", please try truly the latest version. Also please try reproducing this issue with empty profile.

Latest binary available

**Comment by PF4Public** [comment]
> Latest binary available

[Package Details: ungoogled-chromium-bin 128.0.6613.113-1](https://aur.archlinux.org/packages/ungoogled-chromium-bin)

**Comment by bphd** [comment]
> > Latest binary available
> 
> [Package Details: ungoogled-chromium-bin 128.0.6613.113-1](https://aur.archlinux.org/packages/ungoogled-chromium-bin)

It's https://github.com/ungoogled-software/ungoogled-chromium-archlinux, not https://github.com/ungoogled-software/ungoogled-chromium

**Comment by networkException** [comment]
> It's https://github.com/ungoogled-software/ungoogled-chromium-archlinux, not https://github.com/ungoogled-software/ungoogled-chromium

What? Both the patchset and arch packaging are up to date with 128 releases

**Comment by bphd** [comment]
Neat for Arch Linux but distros are pulling from original repo so you need to produce binaries over there

**Comment by networkException** [comment]
I have no idea what you are talking about

**Comment by bphd** [comment]
not stale, still happening

**Comment by networkException** [comment]
Are you using M129 now?

**Comment by bphd** [comment]
Interesting question, do you know why we can't submit posts into Reddit specifically with unGoogled Chromium?

**Comment by networkException** [comment]
You have had the opportunity to provide debug information on this multiple times and you still chose to ignore the questions.

I see myself forced to close and lock the issue should this continue.

It has already been stated that this is unlikely do be related to ungoogled-chromium. Please make sure that you are running the latest version (starting with 129.) and that you *can't* reproduce the issue with vanilla chromium. If you have other constructive input then this is the place, otherwise, as stated above, I will close the issue.

**Comment by bphd** [comment]
I don't have debug informations, I just opened the website as is, without any logs. You can submit on Reddit you?

**Comment by bphd** [comment]
> proceed with this issue

**Comment by bphd** [comment]
> > proceed with this issue

**Comment by PF4Public** [comment]
@bphd Please stop spamming. I will close this issue. Feel free to add new information in order to proceed.

**Comment by bphd** [comment]
That's not spamming, the bot ask if the issue is resolved
