### ISSUE TITLE
Build fails when DCHECK is enabled

### ISSUE THREAD

**Issue by skrinakron** [ungoogled-software/ungoogled-chromium#3008]
### OS/Platform

Gentoo

### Installed

Compiled from source

### Version

128.0.6613.84

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Preference members that are otherwise patched out are still referenced in places compiled only when DCHECK is enabled.

### How to Reproduce?

Attempt to build ungoogled-chromium with GN flags `is_debug=true` and `dcheck_always_on=true`.

### Actual behaviour

The build fails in a portion guarded by `#if DCHECK_IS_ON()` due to references to members that are otherwise pacthed out.

### Expected behaviour

The build completes without errors even when DCHECK is enabled.

### Relevant log output

```sh
../../components/signin/internal/identity_manager/primary_account_manager.cc:400:47: error: no member named 'kGoogleServicesAccountId' in namespace 'prefs'
  400 |         client_->GetPrefs()->GetString(prefs::kGoogleServicesAccountId);
      |                                        ~~~~~~~^
../../components/signin/internal/identity_manager/primary_account_manager.cc:402:48: error: no member named 'kGoogleServicesConsentedToSync' in namespace 'prefs'
  402 |         client_->GetPrefs()->GetBoolean(prefs::kGoogleServicesConsentedToSync);
      |                                         ~~~~~~~^
```

### Additional context

The errors can be fixed simply by adding this chunk to the `components/signin/internal/identity_manager/primary_account_manager.cc` section of patches/core/ungoogled-chromium/remove-unused-preferences-fields.patch:
```diff
@@ -527,10 +399,9 @@ void PrimaryAccountManager::SetSyncPrimaryAccountInternal(
 
 #if DCHECK_IS_ON()
   {
-    std::string pref_account_id =
-        client_->GetPrefs()->GetString(prefs::kGoogleServicesAccountId);
+    std::string pref_account_id;
     bool consented_to_sync =
-        client_->GetPrefs()->GetBoolean(prefs::kGoogleServicesConsentedToSync);
+        false;
 
     DCHECK(pref_account_id.empty() || !consented_to_sync ||
            pref_account_id == account_info.account_id.ToString())
```

In #2034 it was concluded that this problem should be left unfixed and higher symbol levels used for debugging instead of DCHECK. Arguably, however:

 1. A DCHECK failure with its resulting backtrace can make for a much swifter diagnosis of a problem than loads of trace output.
 2. As seen in pf4public/gentoo-overlay#365, a trivially small fix like the above looks to be all it takes to build with DCHECKs enabled. This feels like a very small price to pay for avoiding guaranteed recurring showstoppers in some build configurations.

In light of the above, would you be willing to reconsider adding the fix to your patches?

**Comment by Ahrotahn** [comment]
I don't see a problem with adding that change.  You should make a PR, or one of us could add it to one of the next updates if you'd prefer.  

None of us test dcheck builds though, so it's possible it could become broken again in the future.

**Comment by skrinakron** [comment]
PR submitted. I wouldn't be too worried about breakage: you will notice if the added chunk stops applying cleanly, and if something else DCHECK-related comes up further down the line, we're no worse off than we are now – debug builds break and someone can make another pull request if they're interested enough.
