### ISSUE TITLE
Cant read video on some website

### ISSUE THREAD

**Issue by LucDeGit** [ungoogled-software/ungoogled-chromium#3010]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

129.0.6663.0

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Cant read video on X or Reddit 

### How to Reproduce?

1 : Go to x.com or reddit.com
2 : Try to watch a video 

### Actual behaviour

On x.com and reddit.com they indicate "This media cant be read"

### Expected behaviour

Video is played

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.

Please make sure first that you can reproduce this issue with contributor binaries from https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

Alternatively you may report this issue to where you've obtained the binary from.
