### ISSUE TITLE
Problem with chrome://settings/onStartup

### ISSUE THREAD

**Issue by Rusenche** [ungoogled-software/ungoogled-chromium#3011]
### OS/Platform

Windows

### Installed

Other (please use 'Additional context' field below to mention how exactly)

### Version

ungoogled-chromium_128.0.6613.84-1.1_windows_x64.zip

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Problem with chrome://settings/onStartup

### How to Reproduce?

Steps to reproduce the issue:
1. When starting the portable file from point 1 of @Hibbiki and when loading chrome://settings/onStartup - we mark "Continue from where you left off". In this case, we experimentally press the keyboard key F5 (refresh) several times and the page menu (chrome://settings/onStartup) remains exactly the same and the highlighted option continues to remain highlighted. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and the loaded tabs are exactly the same - everything is correct and that's how it should be.

2. When starting the portable file from point 2 of @teeminus and when loading chrome://settings/onStartup - we mark "Continue from where you left off". In this case, we experimentally press the keyboard key F5 (refresh) several times and the page menu (chrome://settings/onStartup) changes from a menu with three possible options to a menu with 4 options. And the highlighted option is no longer highlighted. Even if you mark an option again, if you press F5 (Refresh) from the keyboard again - you see that the marked option is demarked again. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and nothing is saved anymore - there are no tabs - the previously loaded tabs are gone. I remind you that before restarting the browser, "Continue from where you left off" was marked. But practically this is not the case and it is a problem that the tabs are not saved.

3. When starting the portable file from point 3 of @macchrome / @winchrome and when loading chrome://settings/onStartup - we mark "Continue from where you left off". In this case, we experimentally press the keyboard key F5 (refresh) several times and the page menu (chrome://settings/onStartup) changes from a menu with three possible options to a menu with 4 options. And the highlighted option is no longer highlighted. Even if you mark an option again, if you press F5 (Refresh) from the keyboard again - you see that the marked option is demarked again. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and nothing is saved anymore - there are no tabs - the previously loaded tabs are gone. I remind you that before restarting the browser, "Continue from where you left off" was marked. But practically this is not the case and it is a problem that the tabs are not saved.

### Actual behaviour

Problem with chrome://settings/onStartup

### Expected behaviour

Problem with chrome://settings/onStartup

### Additional context

Hello

Problem with chrome://settings/onStartup

I don't know since when this problem occurred, but this problem is a fact.

Testing was done with:
1. `chrome.nosync.7z` - `chromium-win64 v.128.0.6613.114-r1331488` - @Hibbiki - https://github.com/Hibbiki/chromium-win64/releases/tag/v128.0.6613.114-r1331488/ - [https ://github.com/Hibbiki/chromium-win64/releases/download/v128.0.6613.114-r1331488/chrome.nosync.7z](https://github.com/Hibbiki/chromium-win64/releases/download/v128.0.6613.114-r1331488/chrome.nosync.7z)
2. `ungoogled-chromium_128.0.6613.84-1.1_windows_x64.zip` - @teeminus - https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/128.0.6613.84-1.1/ungoogled-chromium_128.0.6613.84-1.1_windows_x64.zip
3. `ungoogled-chromium-128.0.6613.114-1_Win64.7z` - @macchrome / @winchrome - https://github.com/macchrome/winchrome/releases/tag/v128.6613.114-M128.0.6613.114-r1331488-Win64/

Steps to reproduce the issue:
1. When starting the portable file from point 1 of @Hibbiki and when loading chrome://settings/onStartup - we mark `Continue from where you left off`. In this case, we experimentally press the keyboard key `F5` (refresh) several times and the page menu (chrome://settings/onStartup) remains exactly the same and the highlighted option continues to remain highlighted. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and the loaded tabs are exactly the same - everything is correct and that's how it should be.

2. When starting the portable file from point 2 of @teeminus and when loading `chrome://settings/onStartup` - we mark `Continue from where you left off`. In this case, we experimentally press the keyboard key `F5` (refresh) several times and the page menu (`chrome://settings/onStartup`) _changes from a menu with three possible options to a menu with_ **4 options**. And the highlighted option is no longer highlighted. Even if you mark an option again, if you press `F5` (Refresh) from the keyboard again - you see that the marked option is demarked again. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and nothing is saved anymore - there are no tabs - the previously loaded tabs are gone. I remind you that before restarting the browser, `Continue from where you left off` was marked. But practically this is not the case and it is a problem that the tabs are not saved.

3. When starting the portable file from point 3 of @macchrome / @winchrome and when loading `chrome://settings/onStartup` - we mark `Continue from where you left off`. In this case, we experimentally press the keyboard key `F5` (refresh) several times and the page menu (`chrome://settings/onStartup`) _changes from a menu with three possible options to a menu with_ **4 options**. And the highlighted option is no longer highlighted. Even if you mark an option again, if you press `F5` (Refresh) from the keyboard again - you see that the marked option is demarked again. Then in a new tab we load any site - any - even https://github.com/. You restart the browser and nothing is saved anymore - there are no tabs - the previously loaded tabs are gone. I remind you that before restarting the browser, `Continue from where you left off` was marked. But practically this is not the case and it is a problem that the tabs are not saved.

And now I am attaching pictures to visualize the problem.

@Hibbiki - v.128.0.6613.114: Everything is correct here and that's exactly how it should be. 

https://i.postimg.cc/mrg2gyjW/Hibbiki-v-128-0-6613-114.png 

![Hibbiki - v 128 0 6613 114](https://github.com/user-attachments/assets/d476d82c-4885-4a4f-8dc1-820a61862582)

@teeminus - v.128.0.6613.84-1.1 `before refresh` (`F5`) - https://i.postimg.cc/V6Sfjs27/teeminus-v-128-0-6613-84-1-1-before-refresh.png

![teeminus - v 128 0 6613 84-1 1 before refresh](https://github.com/user-attachments/assets/939acb24-a939-48a6-bf91-90a2ed154085)

@teeminus - v.128.0.6613.84-1.1 `after refresh` (`F5`) - https://i.postimg.cc/FFLFzRyz/teeminus-v-128-0-6613-84-1-1-after-refresh.png

![teeminus - v 128 0 6613 84-1 1 after refresh](https://github.com/user-attachments/assets/50c0cacb-51f9-4973-956c-39f9d5a36e08)

I don't need to show an image that doesn't have any tabs loaded because that's how the browser loads in **scenarios 2 and 3**.

I'm not attaching a picture for @macchrome / @winchrome because there browser behavior is exactly the same as @teeminus's browser behavior.

**Comment by BabyFnord** [comment]
Same behaviour confirmed for `eloston-chromium 128.0.6613.84` (Official Build, ungoogled-chromium) (arm64): 
Except for adding custom search engines and setting them as standard, no other setting is persistent in `chrome://settings/`.

**Comment by trueno2k** [comment]
If anyone is having this issue with saving chrome://settings/onStartup setting to "continue where you left off" or "open a specific page or set of pages" setting, then all you have to do for now is go to "About Chromium" option on the "three dots" menu and then there click on "On start-up" option in Settings and that will allow you set your tabs saves settings again.  If you're already in Settings, then click on "About Chromium" then click back "On start-up" and that will do the same thing as above.  Hopes this helps for now...

**Comment by Nifury** [comment]
> see if applying this after the ungoogled-chromium patches solves the issue:

Yes, just confirmed that this patch solves the issue. Thanks!

**Comment by trueno2k** [comment]
Apparently this issue isn't an ungoogled-chromium issue this issue is actually happening to official build of the chrome browser, I tested the bug on the latest release 128.0.6613.120 of chrome browser on windows and this issue still exists there aswell, so I would hazard a guess this issue can not be resolved by the devs here, no?
