### ISSUE TITLE
TikTok web bad audio quality

### ISSUE THREAD

**Issue by IIBartII** [ungoogled-software/ungoogled-chromium#3019]
### OS/Platform

Fedora and CentOS

### Installed

Flatpak

### Version

128.0.6613.113

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

bad audio quality(like 64kbps on TikTok (all flags off)

### How to Reproduce?

play randrom video on tiktok web

### Actual behaviour

64kbps like audio

### Expected behaviour

normal quality i quess? on chrome everything good

**Comment by PF4Public** [comment]
It would help if you showed the screenshot of the "Media" tab from devtools.

**Comment by IIBartII** [comment]
![image](https://github.com/user-attachments/assets/970af5ec-d10a-4c3b-9110-305874c3596c)
this?

**Comment by IIBartII** [comment]
![image](https://github.com/user-attachments/assets/993896d6-b265-40b8-8f33-44cdc9417e5e)
this?

**Comment by PF4Public** [comment]
This one:
![image](https://github.com/user-attachments/assets/0a25a713-f1ab-4005-98c2-db2d649092e6)
