### ISSUE TITLE
sync from other browsers

### ISSUE THREAD

**Issue by jamescraft10** [ungoogled-software/ungoogled-chromium#3022]
### Description

sync from firefox, chromium browsers.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

When I switched from Firefox to ungoogled chromium there was no sync.

### Possible solutions

Do what other browsers do for Firefox and for chromium based browsers copy the User Data directory which is in %appdata%/../Local/Google/Chrome/User Data/ on Windows for Google Chrome

**Comment by PF4Public** [comment]
Duplicate of #667?

**Comment by jamescraft10** [comment]
> Duplicate of #667?

yes
