### ISSUE TITLE
YouTube "Something went wrong. Refresh or try again later."

### ISSUE THREAD

**Issue by joopbraak** [ungoogled-software/ungoogled-chromium#3038]
I have the same problem, without being logged on into an account. After 30 seconds. It's a live video.  I use NoScript and if I allow script from google.com and gstatic.com the problem is gone.
I also use uBlock Origin.
The strange thing too is that other youtube video's don't give this error, also videos longer then 20 minutes.

![Youtube error](https://github.com/user-attachments/assets/40e65039-a8c6-4849-9514-8a92d9ef7889)

_Originally posted by @joopbraak in https://github.com/ungoogled-software/ungoogled-chromium/issues/3012#issuecomment-2371115429_

**Comment by joopbraak** [comment]
I don't think having to disable hardware acceleration is a real solution to the problem.

**Comment by joopbraak** [comment]
So i just tried on my Linux machine with the latest version of ungoogled-chromium and allowing script from google.com and gstatic.com is actually not enough, I have to disable NoScript completely.

**Comment by PF4Public** [comment]
Which version of NoScript do you have? Have you tried updating it?
Which version of uBlock Origin  do you have? Have you tried updating it?

**Comment by joopbraak** [comment]
Latest versions (I use Chromium Web store from NeverDecaf):
NoScript 11.4.39
uBlock Origin 1.59.0

CuQsnvbpqPk

**Comment by joopbraak** [comment]
Have been trying out some things and it's kind of unpredictable when it happens, Also Google is changing code all the time to try to make applications like ungoogled-chromium and yt-dlp stop working. I can't even install extensions from Chrome web store anymore, I have to manually download the CRX and then drop it in the extensions manager window with Developer mode enabled. I will keep troubleshooting, but for now I have a way to solve it, so I don't wanna waste any more of your time.
Cheers!

**Comment by PF4Public** [comment]
> I have a way to solve it

So what is the solution? Might help someone in the future.

**Comment by joopbraak** [comment]
What I said, in NoScript, allowing script from google.com and gstatic.com. At a certain point I thought I pinned it down to allowing fetch for Default sites in NoScript (I normally don't allow anything for Default sites), but that was not really reproducible.

![NoScript default setting](https://github.com/user-attachments/assets/8486408c-210f-4f36-a60c-536719fe7c1d)

**Comment by joopbraak** [comment]
Oh sorry, I contradict myself.  I said earlier I had to disable NoScript completely. It depends if you allow frame, fetch, noscript and other (the standard NoScript setting) for Default sites, I think.
Not in the mood to test it any further, especially since it changes everytime. I will do that next tme I encounter the problem.

**Comment by PF4Public** [comment]
I'm sorry that we have multiple separate issues with this very problem. I've chosen one of them: https://github.com/ungoogled-software/ungoogled-chromium/issues/3012 and pinned it. Please continue the discussion there. Thanks!
