### ISSUE TITLE
When using Microsoft Teams, the page gets reloaded every time I hit F11

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [ungoogled-software/ungoogled-chromium#3059]
### OS/Platform

Arch Linux

### Installed

OS/Platform's package manager

### Version

129.0.6668.100-1

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

It is quite annoying, as it causes a delay of some seconds.

### How to Reproduce?

1. Go to https://teams.microsoft.com
2. login
3. Press F11 to go to full screen, and the page gets reloaded
4. Press F11 to go back to normal size, and the page gets reloaded again

### Actual behaviour

Page gets reloaded

### Expected behaviour

Not to reload, as it happens with Opera and Chrome.

### Additional context

Currently I use ungoogled chromium only for teams.  I've made an application for it.

I'm using CachyOS

```
❯ pacman -Q|grep ungoog
ungoogled-chromium-bin 129.0.6668.100-1
```
I haven´t changed any settings.

**Comment by PF4Public** [comment]
Is there anything interesting in DevTools console?

**Comment by DavidPerezIngeniero** [comment]
A lot of messages appear on the Javascript console when I hit F11:
![image](https://github.com/user-attachments/assets/09a2f644-7e1c-4ba0-87f2-e9d7bea4c271)

**Comment by DavidPerezIngeniero** [comment]
If I resize the window, it isn't reloaded.

**Comment by PF4Public** [comment]
Are there any blocked requests in network tab?

**Comment by DavidPerezIngeniero** [comment]
![image](https://github.com/user-attachments/assets/36ee24fb-f764-4d63-866b-09643e4aed6d)

With the network tab I've checked that it reloads all.

**Comment by PF4Public** [comment]
Please try empty profile via `--user-data-dir=/tmp/something` to exclude extensions and any possible settings.

**Comment by DavidPerezIngeniero** [comment]
Now it goes ok. 
Thanks for your support.

**Comment by DavidPerezIngeniero** [comment]
When I install the application, then F11 has strange behaviour and reloads.

**Comment by PF4Public** [comment]
Check your extensions or settings.

**Comment by DavidPerezIngeniero** [comment]
No extensions, only default settings.

If I use this extension in order to hide address bar, I repeat the bad behaviour of F11 key.
https://chromewebstore.google.com/detail/open-as-popup/ncppfjladdkdaemaghochfikpmghbcpc

Conclusion: when address bar is hidden, pressing F11 reloads the page, otherwise it doesn't reload.

**Comment by PF4Public** [comment]
> If I use this extension in order to hide address bar, I repeat the bad behaviour of F11 key.

So it is not an issue of ungoogled-chromiun, but an extension?

**Comment by DavidPerezIngeniero** [comment]
I've done already the test of starting with a clean profile.
And it works ok.
But when I convert it as an app, with no address bar, then F11 provokes reloading.

**Comment by PF4Public** [comment]
It could be an upstream issue, we cannot fix.

**Comment by DavidPerezIngeniero** [comment]
OK, now that I know the cause is the hidden address bar, I can close the issue.
