### ISSUE TITLE
Enable specific language for user interface

### ISSUE THREAD

**Issue by d1Bihkte** [ungoogled-software/ungoogled-chromium#3061]
### Description

Could you please enable Sinhala (si or si_LK) language for ungoogled chromium interface?

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

Google doesn't enable this language for UI saying "binary size constraints" but other chormium based browsers already have this language enabled.

https://issues.chromium.org/issues/40073213

What is "binary size constraints"?
I got these details from another party and this response from google. I guess this is not a problem for you and i hope to use the next ungoogled version in Sinhala.

> There are currently no plans to add it due to binary size constraints. That may be revisited by the Desktop team in the future.
> Binary size increases are what's blocking Desktop Chrome from adding more languages. Each language is approximately 250kb, and any binary size increase causes a drop in updates.

![Screenshot from 2024-10-17 12-49-48](https://github.com/user-attachments/assets/91281d41-bd72-40a9-a749-3cd94948728e)
(windows)

**Comment by PF4Public** [comment]
Sorry, but your request is outside of the project goals. If the localisation in question is available in the source tree, it could be doable as it would be a packaging issue. It would be unfortunately impossible otherwise. 

I don't know whether this localisation is shipped with Windows (@Nifury and @teeminus may know better), but in Linux it seems to be absent.

**Comment by joopbraak** [comment]
Could you not just copy the pak file from that specific browser you mention (curious which one it is) into the ungoogled chromium Locales folder?
By the way, the size restraint is bullshit of course, Google could easily implement downloading the language file once you select the interface language, just like they do with spelling languages.

**Comment by PF4Public** [comment]
> Could you not just copy the pak file from that specific browser you mention (curious which one it is) into the ungoogled chromium Locales folder?

I can ask you the same question. Have you tried taking localisation file from other browser and using it in ungoogled-chromium?

> implement downloading the language

This one would be actually _against_ the goals of the project.

**Comment by joopbraak** [comment]
> > Could you not just copy the pak file from that specific browser you mention (curious which one it is) into the ungoogled chromium Locales folder?
> 
> I can ask you the same question. Have you tried taking localisation file from other browser and using it in ungoogled-chromium?

Sorry, it was meant as a response to d1Bihkte.

> > implement downloading the language
> 
> This one would be actually _against_ the goals of the project.

I  didn't mean ungoogled-chromium should do this, I was talking about Google could do this. Not including all languages in the binary but instead downloading the interface language file once you select it would make the binary a lot smaller.
Of course I don't expect this project to implement that functionality!

**Comment by d1Bihkte** [comment]
>I don't know whether this localisation is shipped with Windows (@Nifury and @teeminus may know better), but in Linux it seems to be absent.

@PF4Public They have the problem mentioned above, so they don't ship si.pak file with Chrome releases.

>Google could easily implement downloading the language file once you select the interface language, just like they do with spelling languages.

@joopbraak i think this is not a good solution and will be a problem for some deployment environments that don't allow their devices to connect to Google servers. They can include this language file in the setup as others have already done.

"Each language is approximately 250kb, and any binary size increase causes a drop in updates."
They have said this. Maybe a problem with their update mechanism. 😃

>Could you not just copy the pak file from that specific browser you mention (curious which one it is) into the ungoogled chromium Locales folder?

>I can ask you the same question. Have you tried taking localisation file from other browser and using it in ungoogled-chromium?

I haven't tried this because popular chrome forks strings are in different order and i guess this method doesn't work because I think I have to modify the code and build it from source. (+ i don't know more about software development)

>implement downloading the language
>>This one would be actually against the goals of the project.

@PF4Public I'm not asking to implement a whole new "download languages" feature. I've noticed that other Chromium-based browsers get translations from the Chromium project for Chromium strings and only translate their own strings. 

If i am right, Ungoogle-chromium does not have new strings or UI additions except `chrome://ungoogled-first-run/`
Ungoogled chromium is my main browser. That's why I wanted to ask. :)

**Comment by PF4Public** [comment]
> Chromium-based browsers get sinhala translations from the Chromium project

Do you know how do they do it?

**Comment by PF4Public** [comment]
Additional locales could be enabled by https://github.com/ungoogled-software/ungoogled-chromium/pull/3072
