### ISSUE TITLE
WebAssembly WASM not present, sites that need it don't work, can't find browser option for it

### ISSUE THREAD

**Issue by NearestWater262** [ungoogled-software/ungoogled-chromium#3086]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

Version 130.0.6723.91 (Official Build, ungoogled-chromium) (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

I need WebAssembly for a site to work but I cannot find any settings to turn on WASM anywhere

### How to Reproduce?

1. go to pass.proton.me
2. It complains that it needs WASM but I cannot find any settings for WASM

### Actual behaviour

![image](https://github.com/user-attachments/assets/f41fbfaa-1cde-4dbd-8722-bb2d120a66a7)

Then I click the site settings button at the address bar, and click "Site Settings" but I only see these settings. Am I missing something? I don't see anything about WASM

![image](https://github.com/user-attachments/assets/3fa23af1-6004-4c8d-97de-4fe013ea29fc)
![image](https://github.com/user-attachments/assets/f3257fbc-8430-479b-a7c7-dd440e30bc58)

I also went to the chrome flags and turn all of these on and relaunched but still didnt work

![image](https://github.com/user-attachments/assets/608b64b5-8ad8-46b7-ad47-81b61c37a921)

### Expected behaviour

I expect to see an option for WASM **somewhere**

### Additional context

I also checked this issue but I guess the browser does not look like these screenshots anymore
https://github.com/ungoogled-software/ungoogled-chromium/issues/2466

**Comment by networkException** [comment]
Do you have JavaScript JIT disabled for the site?

**Comment by NearestWater262** [comment]
@networkException there is no option in site settings for JIT or WASM at all, you can see the screenshot of all the site settings that I'm given :)

**Comment by NearestWater262** [comment]
The only thing remotely close I could find was this "V8 optimizer" but I don't know if this the same as turning on WASM/JIT itself. Regardless, it's turned on for all site yet still I'm getting the error on the site
![image](https://github.com/user-attachments/assets/e6f590fc-3041-47c4-a711-0d950d964993)

**Comment by networkException** [comment]
ah right it was called that; yes if you disable that WASM wouldn't work. Not sure why it doesn't for you now

**Comment by networkException** [comment]
Is this reproducible in incognito (without login)?

**Comment by NearestWater262** [comment]
@networkException I opened Incognito window and went to the proton pass site and immediate got the same WASM error

**Comment by NearestWater262** [comment]
I also went to this issue: https://github.com/ungoogled-software/ungoogled-chromium/issues/2466

And tried the same site that this person uses, https://regex101.com/
and got this error as well

![image](https://github.com/user-attachments/assets/19b53b33-025c-4384-bb26-dfa83d5f7d45)

**Comment by networkException** [comment]
@rany2 is this obvious to you?

**Comment by NearestWater262** [comment]
well, I am a very stupid person :( 
I totally forgot that I had added thechromium flag `--js-flags="--jitless"` to my execution command 
sorry to take up your time!

**Comment by networkException** [comment]
No problem, glad it could be solved
