### ISSUE TITLE
Under the Nouveau driver, in the Chinese input method, in fcitx5, Under wayland settings ，Pinyin will turn yellow

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium#3091]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

OS/Platform's package manager

### Version

laster

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

https://github.com/fcitx/fcitx5/issues/1164

### How to Reproduce?

1.Nouveau drive
2.fcitx5
3.chrome://flags
Preferred Ozone platform wayland
text-input-v3 enabled

### Actual behaviour

Pinyin  turn yellow

### Expected behaviour

Pinyin will not turn yellow

**Comment by PF4Public** [comment]
I assume it is an upstream issue, which is outside of the scope of the project, right?
