### ISSUE TITLE
Remove Client Hints flag only works on the first request

### ISSUE THREAD

**Issue by Bosnier** [ungoogled-software/ungoogled-chromium#3105]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

131

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Browser sends sec-ch-ua headers even if the #remove-client-hints flag enabled

### How to Reproduce?

1. Enable `#remove-client-hints` flag
1. Open any site that returns request headers
1. Make sure that the sec-ch-ua headers have not been sent
1. Send the same request to the site in devtools console using fetch
1. Get the sec-ch-ua headers in the response

Or just open any other site and check the network tab in devtools

### Actual behaviour

Browser sends sec-ch-ua headers even if the `#remove-client-hints` flag enabled

### Expected behaviour

Browser doesn't send sec-ch-ua headers even if the `#remove-client-hints` flag enabled

### Additional context

![image](https://github.com/user-attachments/assets/a5f7e3e7-8205-4993-8ef7-f0310748bee8)
![image](https://github.com/user-attachments/assets/bcb7f1d4-21c6-47e3-a74c-f0ff28c8ca5f)

**Comment by Ahrotahn** [comment]
It seems that fetches from the dev tools get the hints from a different section.  I'll start working on a new PR to update how that's handled.

**Comment by PF4Public** [comment]
@Bosnier It would be great if you could verify the fix with the next release.

**Comment by Bosnier** [comment]
Everything works fine. Thanks
