### ISSUE TITLE
[Not really an issue] Is it possible to add an adblock thats not an extension to ungoogled chromium (like brave)

### ISSUE THREAD

**Issue by Twig6943** [ungoogled-software/ungoogled-chromium#3107]
### OS/Platform

Android

### Installed

Compiled from source

### Version

placeholder

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Switched to firefox cuz of all the manifest v3 bullshit

### How to Reproduce?

placeholder

### Actual behaviour

placeholder

### Expected behaviour

placeholder

### Relevant log output

```sh
placeholder
```

### Additional context

(Sorry for creating this issue)

**Comment by PF4Public** [comment]
>Is it possible

More or less. Given that Cromite has one implemented it seems possible.

Is it being worked on?

No. Definitely not. Re-implementation of uBlockOrigin with the aim of embedding is also unlikely:  https://github.com/ungoogled-software/ungoogled-chromium/issues/662#issuecomment-1841770642
