### ISSUE TITLE
Consider enable chrome://new-tab-page rather than chrome://new-tab-page-third-party

### ISSUE THREAD

**Issue by xycabcd** [ungoogled-software/ungoogled-chromium#3116]
### Description

Use the better new tab page usually only used for Google

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

In Google Chrome, the better new tab page (the one with theme, shortcuts...) only work with google.com as search engine, and in Ungoogled Chromium, it work with nothing.

### Possible solutions

Make this better new tab page avalible for every search engine.

**Comment by joopbraak** [comment]
https://support.google.com/chrome/answer/11032183

"To customize your New Tab page, you must be signed in to your Google Account and use Google as your default search engine"

So not possible for Chromium ungoogled, I think.

**Comment by xycabcd** [comment]
On my end, it's fine with it.

https://github.com/user-attachments/assets/20212c2d-693b-4d68-bb57-606d5ad68035

**Comment by PF4Public** [comment]
Have you tried [--custom-ntp](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.)?

**Comment by xycabcd** [comment]
> Have you tried [--custom-ntp](https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md#:~:text=%2D%2Dcustom%2Dntp,chrome%3A//%20internal%20page.)?

Thanks
