### ISSUE TITLE
Allow web extensions save file without saveAs dialog and with custom file name

### ISSUE THREAD

**Issue by diimdeep** [ungoogled-software/ungoogled-chromium#3118]
### Description

Allow web extensions to not show saveAs and rename file

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I am not sure if this is limitation of chromium or bug, can anyone clarify? 

In firefox web extensions like `SingleFile`, `DownThemAll!`, `Save In…` can save file without save as dialog and with custom file name. This does not work for me in chromium.

this might be related

https://issues.chromium.org/issues/41133685
https://issues.chromium.org/issues/41340668

### Possible solutions

web ext. can save file without saveAs dialog and with custom file name

**Comment by joopbraak** [comment]
In chrome://settings/downloads, do you have "Ask where to save each file before downloading" disabled?

**Comment by joopbraak** [comment]
If it doesn't work in Chromium, it's not gonna work in Chromium ungoogled either.
