### ISSUE TITLE
"Clear HTTP auth cache" menu item out-of-date (crashes browser)

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium#761]
Using the "Clear HTTP auth cache" menu item causes the entire browser to segfault in 74.0.3729.108. Will need to investigate.

**Comment by Eloston** [comment]
Since this is an extra feature (it lives under `patches/extra`), it will be removed until it is fixed.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
