### ISSUE TITLE
File System entries are not deleted after browser start up

### ISSUE THREAD

**Issue by arau0** [ungoogled-software/ungoogled-chromium#998]
**Describe the bug**
File System entries are not deleted after browser start up

**To Reproduce**
I am not sure if that's normal behavior but in different versions  of Ungoogled-Chromium I see sites, which used "File System" to have entries at chrome://settings/siteData 
This entries are staying after Ungoogled-Chromium is closed and open again and there are not whitelisted.

Example of site which I used  and the "File System" is present https://www.theguardian.com/

**Expected behavior**
The normal bahavior in my understanding is unless the user is whitelisted them, everything should be cleared at browser start up.

**Environment (please complete the following information):**
 - Windows 10

**Comment by Ph0rk0z** [comment]
I can confirm this to be the case. Some site's data is left in there.

**Comment by Eloston** [comment]
What kind of data is stored in "File System"?

**Comment by Ph0rk0z** [comment]
No idea. This is what shows up... 
![sitedata](https://user-images.githubusercontent.com/59298527/79086536-0b3a5400-7d02-11ea-8fe5-18167d1c75e4.png)

And after browser restart:

![data2](https://user-images.githubusercontent.com/59298527/79086587-32912100-7d02-11ea-9412-95242fc0ae4d.png)

**Comment by arau0** [comment]
@Eloston to be fair I don't know :)

@Ph0rk0z Thank you for your screenshoots.

Maybe somebody else could have appropriate information about that?

**Comment by arau0** [comment]
I am not sure if the "File System" entries at chrome://settings/siteData have any connections with the "Native File System API". There is flag at chrome://flags/#native-file-system-api

"The Native File System API (formerly known as the Writeable Files API), is available as an origin trial in Chrome 78 (beta in September, stable in October) and later. It is part of capabilities project, and this post will be updated as the implementation progresses."*

*https://web.dev/native-file-system/

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
